// play-demos.js — single source of truth for the Play demos.
// Loaded before visualize-app.jsx (the Visualize hub). Status: LIVE | SOON.
// `lesson` is a path (relative to site root) to the matching /learn/ lesson, or null.

window.PLAY_DEMOS = {
  demos: [
    { slug: "pathfinding",        topic: "SEARCH",        title: "A* Pathfinding",        tone: "blue",   status: "LIVE",
      blurb: "Draw walls, drop a start and goal, and watch A* (or Dijkstra, BFS, Greedy) search for the shortest path." },
    { slug: "kmeans",             topic: "UNSUPERVISED",  title: "K-Means Clustering",    tone: "violet", status: "LIVE",
      blurb: "Scatter points, pick k, and step through assign-and-update until the centroids settle." },
    { slug: "gradient-descent",   topic: "OPTIMIZATION",  title: "Gradient Descent",      tone: "blue",   status: "LIVE",
      blurb: "Drop a ball on a loss surface and race SGD, Momentum, RMSProp, and Adam down to the minimum." },
    { slug: "overfitting",        topic: "ML THEORY",     title: "Overfitting Lab",       tone: "violet", status: "LIVE",
      blurb: "Fit a polynomial to noisy data and watch the bias-variance tradeoff and overfitting play out." },
    { slug: "roc",                topic: "ML THEORY",     title: "ROC, PR & Thresholds",  tone: "blue",   status: "LIVE",
      blurb: "Slide a decision threshold across two score distributions and watch precision, recall, ROC, and PR trade off." },
    { slug: "decision-tree",      topic: "CLASSICAL ML",  title: "Decision Tree",         tone: "violet", status: "LIVE",
      blurb: "Watch a CART tree carve the plane into axis-aligned regions — and overfit as it deepens." },
    { slug: "knn",                topic: "CLASSICAL ML",  title: "k-Nearest Neighbors",   tone: "blue",   status: "LIVE",
      blurb: "Vote among the k closest points; tune k to trade a jagged boundary for a smooth one." },
    { slug: "svm",                topic: "CLASSICAL ML",  title: "SVM - Margins & Kernels", tone: "blue", status: "LIVE",
      blurb: "Find the widest-margin boundary, see the support vectors that define it, then bend it with the kernel trick." },
    { slug: "pca",                topic: "UNSUPERVISED",  title: "Principal Component Analysis", tone: "violet", status: "LIVE",
      blurb: "Find the axes of greatest variance via a real covariance eigen-decomposition, then project onto them." },
    { slug: "gmm",                topic: "UNSUPERVISED",  title: "Gaussian Mixtures & EM", tone: "violet", status: "LIVE",
      blurb: "Soft clustering by Expectation-Maximization — fit overlapping Gaussians and watch the log-likelihood climb." },
    { slug: "clt",                topic: "PROBABILITY",   title: "Central Limit Theorem", tone: "violet", status: "LIVE",
      blurb: "Average samples from any distribution and watch the means pile up into a Gaussian." },
    { slug: "attention",          topic: "TRANSFORMERS",  title: "Attention Heatmap",     tone: "violet", status: "LIVE",
      blurb: "Type a sentence and see scaled dot-product attention decide which tokens look at which.", lesson: "learn/transformers/self-attention/" },
    { slug: "positional-encoding",topic: "TRANSFORMERS",  title: "Positional Encoding",   tone: "blue",   status: "LIVE",
      blurb: "Visualize how sinusoidal and rotary encodings inject order into a transformer." },
    { slug: "multi-head-attention", topic: "TRANSFORMERS", title: "Multi-Head Attention", tone: "violet", status: "LIVE",
      blurb: "Several real attention patterns in parallel — flip between heads and watch each one specialize on the same sentence." },
    { slug: "tokenizer",          topic: "NLP",           title: "Tokenizer Lab",         tone: "violet", status: "LIVE",
      blurb: "Watch BPE carve your text into subword tokens — trained live in the browser." },
    { slug: "markov",             topic: "NLP",           title: "Markov Text Generator", tone: "blue",   status: "LIVE",
      blurb: "The simplest language model — count which token follows which, then sample. The ancestor of every LLM." },
    { slug: "decoding",           topic: "NLP",           title: "Decoding Strategies",   tone: "violet", status: "LIVE",
      blurb: "Temperature, top-k, and top-p — how the same model becomes safe or wild depending on how you sample." },
    { slug: "gridworld-rl",       topic: "RL",            title: "Q-Learning Gridworld",  tone: "blue",   status: "LIVE",
      blurb: "Watch a Q-learning agent learn a policy in a gridworld, one episode at a time." },
    { slug: "bandit",             topic: "RL",            title: "Multi-Armed Bandit",    tone: "violet", status: "LIVE",
      blurb: "Explore vs exploit: pit ε-greedy, UCB, and Thompson sampling against each other." },
    { slug: "value-iteration",    topic: "RL",            title: "MDP Value Iteration",   tone: "blue",   status: "LIVE",
      blurb: "Solve a gridworld exactly — Bellman backups propagate value out from the goal, inducing the optimal policy." },
    { slug: "neural-playground",  topic: "NEURAL NETS",   title: "Neural Playground",     tone: "blue",   status: "LIVE",
      blurb: "Train a tiny neural net live on 2D data and watch the decision boundary form." },
    { slug: "activations",        topic: "NEURAL NETS",   title: "Activation Functions",  tone: "blue",   status: "LIVE",
      blurb: "Plot sigmoid, tanh, ReLU, GELU and their gradients — and see where gradients vanish." },
    { slug: "convolution",        topic: "COMPUTER VISION", title: "Convolution Lab",     tone: "violet", status: "LIVE",
      blurb: "Apply and design kernels on an image to see what each filter detects." },
    { slug: "nms",                topic: "COMPUTER VISION", title: "IoU & Non-Max Suppression", tone: "blue", status: "LIVE",
      blurb: "Turn a cloud of overlapping detection boxes into one clean box per object with IoU + greedy NMS." },
    { slug: "diffusion",          topic: "GENERATIVE",    title: "Diffusion Sampler",     tone: "blue",   status: "LIVE",
      blurb: "Step through a denoising chain turning pure noise into samples from a 2D distribution." },
    { slug: "vae",                topic: "GENERATIVE",    title: "Variational Autoencoder", tone: "violet", status: "LIVE",
      blurb: "Train a tiny VAE live — reparameterization, a KL-shaped latent space, and generation from pure noise." },
    { slug: "fourier",            topic: "SIGNAL",        title: "Fourier Series",        tone: "violet", status: "LIVE",
      blurb: "Rotating epicycles — one per sine wave — summing into square, sawtooth, and triangle waves." },
    { slug: "forecasting",        topic: "TIME SERIES",   title: "Time-Series Forecasting", tone: "blue", status: "LIVE",
      blurb: "Level, trend, and seasonality: exponential smoothing fit on history and scored on a held-out future." },
    { slug: "embeddings",         topic: "EMBEDDINGS",    title: "Embedding Atlas",       tone: "violet", status: "LIVE",
      blurb: "Explore word embeddings in 2D — nearest neighbors and analogy arrows." },
    { slug: "vector-search",      topic: "RETRIEVAL · RAG", title: "Vector Search",       tone: "violet", status: "LIVE",
      blurb: "Click to query an embedding space and watch k-NN retrieval — the engine under semantic search and RAG." },
    { slug: "lr-schedule",        topic: "TRAINING",      title: "Learning-Rate Schedules", tone: "blue", status: "LIVE",
      blurb: "Warmup and decay, and the real noisy-SGD loss curve that converges or diverges depending on the schedule." },
    { slug: "lora",               topic: "FINE-TUNING",   title: "LoRA - Low-Rank Adaptation", tone: "violet", status: "LIVE",
      blurb: "Approximate a full weight update with two thin matrices via real truncated SVD — most of the change, a fraction of the params." },
    { slug: "scaling-laws",       topic: "SCALING",       title: "Neural Scaling Laws",   tone: "blue",   status: "LIVE",
      blurb: "The power-law loss frontier and the compute-optimal balance of model size and data (Chinchilla)." },
    { slug: "bayes",              topic: "FOUNDATIONS",   title: "Bayes Updater",         tone: "violet", status: "LIVE",
      blurb: "A Beta prior meets Bernoulli flips: drag your prior, watch the posterior tighten on the truth, learn conjugate updating by feel." },
    { slug: "optimizers",         topic: "OPTIMIZATION",  title: "Optimizer Shootout",    tone: "blue",   status: "LIVE",
      blurb: "SGD, Momentum, RMSProp, and Adam racing on the same non-convex loss surface — see how each one's mechanics shape its path." },
    { slug: "gan",                topic: "GENERATIVE",    title: "GAN 2-D",               tone: "violet", status: "LIVE",
      blurb: "A real generator and discriminator duel in your browser — fakes drift toward the target as the two networks fight to a draw." },
    { slug: "backprop",           topic: "FOUNDATIONS",   title: "Backprop Graph",        tone: "blue",   status: "LIVE",
      blurb: "Step through forward then backward on a tiny computation graph — every value, every gradient, by the chain rule." },
    { slug: "mcts",               topic: "RL",            title: "MCTS Tree Search",      tone: "violet", status: "LIVE",
      blurb: "Monte-Carlo Tree Search iteration by iteration — select, expand, rollout, backup — the search that powered AlphaGo." },
    { slug: "simulated-annealing", topic: "OPTIMIZATION", title: "Simulated Annealing",  tone: "violet", status: "LIVE",
      blurb: "Cool a tangled traveling-salesman tour into a clean one — Metropolis acceptance, geometric cooling, real 2-opt moves." },
    { slug: "regression",         topic: "CLASSICAL ML",  title: "Linear & Logistic Regression", tone: "blue", status: "LIVE",
      blurb: "Click to scatter points and watch the closed-form line of best fit, or train a sigmoid boundary with real gradient descent on BCE." },
    { slug: "rnn-gates",          topic: "RNN / NLP",     title: "LSTM Gates",            tone: "violet", status: "LIVE",
      blurb: "Feed a sequence into a tiny LSTM and watch the forget, input, and output gates open and close — a live look at gated memory." },
    { slug: "beam-search",        topic: "NLP / DECODING", title: "Beam Search Tree",     tone: "blue",   status: "LIVE",
      blurb: "Greedy vs beam vs sampling on a toy language model — see the search frontier branch, prune, and find the high-probability sentence." },
    { slug: "kv-cache",           topic: "TRANSFORMERS",  title: "KV Cache",              tone: "blue",   status: "LIVE",
      blurb: "Toggle the KV cache during autoregressive generation and watch per-step compute either stay flat or grow with prefix length." },
    { slug: "gnn",                topic: "GRAPH NETS",    title: "GNN Message Passing",   tone: "violet", status: "LIVE",
      blurb: "Watch node features smooth across a small graph as a real GCN runs message passing — and over-smooth when you stack too many layers." },
    { slug: "rope",               topic: "TRANSFORMERS",  title: "RoPE Explorer",         tone: "violet", status: "LIVE",
      blurb: "Rotary position embeddings, live — see why the attention score depends only on relative position, the trick behind every long-context LLM." },
    { slug: "dbscan",             topic: "UNSUPERVISED",  title: "DBSCAN",                tone: "blue",   status: "LIVE",
      blurb: "Density-based clustering — no k to pick, just two knobs that define what counts as dense. Watch moons, rings, and blobs cluster cleanly while noise stays gray." },
    { slug: "policy-gradient",    topic: "REINFORCEMENT LEARNING", title: "Policy Gradient — REINFORCE", tone: "violet", status: "LIVE",
      blurb: "A Gaussian policy finds a hidden target by sampling, scoring, and ascending log-prob times reward. The simplest RL — parent of PPO, GRPO, and RLHF." },
  ],
  // Display order + the "why it matters / foundations" line per category.
  categories: [
    { name: "Foundations", why: "The optimization, probability, evaluation, and search that sit under every model. Get these in your hands and the rest of ML stops looking like magic — it's gradient descent, generalization, the Gaussian, thresholds, and informed search, all the way down.", slugs: ["gradient-descent", "backprop", "overfitting", "roc", "clt", "bayes", "pathfinding", "simulated-annealing"] },
    { name: "Classical Machine Learning", why: "Interpretable algorithms that still win on tabular data — and that build the geometric intuition (distance, splits, clusters, margins, projections, mixtures) deep learning quietly assumes you already have.", slugs: ["regression", "kmeans", "decision-tree", "knn", "svm", "pca", "gmm", "dbscan"] },
    { name: "Neural Networks", why: "Where deep learning begins: how a network bends space to separate classes, why the choice of nonlinearity decides whether it trains, how convolution turns raw pixels into features, how optimizers actually move through a loss landscape, and how detectors turn those features into boxes.", slugs: ["neural-playground", "activations", "optimizers", "convolution", "nms", "rnn-gates", "gnn"] },
    { name: "Transformers & NLP", why: "The path from counting which word follows which to the scaled dot-product attention behind every modern LLM — tokenization, embeddings, position, attention itself, how you sample the output, and how retrieval grounds it.", slugs: ["tokenizer", "markov", "decoding", "beam-search", "embeddings", "vector-search", "attention", "multi-head-attention", "positional-encoding", "rope", "kv-cache"] },
    { name: "Training & Scaling", why: "How large models actually get trained, adapted, and scaled — the practical engineering behind the headline results: the learning-rate schedules that keep training stable, the low-rank tricks that make fine-tuning cheap, and the scaling laws that decide how to spend compute.", slugs: ["lr-schedule", "lora", "scaling-laws"] },
    { name: "Reinforcement Learning", why: "Learning from delayed reward instead of labels, the explore-vs-exploit tradeoff, the Bellman backups that plan optimal behavior, and the tree search that scales planning to large games — the foundations of agents that act, not just predict.", slugs: ["gridworld-rl", "value-iteration", "bandit", "mcts", "policy-gradient"] },
    { name: "Generative & Signal", why: "Creating new data rather than labeling it, plus the frequency-domain and sequence views that underpin audio, images, forecasting, and the diffusion models reshaping generative AI.", slugs: ["diffusion", "vae", "gan", "fourier", "forecasting"] },
  ],
  // The single concept each demo rests on — shown as a "foundation" tag.
  foundations: {
    "pathfinding": "informed search · f = g + h",
    "kmeans": "Lloyd's algorithm",
    "gradient-descent": "following the gradient",
    "overfitting": "the bias-variance tradeoff",
    "clt": "the √n law",
    "decision-tree": "recursive Gini splits",
    "knn": "distance-weighted voting",
    "svm": "max-margin + the kernel trick",
    "pca": "covariance eigenvectors",
    "gmm": "EM soft clustering",
    "roc": "threshold, ROC & PR",
    "value-iteration": "the Bellman optimality backup",
    "lr-schedule": "warmup & decay",
    "lora": "the low-rank update ΔW = BA",
    "scaling-laws": "power laws & compute-optimal",
    "nms": "IoU & greedy suppression",
    "vector-search": "k-NN retrieval (cosine vs L2)",
    "forecasting": "level, trend & seasonality",
    "multi-head-attention": "parallel attention heads",
    "vae": "reparameterization + KL",
    "decoding": "temperature, top-k, top-p sampling",
    "attention": "scaled dot-product attention",
    "positional-encoding": "sinusoidal & rotary position",
    "tokenizer": "byte-pair encoding",
    "markov": "the n-gram next-token model",
    "embeddings": "vector semantics",
    "gridworld-rl": "the Bellman update",
    "bandit": "explore vs exploit",
    "neural-playground": "backpropagation",
    "activations": "nonlinearity & gradients",
    "convolution": "the convolution kernel",
    "diffusion": "denoising (score / DDIM)",
    "fourier": "a sum of sines",
    "bayes": "conjugate prior × likelihood → posterior",
    "optimizers": "SGD · Momentum · RMSProp · Adam",
    "gan": "generator vs discriminator (BCE)",
    "backprop": "the chain rule on a computation graph",
    "mcts": "UCB tree search + rollouts",
    "simulated-annealing": "Metropolis acceptance + cooling",
    "regression": "least squares & cross-entropy",
    "rnn-gates": "gated recurrent memory",
    "beam-search": "log-probability tree search",
    "kv-cache": "reuse the prefix's K & V",
    "gnn": "neighborhood message passing",
    "rope": "rotate-by-position, score by relative",
    "dbscan": "density reachability + noise",
    "policy-gradient": "log-prob × reward",
  },
  findDemo(slug) { return this.demos.find(d => d.slug === slug); },
};
