// play-demos.js — single source of truth for the Play demos.
// Loaded before visualize-app.jsx (the Visualize hub). Status: LIVE | SOON.
// `lesson` is a path (relative to site root) to the matching /learn/ lesson, or null.

window.PLAY_DEMOS = {
  demos: [
    { slug: "pathfinding",        topic: "SEARCH",        title: "A* Pathfinding",        tone: "blue",   status: "LIVE",
      blurb: "Draw walls, drop a start and goal, and watch A* (or Dijkstra, BFS, Greedy) search for the shortest path." },
    { slug: "kmeans",             topic: "UNSUPERVISED",  title: "K-Means Clustering",    tone: "violet", status: "LIVE",
      blurb: "Scatter points, pick k, and step through assign-and-update until the centroids settle." },
    { slug: "gradient-descent",   topic: "OPTIMIZATION",  title: "Gradient Descent",      tone: "blue",   status: "LIVE",
      blurb: "Drop a ball on a loss surface and race SGD, Momentum, RMSProp, and Adam down to the minimum." },
    { slug: "overfitting",        topic: "ML THEORY",     title: "Overfitting Lab",       tone: "violet", status: "LIVE",
      blurb: "Fit a polynomial to noisy data and watch the bias-variance tradeoff and overfitting play out." },
    { slug: "cross-validation",   topic: "ML THEORY",     title: "Cross-Validation",      tone: "violet", status: "LIVE",
      blurb: "k-fold CV for model selection: a held-out fold rotates through the data while train error falls forever and CV error traces a U whose minimum is the right complexity." },
    { slug: "double-descent",     topic: "ML THEORY",     title: "Double Descent",        tone: "violet", status: "LIVE",
      blurb: "Test error dips, spikes at the interpolation threshold, then dips again as capacity grows. Sweep capacity to watch the fit go wild at P/N=1 — then see what noise and ridge do to the peak." },
    { slug: "bias-variance-decomp", topic: "ML THEORY",   title: "Bias-Variance Decomposition", tone: "violet", status: "LIVE",
      blurb: "Fit many models to resampled noisy data and watch error split into bias², variance, and irreducible noise. Sweep complexity to trace the U-curve; add data to see variance collapse." },
    { slug: "roc",                topic: "ML THEORY",     title: "ROC, PR & Thresholds",  tone: "blue",   status: "LIVE",
      blurb: "Slide a decision threshold across two score distributions and watch precision, recall, ROC, and PR trade off." },
    { slug: "decision-tree",      topic: "CLASSICAL ML",  title: "Decision Tree",         tone: "violet", status: "LIVE",
      blurb: "Watch a CART tree carve the plane into axis-aligned regions — and overfit as it deepens." },
    { slug: "bagging-boosting",   topic: "CLASSICAL ML",  title: "Bagging vs Boosting",   tone: "violet", status: "LIVE",
      blurb: "Bagging averages bootstrap-trained deep trees to cut variance; boosting stacks shallow trees on the residual to cut bias. Tune depth, count, and noise to see each shine and fail." },
    { slug: "gaussian-process",   topic: "CLASSICAL ML",  title: "Gaussian Processes",    tone: "violet", status: "LIVE",
      blurb: "A distribution over functions with closed-form uncertainty. Click to add points and watch the posterior mean bend and the ±2σ band pinch shut at data, flare open where you have none." },
    { slug: "knn",                topic: "CLASSICAL ML",  title: "k-Nearest Neighbors",   tone: "blue",   status: "LIVE",
      blurb: "Vote among the k closest points; tune k to trade a jagged boundary for a smooth one." },
    { slug: "naive-bayes",        topic: "CLASSICAL ML",  title: "Gaussian Naive Bayes",  tone: "violet", status: "LIVE",
      blurb: "Classify by Bayes' rule assuming features are independent within each class. Tilt the data so features correlate to see what the naive diagonal-covariance assumption costs versus full QDA." },
    { slug: "svm",                topic: "CLASSICAL ML",  title: "SVM - Margins & Kernels", tone: "blue", status: "LIVE",
      blurb: "Find the widest-margin boundary, see the support vectors that define it, then bend it with the kernel trick." },
    { slug: "pca",                topic: "UNSUPERVISED",  title: "Principal Component Analysis", tone: "violet", status: "LIVE",
      blurb: "Find the axes of greatest variance via a real covariance eigen-decomposition, then project onto them." },
    { slug: "tsne",               topic: "UNSUPERVISED",  title: "t-SNE",                 tone: "violet", status: "LIVE",
      blurb: "Watch real KL-divergence gradient descent pull high-dimensional clusters apart in 2D. Tune perplexity and learning rate to see t-SNE work — and the ways it famously misleads." },
    { slug: "isomap",             topic: "UNSUPERVISED",  title: "Isomap",                tone: "violet", status: "LIVE",
      blurb: "Nonlinear manifold learning: unroll a curved shape by geodesic (graph) distance, recovering an order that straight-line PCA folds and scrambles. Tune k to see the short-circuit failure." },
    { slug: "gmm",                topic: "UNSUPERVISED",  title: "Gaussian Mixtures & EM", tone: "violet", status: "LIVE",
      blurb: "Soft clustering by Expectation-Maximization — fit overlapping Gaussians and watch the log-likelihood climb." },
    { slug: "spectral-clustering", topic: "UNSUPERVISED", title: "Spectral Clustering",   tone: "violet", status: "LIVE",
      blurb: "Cluster by graph connectivity, not distance. The Laplacian's eigenvectors separate interlocking rings and moons that k-means cuts straight through." },
    { slug: "label-propagation",  topic: "SEMI-SUPERVISED", title: "Label Propagation",   tone: "violet", status: "LIVE",
      blurb: "Semi-supervised learning: one or two labels per class spread through a similarity graph to color hundreds of unlabeled points along the data's shape." },
    { slug: "clt",                topic: "PROBABILITY",   title: "Central Limit Theorem", tone: "violet", status: "LIVE",
      blurb: "Average samples from any distribution and watch the means pile up into a Gaussian." },
    { slug: "attention",          topic: "TRANSFORMERS",  title: "Attention Heatmap",     tone: "violet", status: "LIVE",
      blurb: "Type a sentence and see scaled dot-product attention decide which tokens look at which.", lesson: "learn/transformers/self-attention/" },
    { slug: "positional-encoding",topic: "TRANSFORMERS",  title: "Positional Encoding",   tone: "blue",   status: "LIVE",
      blurb: "Visualize how sinusoidal and rotary encodings inject order into a transformer." },
    { slug: "multi-head-attention", topic: "TRANSFORMERS", title: "Multi-Head Attention", tone: "violet", status: "LIVE",
      blurb: "Several real attention patterns in parallel — flip between heads and watch each one specialize on the same sentence." },
    { slug: "tokenizer",          topic: "NLP",           title: "Tokenizer Lab",         tone: "violet", status: "LIVE",
      blurb: "Watch BPE carve your text into subword tokens — trained live in the browser." },
    { slug: "markov",             topic: "NLP",           title: "Markov Text Generator", tone: "blue",   status: "LIVE",
      blurb: "The simplest language model — count which token follows which, then sample. The ancestor of every LLM." },
    { slug: "decoding",           topic: "NLP",           title: "Decoding Strategies",   tone: "violet", status: "LIVE",
      blurb: "Temperature, top-k, and top-p — how the same model becomes safe or wild depending on how you sample." },
    { slug: "gridworld-rl",       topic: "RL",            title: "Q-Learning Gridworld",  tone: "blue",   status: "LIVE",
      blurb: "Watch a Q-learning agent learn a policy in a gridworld, one episode at a time." },
    { slug: "bandit",             topic: "RL",            title: "Multi-Armed Bandit",    tone: "violet", status: "LIVE",
      blurb: "Explore vs exploit: pit ε-greedy, UCB, and Thompson sampling against each other." },
    { slug: "value-iteration",    topic: "RL",            title: "MDP Value Iteration",   tone: "blue",   status: "LIVE",
      blurb: "Solve a gridworld exactly — Bellman backups propagate value out from the goal, inducing the optimal policy." },
    { slug: "perceptron",         topic: "NEURAL NETS",   title: "The Perceptron",        tone: "violet", status: "LIVE",
      blurb: "The original learning algorithm: one corrective nudge per misclassified point swings a boundary into place. Separable data converges by theorem; raise the overlap and it never settles." },
    { slug: "neural-playground",  topic: "NEURAL NETS",   title: "Neural Playground",     tone: "blue",   status: "LIVE",
      blurb: "Train a tiny neural net live on 2D data and watch the decision boundary form." },
    { slug: "activations",        topic: "NEURAL NETS",   title: "Activation Functions",  tone: "blue",   status: "LIVE",
      blurb: "Plot sigmoid, tanh, ReLU, GELU and their gradients — and see where gradients vanish." },
    { slug: "batch-norm",         topic: "NEURAL NETS",   title: "Batch Normalization",   tone: "violet", status: "LIVE",
      blurb: "Watch a mini-batch's activations drift, explode, or saturate across a deep stack — then turn BatchNorm on and see every layer snap back to a healthy unit-variance spread." },
    { slug: "weight-init",        topic: "NEURAL NETS",   title: "Weight Initialization", tone: "violet", status: "LIVE",
      blurb: "The activation std stays near 1 or diverges exponentially with depth depending entirely on the init scale. Compare Naive vs Xavier vs He, and switch the activation to see which is right." },
    { slug: "contrastive-learning", topic: "NEURAL NETS", title: "Contrastive Learning",   tone: "violet", status: "LIVE",
      blurb: "Optimize the SimCLR / NT-Xent loss live: two views of each item pull together (alignment) while every other item is pushed away (uniformity) — all without labels." },
    { slug: "convolution",        topic: "COMPUTER VISION", title: "Convolution Lab",     tone: "violet", status: "LIVE",
      blurb: "Apply and design kernels on an image to see what each filter detects." },
    { slug: "edge-detection",     topic: "COMPUTER VISION", title: "Canny Edge Detection", tone: "violet", status: "LIVE",
      blurb: "Walk the five-stage Canny pipeline — blur, Sobel gradient, non-max suppression, double threshold, hysteresis — and watch edges emerge from raw pixels." },
    { slug: "hough-transform",    topic: "COMPUTER VISION", title: "Hough Transform",      tone: "violet", status: "LIVE",
      blurb: "Find straight lines by voting: every edge point votes for the lines through it, and real lines emerge as bright peaks in the (rho, theta) accumulator." },
    { slug: "harris-corners",     topic: "COMPUTER VISION", title: "Harris Corner Detector", tone: "violet", status: "LIVE",
      blurb: "Find corners from the eigenvalues of the local gradient structure tensor — where intensity changes in two directions at once. The keypoints behind tracking and SLAM." },
    { slug: "optical-flow",       topic: "COMPUTER VISION", title: "Optical Flow (Lucas-Kanade)", tone: "violet", status: "LIVE",
      blurb: "Estimate per-point motion between frames from brightness constancy — solve the 2x2 least-squares window system and watch the aperture problem and small-motion limit live." },
    { slug: "hog",                topic: "COMPUTER VISION", title: "Histogram of Oriented Gradients", tone: "violet", status: "LIVE",
      blurb: "Summarize an image by where its edges point — per-cell orientation histograms, block-normalized into the descriptor behind classic HOG+SVM object detection." },
    { slug: "nms",                topic: "COMPUTER VISION", title: "IoU & Non-Max Suppression", tone: "blue", status: "LIVE",
      blurb: "Turn a cloud of overlapping detection boxes into one clean box per object with IoU + greedy NMS." },
    { slug: "diffusion",          topic: "GENERATIVE",    title: "Diffusion Sampler",     tone: "blue",   status: "LIVE",
      blurb: "Step through a denoising chain turning pure noise into samples from a 2D distribution." },
    { slug: "vae",                topic: "GENERATIVE",    title: "Variational Autoencoder", tone: "violet", status: "LIVE",
      blurb: "Train a tiny VAE live — reparameterization, a KL-shaped latent space, and generation from pure noise." },
    { slug: "fourier",            topic: "SIGNAL",        title: "Fourier Series",        tone: "violet", status: "LIVE",
      blurb: "Rotating epicycles — one per sine wave — summing into square, sawtooth, and triangle waves." },
    { slug: "ica",                topic: "SIGNAL",        title: "ICA (Cocktail Party)",  tone: "violet", status: "LIVE",
      blurb: "Blind source separation: two signals blended into two microphones, unmixed by FastICA hunting the least-Gaussian directions. Switch to two Gaussian sources and watch it fail by design." },
    { slug: "forecasting",        topic: "TIME SERIES",   title: "Time-Series Forecasting", tone: "blue", status: "LIVE",
      blurb: "Level, trend, and seasonality: exponential smoothing fit on history and scored on a held-out future." },
    { slug: "embeddings",         topic: "EMBEDDINGS",    title: "Embedding Atlas",       tone: "violet", status: "LIVE",
      blurb: "Explore word embeddings in 2D — nearest neighbors and analogy arrows." },
    { slug: "word2vec",           topic: "EMBEDDINGS",    title: "word2vec (Skip-gram)",  tone: "violet", status: "LIVE",
      blurb: "Train real 2-D word vectors with skip-gram SGD and watch topics self-organize into clusters from co-occurrence alone. Raise the cross-topic mix to see the geometry blur." },
    { slug: "vector-search",      topic: "RETRIEVAL · RAG", title: "Vector Search",       tone: "violet", status: "LIVE",
      blurb: "Click to query an embedding space and watch k-NN retrieval — the engine under semantic search and RAG." },
    { slug: "lr-schedule",        topic: "TRAINING",      title: "Learning-Rate Schedules", tone: "blue", status: "LIVE",
      blurb: "Warmup and decay, and the real noisy-SGD loss curve that converges or diverges depending on the schedule." },
    { slug: "gradient-clipping",  topic: "TRAINING",      title: "Gradient Clipping",      tone: "violet", status: "LIVE",
      blurb: "A loss cliff makes the gradient explode; one unclipped step launches the parameters off the map. Norm clipping caps the gradient so descent stays bounded — race a clipped and unclipped walker." },
    { slug: "lora",               topic: "FINE-TUNING",   title: "LoRA - Low-Rank Adaptation", tone: "violet", status: "LIVE",
      blurb: "Approximate a full weight update with two thin matrices via real truncated SVD — most of the change, a fraction of the params." },
    { slug: "scaling-laws",       topic: "SCALING",       title: "Neural Scaling Laws",   tone: "blue",   status: "LIVE",
      blurb: "The power-law loss frontier and the compute-optimal balance of model size and data (Chinchilla)." },
    { slug: "bayes",              topic: "FOUNDATIONS",   title: "Bayes Updater",         tone: "violet", status: "LIVE",
      blurb: "A Beta prior meets Bernoulli flips: drag your prior, watch the posterior tighten on the truth, learn conjugate updating by feel." },
    { slug: "kalman-filter",      topic: "FOUNDATIONS",   title: "Kalman Filter",         tone: "violet", status: "LIVE",
      blurb: "A real 2-state Kalman filter tracks a maneuvering target from noisy measurements — tune process and sensor noise to move the gain and watch it denoise in real time." },
    { slug: "hmm-viterbi",        topic: "FOUNDATIONS",   title: "HMM & Viterbi",         tone: "violet", status: "LIVE",
      blurb: "Watch real Viterbi dynamic programming decode the most-likely hidden regime path from a noisy observation stream — tune persistence and emission noise to make it easy or near-impossible." },
    { slug: "mcmc",               topic: "FOUNDATIONS",   title: "MCMC (Metropolis)",     tone: "violet", status: "LIVE",
      blurb: "Sample a distribution you can only evaluate up to a constant via a random walk that visits it in proportion to its density. Tune the proposal step to feel the mixing-vs-acceptance tradeoff." },
    { slug: "importance-sampling", topic: "FOUNDATIONS",  title: "Importance Sampling",   tone: "violet", status: "LIVE",
      blurb: "Estimate a rare-event probability naive Monte Carlo never reaches by sampling a steered proposal and reweighting by p/q. Misplace the proposal and watch the effective sample size collapse." },
    { slug: "reservoir-sampling", topic: "FOUNDATIONS",   title: "Reservoir Sampling",    tone: "violet", status: "LIVE",
      blurb: "Keep a uniform random sample of k items from an unbounded stream in one pass, O(k) memory. A Monte-Carlo histogram proves every position survives with equal probability k/N." },
    { slug: "count-min-sketch",   topic: "FOUNDATIONS",   title: "Count-Min Sketch",      tone: "violet", status: "LIVE",
      blurb: "Estimate item frequencies in a massive stream with a tiny d x w table of hashed counters. Query takes the min, so collisions only ever overestimate — heavy hitters are nailed in sublinear memory." },
    { slug: "bloom-filter",       topic: "FOUNDATIONS",   title: "Bloom Filter",          tone: "violet", status: "LIVE",
      blurb: "Probabilistic set membership in a tiny bit array: never a false negative, only tunable false positives. Watch the FP rate climb as the array fills and find the optimal hash count." },
    { slug: "optimizers",         topic: "OPTIMIZATION",  title: "Optimizer Shootout",    tone: "blue",   status: "LIVE",
      blurb: "SGD, Momentum, RMSProp, and Adam racing on the same non-convex loss surface — see how each one's mechanics shape its path." },
    { slug: "gan",                topic: "GENERATIVE",    title: "GAN 2-D",               tone: "violet", status: "LIVE",
      blurb: "A real generator and discriminator duel in your browser — fakes drift toward the target as the two networks fight to a draw." },
    { slug: "backprop",           topic: "FOUNDATIONS",   title: "Backprop Graph",        tone: "blue",   status: "LIVE",
      blurb: "Step through forward then backward on a tiny computation graph — every value, every gradient, by the chain rule." },
    { slug: "mcts",               topic: "RL",            title: "MCTS Tree Search",      tone: "violet", status: "LIVE",
      blurb: "Monte-Carlo Tree Search iteration by iteration — select, expand, rollout, backup — the search that powered AlphaGo." },
    { slug: "simulated-annealing", topic: "OPTIMIZATION", title: "Simulated Annealing",  tone: "violet", status: "LIVE",
      blurb: "Cool a tangled traveling-salesman tour into a clean one — Metropolis acceptance, geometric cooling, real 2-opt moves." },
    { slug: "regression",         topic: "CLASSICAL ML",  title: "Linear & Logistic Regression", tone: "blue", status: "LIVE",
      blurb: "Click to scatter points and watch the closed-form line of best fit, or train a sigmoid boundary with real gradient descent on BCE." },
    { slug: "rnn-gates",          topic: "RNN / NLP",     title: "LSTM Gates",            tone: "violet", status: "LIVE",
      blurb: "Feed a sequence into a tiny LSTM and watch the forget, input, and output gates open and close — a live look at gated memory." },
    { slug: "beam-search",        topic: "NLP / DECODING", title: "Beam Search Tree",     tone: "blue",   status: "LIVE",
      blurb: "Greedy vs beam vs sampling on a toy language model — see the search frontier branch, prune, and find the high-probability sentence." },
    { slug: "kv-cache",           topic: "TRANSFORMERS",  title: "KV Cache",              tone: "blue",   status: "LIVE",
      blurb: "Toggle the KV cache during autoregressive generation and watch per-step compute either stay flat or grow with prefix length." },
    { slug: "attention-rollout",  topic: "TRANSFORMERS",  title: "Attention Rollout",     tone: "violet", status: "LIVE",
      blurb: "One attention layer shows one hop; compose them to trace a token's attribution back to the input. Watch rollout spread credit beyond the last layer." },
    { slug: "gnn",                topic: "GRAPH NETS",    title: "GNN Message Passing",   tone: "violet", status: "LIVE",
      blurb: "Watch node features smooth across a small graph as a real GCN runs message passing — and over-smooth when you stack too many layers." },
    { slug: "rope",               topic: "TRANSFORMERS",  title: "RoPE Explorer",         tone: "violet", status: "LIVE",
      blurb: "Rotary position embeddings, live — see why the attention score depends only on relative position, the trick behind every long-context LLM." },
    { slug: "dbscan",             topic: "UNSUPERVISED",  title: "DBSCAN",                tone: "blue",   status: "LIVE",
      blurb: "Density-based clustering — no k to pick, just two knobs that define what counts as dense. Watch moons, rings, and blobs cluster cleanly while noise stays gray." },
    { slug: "hierarchical-clustering", topic: "UNSUPERVISED", title: "Hierarchical Clustering", tone: "violet", status: "LIVE",
      blurb: "Merge the closest clusters into a tree, then slide a cut across the dendrogram to read off any number of clusters from one structure. Switch linkage for compact, chained, or Ward clusters." },
    { slug: "kernel-density",     topic: "UNSUPERVISED",  title: "Kernel Density Estimation", tone: "violet", status: "LIVE",
      blurb: "Drop a kernel on every point and sum them into a smooth, assumption-free density. Drag the bandwidth to watch the bias/variance tradeoff: spiky at small h, oversmoothed at large h." },
    { slug: "policy-gradient",    topic: "REINFORCEMENT LEARNING", title: "Policy Gradient — REINFORCE", tone: "violet", status: "LIVE",
      blurb: "A Gaussian policy finds a hidden target by sampling, scoring, and ascending log-prob times reward. The simplest RL — parent of PPO, GRPO, and RLHF." },
    { slug: "actor-critic",       topic: "REINFORCEMENT LEARNING", title: "Actor-Critic", tone: "violet", status: "LIVE",
      blurb: "A critic learns each state's value while an actor learns the policy — one shared TD error trains both. The learned baseline behind A2C, PPO, and RLHF." },
    { slug: "dqn",                topic: "REINFORCEMENT LEARNING", title: "Deep Q-Network (DQN)", tone: "violet", status: "LIVE",
      blurb: "A neural net learns Q(s, a) on a continuous state. Toggle experience replay and the target network to see why deep RL needs both to stay stable." },
    { slug: "reward-model",       topic: "REINFORCEMENT LEARNING", title: "Reward Model (RLHF)", tone: "violet", status: "LIVE",
      blurb: "Learn a scalar reward from pairwise human preferences with Bradley-Terry — the signal PPO maximizes in RLHF. Watch the learned field reconstruct the hidden one." },
    { slug: "dpo",                topic: "REINFORCEMENT LEARNING", title: "DPO vs RLHF", tone: "violet", status: "LIVE",
      blurb: "Align a policy from the same human preferences two ways — RLHF's reward model + RL loop vs DPO's direct update — and watch them converge to the same policy." },
    { slug: "rag-chunking",       topic: "RAG / RETRIEVAL", title: "RAG Chunking", tone: "violet", status: "LIVE",
      blurb: "Chunk size, overlap, and strategy decide whether the answer survives retrieval. Real TF-IDF cosine over the chunks — watch the retrieval verdict flip." },
    { slug: "self-consistency",   topic: "AGENTS / LLM OPS", title: "Self-Consistency", tone: "violet", status: "LIVE",
      blurb: "Sample many chains of thought and majority-vote the answer. See why it lifts accuracy — and why correlated errors quietly defeat it." },
    { slug: "constrained-decoding", topic: "AGENTS / LLM OPS", title: "Constrained Decoding", tone: "violet", status: "LIVE",
      blurb: "Mask the grammar-invalid tokens at every step and structured output becomes guaranteed, not hoped-for. Raw vs constrained JSON generation, side by side." },
    { slug: "guardrails",         topic: "AGENTS / LLM OPS", title: "Guardrails", tone: "violet", status: "LIVE",
      blurb: "The input/output safety pipeline around an LLM — PII redaction, injection and topic guards, output filtering. Toggle a guard off and watch a threat get through." },
    { slug: "lost-in-the-middle", topic: "AGENTS / LLM OPS", title: "Lost in the Middle", tone: "violet", status: "LIVE",
      blurb: "Models use the start and end of a long context far better than the middle. Slide the answer's position along the U-curve — and rerank it to the front to fix it." },
    { slug: "hyde",               topic: "AGENTS / LLM OPS", title: "HyDE — Hypothetical Embeddings", tone: "violet", status: "LIVE",
      blurb: "Questions embed away from their answers. Draft a hypothetical answer, embed that instead, and retrieval lands on the right documents." },
    { slug: "reflection",         topic: "AGENTS / LLM OPS", title: "Self-Correction (Reflection)", tone: "violet", status: "LIVE",
      blurb: "Draft, critique, revise, repeat. Watch quality climb to the bar — then weaken the critic and see reflection stall, ship garbage, or burn the budget." },
    { slug: "react-agent",        topic: "AGENTS / LLM OPS", title: "ReAct — Reason + Act", tone: "violet", status: "LIVE",
      blurb: "The tool-using agent loop: Thought → Action → Observation, repeat. Watch a worked trace — then drop the reliability and see errors compound." },
    { slug: "multi-query",        topic: "AGENTS / LLM OPS", title: "Multi-Query & RAG-Fusion", tone: "violet", status: "LIVE",
      blurb: "One phrasing misses docs another catches. Retrieve with several query variants and fuse the ranked lists by reciprocal rank — recall beats any single query." },
    { slug: "rag-reranker",       topic: "AGENTS / LLM OPS", title: "RAG Reranker", tone: "violet", status: "LIVE",
      blurb: "Cheap lexical retrieval buries semantically-relevant docs; a cross-encoder reranker re-scores the shortlist and floats them to the top. Watch nDCG jump." },
    { slug: "agent-router",       topic: "AGENTS / LLM OPS", title: "Agent Tool Router", tone: "violet", status: "LIVE",
      blurb: "Which tool handles this query? Score it against each tool, route to the top above a confidence threshold, and fall back to the model when nothing fits." },
    { slug: "calibration",        topic: "TRUSTWORTHY ML", title: "Model Calibration", tone: "blue", status: "LIVE",
      blurb: "A '90% confident' model should be right 90% of the time. See overconfidence on a reliability diagram, measure ECE, and fix it with one temperature knob." },
    { slug: "shap",               topic: "TRUSTWORTHY ML", title: "Feature Attribution (SHAP)", tone: "blue", status: "LIVE",
      blurb: "Why did the model decide that? Exact Shapley values credit each feature's contribution — including the interaction — as a waterfall from base to prediction." },
    { slug: "conformal",          topic: "TRUSTWORTHY ML", title: "Conformal Prediction", tone: "blue", status: "LIVE",
      blurb: "Output a label set guaranteed to contain the truth (1−α) of the time — for any model. Coverage holds even as the model worsens; only set size suffers." },
    { slug: "conformal-regression", topic: "TRUSTWORTHY ML", title: "Conformal Regression", tone: "blue", status: "LIVE",
      blurb: "Turn a point regressor into a prediction interval with a coverage guarantee. Coverage holds even when the mean is underfit; an adaptive score lets the band breathe with the noise." },
    { slug: "active-learning",    topic: "TRUSTWORTHY ML", title: "Active Learning", tone: "blue", status: "LIVE",
      blurb: "Labels are expensive — let the model pick what to label. Uncertainty sampling races random labeling and hits high accuracy with far fewer labels." },
    { slug: "coreset",            topic: "DATA-CENTRIC ML", title: "Coresets", tone: "violet", status: "LIVE",
      blurb: "Keep a tiny weighted subset of the data that reproduces the full k-means clustering. Importance sampling tracks the answer with a fraction of the points where uniform falls apart." },
    { slug: "dataset-distillation", topic: "DATA-CENTRIC ML", title: "Dataset Distillation", tone: "violet", status: "LIVE",
      blurb: "Learn a handful of synthetic training points whose model reproduces the full dataset's boundary. Watch them migrate into the most informative positions as the distillation loss falls." },
    { slug: "fairness",           topic: "TRUSTWORTHY ML", title: "Fairness & Group Metrics", tone: "blue", status: "LIVE",
      blurb: "Equal qualification, biased scores. See how one threshold creates unequal outcomes — and why you can't satisfy every fairness metric at once." },
    { slug: "label-noise",        topic: "TRUSTWORTHY ML", title: "Label Noise", tone: "blue", status: "LIVE",
      blurb: "Flip some training labels and watch the boundary warp around them. Train longer and the model memorizes the noise — true accuracy falls as train accuracy climbs." },
    { slug: "mc-dropout",         topic: "TRUSTWORTHY ML", title: "MC Dropout", tone: "blue", status: "LIVE",
      blurb: "Keep dropout on at inference and sample many times — the spread is the model's uncertainty, and it grows where the data runs out." },
    { slug: "saliency",           topic: "TRUSTWORTHY ML", title: "Saliency Maps", tone: "blue", status: "LIVE",
      blurb: "Gradient of the output w.r.t. each input pixel — a per-example map of what the model is looking at. Paint the grid and watch the explanation move." },
    { slug: "drift-detection",    topic: "MLOPS / MONITORING", title: "Data Drift Detection", tone: "blue", status: "LIVE",
      blurb: "Deployed models rot as the world shifts. Watch the live distribution peel away from the reference and a PSI monitor trip the retrain alarm." },
    { slug: "n-queens",           topic: "SEARCH / CSP", title: "N-Queens (Backtracking)", tone: "blue", status: "LIVE",
      blurb: "Place N non-attacking queens by depth-first backtracking. Toggle forward checking and watch constraint propagation prune the search tree." },
    { slug: "graph-coloring",     topic: "SEARCH / CSP", title: "Graph Coloring (AC-3)", tone: "blue", status: "LIVE",
      blurb: "Color the map so neighbors differ. Backtracking with arc-consistency propagation — watch domains shrink, and compare backtracks with AC-3 on vs off." },
    { slug: "sudoku",             topic: "SEARCH / CSP", title: "Sudoku Solver", tone: "blue", status: "LIVE",
      blurb: "Backtracking + constraint propagation on a 9×9 grid. Toggle propagation off and watch the guess and backtrack counts explode for the same puzzle." },
    { slug: "quantization",       topic: "EFFICIENCY", title: "Quantization", tone: "violet", status: "LIVE",
      blurb: "Round fp32 weights to b-bit integers — smaller and faster, but coarser. Watch weights snap to the grid, and how outliers wreck it until you clip them." },
    { slug: "pruning",            topic: "EFFICIENCY", title: "Pruning & Sparsity", tone: "violet", status: "LIVE",
      blurb: "Zero the smallest weights and accuracy barely budges — until it falls off a cliff. The over-parameterization that makes networks compressible." },
    { slug: "distillation",       topic: "EFFICIENCY", title: "Knowledge Distillation", tone: "violet", status: "LIVE",
      blurb: "Train a small student to match a teacher's soft labels, not just its answers. Turn up temperature and soft-weight to transfer the teacher's dark knowledge." },
    { slug: "moe",                topic: "EFFICIENCY", title: "Mixture of Experts (MoE)", tone: "violet", status: "LIVE",
      blurb: "Route each token to a few of many experts — scale parameters, not per-token compute. Watch specialization emerge and fight the load-imbalance failure." },
    { slug: "mixed-precision",    topic: "EFFICIENCY", title: "Mixed Precision", tone: "violet", status: "LIVE",
      blurb: "fp16's narrow range makes small gradients vanish and big ones blow up. Slide loss scaling to rescue them — or switch to bf16 and trade precision for range." },
    { slug: "speculative-decoding", topic: "EFFICIENCY", title: "Speculative Decoding", tone: "violet", status: "LIVE",
      blurb: "A small draft model guesses ahead; the big model verifies in one pass. Several tokens per expensive step — a lossless speedup set by draft agreement and lookahead." },
    { slug: "paged-attention",    topic: "EFFICIENCY", title: "PagedAttention", tone: "violet", status: "LIVE",
      blurb: "Contiguous KV-cache reservations waste memory on every half-finished sequence; paging packs fixed blocks on demand and fits far more streams in the same GPU." },
    { slug: "simpsons-paradox",   topic: "CAUSAL INFERENCE", title: "Simpson's Paradox", tone: "blue", status: "LIVE",
      blurb: "Every subgroup trends up, the pooled data trends down. See how a confounder reverses the conclusion — and why you have to condition on it." },
    { slug: "do-intervention",    topic: "CAUSAL INFERENCE", title: "do() & Backdoor Adjustment", tone: "blue", status: "LIVE",
      blurb: "Observing X is not setting X. A confounder biases the naive estimate; cut its arrow with do(X), or adjust for it, to recover the true causal effect." },
    { slug: "instrumental-variables", topic: "CAUSAL INFERENCE", title: "Instrumental Variables", tone: "blue", status: "LIVE",
      blurb: "Can't measure the confounder? Find an instrument that moves the treatment but not the outcome, and 2SLS reads the true effect off it — until you break relevance or exclusion." },
    { slug: "knapsack",           topic: "DYNAMIC PROGRAMMING", title: "Knapsack (DP)", tone: "blue", status: "LIVE",
      blurb: "Pack the most value into a weight budget. Watch the DP table fill from its sub-answers, then backtrack to recover which items to take." },
    { slug: "branch-and-bound",   topic: "SEARCH", title: "Branch & Bound", tone: "blue", status: "LIVE",
      blurb: "Solve 0/1 knapsack exactly without opening every branch. An optimistic LP bound prunes whole subtrees that can't beat the best solution so far — toggle bounding off to watch it collapse into brute force." },
    { slug: "bfs-dfs-astar",      topic: "SEARCH / CSP", title: "BFS vs DFS vs A*", tone: "blue", status: "LIVE",
      blurb: "Three searches, one maze. Watch uninformed rings and dives versus A*'s heuristic beeline — and compare nodes expanded and path optimality." },
    { slug: "edit-distance",      topic: "DYNAMIC PROGRAMMING", title: "Edit Distance", tone: "blue", status: "LIVE",
      blurb: "The fewest insert/delete/substitute edits between two strings. Watch the DP table fill from its neighbors, then backtrack the character alignment." },
  ],
  // Display order + the "why it matters / foundations" line per category.
  categories: [
    { name: "Foundations", why: "The optimization, probability, evaluation, and search that sit under every model. Get these in your hands and the rest of ML stops looking like magic — it's gradient descent, generalization, the Gaussian, thresholds, and informed search, all the way down.", slugs: ["gradient-descent", "backprop", "overfitting", "double-descent", "bias-variance-decomp", "roc", "clt", "bayes", "mcmc", "importance-sampling", "reservoir-sampling", "count-min-sketch", "bloom-filter", "cross-validation", "kalman-filter", "hmm-viterbi", "simpsons-paradox", "do-intervention", "instrumental-variables", "pathfinding", "simulated-annealing"] },
    { name: "Classical Machine Learning", why: "Interpretable algorithms that still win on tabular data — and that build the geometric intuition (distance, splits, clusters, margins, projections, mixtures) deep learning quietly assumes you already have.", slugs: ["regression", "kmeans", "decision-tree", "bagging-boosting", "knn", "svm", "naive-bayes", "gaussian-process", "pca", "tsne", "isomap", "gmm", "dbscan", "hierarchical-clustering", "spectral-clustering", "label-propagation", "kernel-density"] },
    { name: "Neural Networks", why: "Where deep learning begins: how a network bends space to separate classes, why the choice of nonlinearity decides whether it trains, how convolution turns raw pixels into features, how optimizers actually move through a loss landscape, and how detectors turn those features into boxes.", slugs: ["perceptron", "neural-playground", "activations", "batch-norm", "weight-init", "contrastive-learning", "optimizers", "convolution", "edge-detection", "hough-transform", "harris-corners", "optical-flow", "hog", "nms", "rnn-gates", "gnn"] },
    { name: "Transformers & NLP", why: "The path from counting which word follows which to the scaled dot-product attention behind every modern LLM — tokenization, embeddings, position, attention itself, how you sample the output, and how retrieval grounds it.", slugs: ["tokenizer", "markov", "decoding", "beam-search", "embeddings", "word2vec", "vector-search", "attention", "multi-head-attention", "attention-rollout", "positional-encoding", "rope", "kv-cache"] },
    { name: "Training & Scaling", why: "How large models actually get trained, adapted, and scaled — the practical engineering behind the headline results: the learning-rate schedules that keep training stable, the low-rank tricks that make fine-tuning cheap, and the scaling laws that decide how to spend compute.", slugs: ["lr-schedule", "gradient-clipping", "lora", "scaling-laws"] },
    { name: "Reinforcement Learning", why: "Learning from delayed reward instead of labels, the explore-vs-exploit tradeoff, the Bellman backups that plan optimal behavior, and the tree search that scales planning to large games — the foundations of agents that act, not just predict.", slugs: ["gridworld-rl", "value-iteration", "bandit", "mcts", "policy-gradient", "actor-critic", "dqn", "reward-model", "dpo"] },
    { name: "Generative & Signal", why: "Creating new data rather than labeling it, plus the frequency-domain and sequence views that underpin audio, images, forecasting, and the diffusion models reshaping generative AI.", slugs: ["diffusion", "vae", "gan", "fourier", "ica", "forecasting"] },
    { name: "Agents & LLM Systems", why: "What it takes to turn a raw model into a reliable system: grounding answers in retrieved context, the reliability patterns — sampling-and-voting, verification — that make stochastic models dependable, and the decoding constraints that guarantee structured output. The engineering layer on top of the weights.", slugs: ["rag-chunking", "hyde", "multi-query", "rag-reranker", "lost-in-the-middle", "react-agent", "agent-router", "self-consistency", "reflection", "constrained-decoding", "guardrails"] },
    { name: "Trustworthy & Explainable ML", why: "Whether you can actually trust what a model outputs: are its confidence scores honest, and can you explain why it decided what it did? The layer that turns a black-box predictor into something you'd deploy where the stakes are real.", slugs: ["calibration", "shap", "saliency", "conformal", "conformal-regression", "mc-dropout", "active-learning", "coreset", "dataset-distillation", "label-noise", "drift-detection", "fairness"] },
    { name: "Search & Constraint Solving", why: "The classic computer-science core under so much of AI: systematically searching enormous discrete spaces, and using constraints to prune them. Complete methods that guarantee a solution if one exists — the counterpoint to the gradient-based learning everywhere else here.", slugs: ["bfs-dfs-astar", "n-queens", "graph-coloring", "sudoku", "knapsack", "branch-and-bound", "edit-distance"] },
    { name: "Efficiency & Systems", why: "Trained models are huge; this is how you make them cheap enough to actually ship — shrinking the bits, the weights, and the compute without giving back the accuracy. The engineering that turns a research checkpoint into something that runs on your hardware.", slugs: ["quantization", "pruning", "distillation", "moe", "mixed-precision", "speculative-decoding", "paged-attention"] },
  ],
  // The single concept each demo rests on — shown as a "foundation" tag.
  foundations: {
    "pathfinding": "informed search · f = g + h",
    "kmeans": "Lloyd's algorithm",
    "gradient-descent": "following the gradient",
    "overfitting": "the bias-variance tradeoff",
    "cross-validation": "held-out folds pick the model",
    "double-descent": "error peaks then falls past interpolation",
    "bias-variance-decomp": "split error: bias² + variance + noise",
    "clt": "the √n law",
    "decision-tree": "recursive Gini splits",
    "bagging-boosting": "average to cut variance, stack to cut bias",
    "gaussian-process": "distribution over functions + uncertainty",
    "tsne": "preserve neighbors from high-D to 2D",
    "isomap": "unroll by geodesic distance",
    "spectral-clustering": "cluster the graph Laplacian's eigenvectors",
    "label-propagation": "a few labels spread through the graph",
    "knn": "distance-weighted voting",
    "naive-bayes": "Bayes rule + feature independence",
    "svm": "max-margin + the kernel trick",
    "pca": "covariance eigenvectors",
    "gmm": "EM soft clustering",
    "roc": "threshold, ROC & PR",
    "value-iteration": "the Bellman optimality backup",
    "lr-schedule": "warmup & decay",
    "gradient-clipping": "cap the gradient norm at a cliff",
    "lora": "the low-rank update ΔW = BA",
    "scaling-laws": "power laws & compute-optimal",
    "nms": "IoU & greedy suppression",
    "vector-search": "k-NN retrieval (cosine vs L2)",
    "forecasting": "level, trend & seasonality",
    "multi-head-attention": "parallel attention heads",
    "vae": "reparameterization + KL",
    "decoding": "temperature, top-k, top-p sampling",
    "attention": "scaled dot-product attention",
    "positional-encoding": "sinusoidal & rotary position",
    "tokenizer": "byte-pair encoding",
    "markov": "the n-gram next-token model",
    "embeddings": "vector semantics",
    "word2vec": "skip-gram learns vectors from context",
    "gridworld-rl": "the Bellman update",
    "bandit": "explore vs exploit",
    "perceptron": "mistake-driven linear learning",
    "neural-playground": "backpropagation",
    "activations": "nonlinearity & gradients",
    "batch-norm": "re-standardize activations per layer",
    "weight-init": "scale weights to preserve variance",
    "contrastive-learning": "pull positives, push negatives",
    "convolution": "the convolution kernel",
    "edge-detection": "Canny: gradient, thin, threshold, link",
    "hough-transform": "edge points vote; lines = peaks",
    "harris-corners": "structure tensor: both eigenvalues large",
    "optical-flow": "brightness constancy + LK least squares",
    "hog": "per-cell orientation histograms",
    "diffusion": "denoising (score / DDIM)",
    "fourier": "a sum of sines",
    "ica": "unmix by maximizing non-Gaussianity",
    "bayes": "conjugate prior × likelihood → posterior",
    "mcmc": "sample by random walk; proportional to density",
    "importance-sampling": "reweight a proposal by p/q",
    "reservoir-sampling": "uniform sample of a stream in one pass",
    "count-min-sketch": "hashed counters; query the min",
    "bloom-filter": "k hashes; no false negatives",
    "kalman-filter": "predict then update; optimal denoising",
    "hmm-viterbi": "DP for the best hidden path",
    "optimizers": "SGD · Momentum · RMSProp · Adam",
    "gan": "generator vs discriminator (BCE)",
    "backprop": "the chain rule on a computation graph",
    "mcts": "UCB tree search + rollouts",
    "simulated-annealing": "Metropolis acceptance + cooling",
    "regression": "least squares & cross-entropy",
    "rnn-gates": "gated recurrent memory",
    "beam-search": "log-probability tree search",
    "kv-cache": "reuse the prefix's K & V",
    "gnn": "neighborhood message passing",
    "rope": "rotate-by-position, score by relative",
    "dbscan": "density reachability + noise",
    "hierarchical-clustering": "merge into a dendrogram, cut for k",
    "kernel-density": "sum of kernels; bandwidth = bias/variance",
    "policy-gradient": "log-prob × reward",
    "actor-critic": "TD error trains actor + critic",
    "dqn": "replay + target net stabilize Q",
    "reward-model": "Bradley-Terry from preferences",
    "dpo": "implicit reward = β·log(π/π_ref)",
    "rag-chunking": "chunk → retrieve → ground",
    "self-consistency": "sample N → majority vote",
    "constrained-decoding": "mask invalid tokens per step",
    "guardrails": "layered input/output checks",
    "lost-in-the-middle": "U-shaped context position bias",
    "hyde": "embed a drafted answer, not the query",
    "reflection": "draft → critique → revise loop",
    "react-agent": "thought → action → observation",
    "multi-query": "query variants + reciprocal-rank fusion",
    "rag-reranker": "cross-encoder reorders the shortlist",
    "agent-router": "score tools, route or fall back",
    "attention-rollout": "compose attention across layers",
    "calibration": "reliability diagram + temperature",
    "shap": "Shapley values over feature coalitions",
    "conformal": "calibrated sets with coverage guarantee",
    "conformal-regression": "prediction intervals with coverage guarantee",
    "active-learning": "label the most uncertain points",
    "coreset": "tiny weighted subset preserves the model",
    "dataset-distillation": "learn synthetic points that teach",
    "fairness": "group metrics & the threshold tradeoff",
    "label-noise": "memorizing flipped labels",
    "mc-dropout": "sample dropout masks for uncertainty",
    "saliency": "input-gradient attribution map",
    "drift-detection": "PSI alarm on covariate shift",
    "n-queens": "backtracking + forward checking",
    "graph-coloring": "backtracking + AC-3 propagation",
    "sudoku": "backtracking + naked singles",
    "quantization": "round to a b-bit grid",
    "pruning": "zero small weights, keep accuracy",
    "distillation": "match the teacher's soft labels",
    "moe": "route tokens to top-k experts",
    "mixed-precision": "loss scaling into fp16's range",
    "speculative-decoding": "draft proposes, target verifies",
    "paged-attention": "KV cache in on-demand blocks",
    "simpsons-paradox": "confounding reverses the trend",
    "do-intervention": "observe vs do(); backdoor adjust",
    "instrumental-variables": "2SLS via an instrument; recover β",
    "knapsack": "fill the table, backtrack the choice",
    "branch-and-bound": "prune subtrees with an optimistic bound",
    "bfs-dfs-astar": "uninformed vs informed search",
    "edit-distance": "string alignment DP",
  },
  findDemo(slug) { return this.demos.find(d => d.slug === slug); },
};
