// play-demos.js — single source of truth for the Play demos.
// Loaded before visualize-app.jsx (the Visualize hub). Status: LIVE | SOON.
// `lesson` is a path (relative to site root) to the matching /learn/ lesson, or null.

window.PLAY_DEMOS = {
  demos: [
    { slug: "pathfinding",        topic: "SEARCH / CSP",        title: "A* Pathfinding",        tone: "blue",   status: "LIVE",
      blurb: "Draw walls, drop a start and goal, and watch A* (or Dijkstra, BFS, Greedy) search for the shortest path.", lesson: "learn/interview-capstone/search-astar/" },
    { slug: "kmeans",             topic: "UNSUPERVISED",  title: "K-Means Clustering",    tone: "violet", status: "LIVE",
      blurb: "Scatter points, pick k, and step through assign-and-update until the centroids settle.", lesson: "learn/unsupervised-learning/kmeans/" },
    { slug: "gradient-descent",   topic: "OPTIMIZATION",  title: "Gradient Descent",      tone: "blue",   status: "LIVE",
      blurb: "Drop a ball on a loss surface and race SGD, Momentum, RMSProp, and Adam down to the minimum." },
    { slug: "newton-vs-gradient", topic: "OPTIMIZATION",  title: "Newton vs Gradient Descent", tone: "blue", status: "LIVE",
      blurb: "Race a first-order step against Newton's second-order step that uses curvature to jump to the minimum - one step on a quadratic, trapped on a saddle.", lesson: "learn/ml-theory/newtons-method/" },
    { slug: "coordinate-descent", topic: "OPTIMIZATION",  title: "Coordinate Descent",      tone: "violet", status: "LIVE",
      blurb: "Minimize one variable at a time with exact line searches - fast when the axes align, a long staircase when the coordinates are correlated.", lesson: "learn/ml-theory/convex-optimization/" },
    { slug: "ista",               topic: "OPTIMIZATION",  title: "ISTA / Proximal Gradient (L1)", tone: "violet", status: "LIVE",
      blurb: "Recover a sparse model with soft-thresholding - the proximal step that snaps small coefficients to exactly zero, with ISTA vs FISTA acceleration.", lesson: "learn/ml-theory/convex-optimization/" },
    { slug: "l-bfgs",             topic: "OPTIMIZATION",  title: "L-BFGS (Quasi-Newton)",  tone: "violet", status: "LIVE",
      blurb: "Approximate curvature from a short memory of past gradients via the two-loop recursion - Newton-like convergence with no Hessian.", lesson: "learn/ml-theory/convex-optimization/" },
    { slug: "bayesian-linear-regression", topic: "BAYESIAN", title: "Bayesian Linear Regression", tone: "blue", status: "LIVE",
      blurb: "Fit a distribution over functions, not one line - click to add data and watch the closed-form Gaussian posterior tighten near data and fan out in the gaps.", lesson: "learn/supervised-learning/bayesian-linear-regression/" },
    { slug: "variational-inference", topic: "BAYESIAN", title: "Variational Inference (ELBO)", tone: "blue", status: "LIVE",
      blurb: "Approximate a posterior by maximizing the ELBO - watch mean-field VI underestimate variance and chase a single mode, the classic reverse-KL pathologies.", lesson: "learn/generative/variational-inference/" },
    { slug: "thompson-vs-ucb",      topic: "BAYESIAN",     title: "Thompson Sampling vs UCB", tone: "blue", status: "LIVE",
      blurb: "Two principled bandit strategies head to head - a Bayesian Beta posterior vs frequentist optimism - with the per-arm beliefs that drive each on screen." },
    { slug: "conjugate-updating",   topic: "BAYESIAN",     title: "Conjugate Prior Updating", tone: "violet", status: "LIVE",
      blurb: "Watch a prior become a posterior one observation at a time across Beta-Bernoulli, Normal-Normal, and Gamma-Poisson - the closed-form heart of Bayesian inference.", lesson: "learn/unsupervised-learning/bayesian-inference/" },
    { slug: "bayesian-optimization", topic: "BAYESIAN",    title: "Bayesian Optimization", tone: "violet", status: "LIVE",
      blurb: "Find the max of an expensive function in a handful of evals - a GP surrogate plus an acquisition function (EI / UCB / PI) that picks where to sample next.", lesson: "learn/training-systems/bayesian-optimization/" },
    { slug: "sparse-autoencoder",   topic: "INTERPRETABILITY", title: "Sparse Autoencoders (Superposition)", tone: "violet", status: "LIVE",
      blurb: "Pull monosemantic features out of polysemantic neurons - train a real sparse autoencoder and watch its dictionary atoms snap onto the true hidden features.", lesson: "learn/trustworthy-ai/sparse-autoencoder/" },
    { slug: "probing-classifier",   topic: "INTERPRETABILITY", title: "Linear Probing by Layer", tone: "violet", status: "LIVE",
      blurb: "Fit a linear probe to each layer and watch representations become linearly separable with depth - the standard test for what a layer encodes." },
    { slug: "activation-patching",  topic: "INTERPRETABILITY", title: "Activation Patching (Causal Tracing)", tone: "violet", status: "LIVE",
      blurb: "Copy one neuron from a clean run into a corrupted run and measure how much the answer is restored - the causal-tracing method that localizes what a network uses.", lesson: "learn/advanced-nlp/interpretability/" },
    { slug: "superposition",        topic: "INTERPRETABILITY", title: "Toy Model of Superposition", tone: "violet", status: "LIVE",
      blurb: "Watch a network pack more features than it has dimensions - superposition emerging as antipodal pairs and polygons, the reason neurons are polysemantic.", lesson: "learn/trustworthy-ai/superposition-sae/" },
    { slug: "regret-matching",      topic: "GAME THEORY",  title: "Regret Matching to Nash", tone: "violet", status: "LIVE",
      blurb: "Two no-regret learners play a game and their average strategy converges to a Nash equilibrium - the normal-form core of CFR, the algorithm behind superhuman poker.", lesson: "learn/reinforcement-learning/bandits/" },
    { slug: "replicator-dynamics",  topic: "GAME THEORY",  title: "Replicator Dynamics", tone: "violet", status: "LIVE",
      blurb: "Evolve a population of strategies on the simplex - watch Rock-Paper-Scissors cycle forever around Nash while coordination games flow to a corner.", lesson: "learn/reinforcement-learning/replicator-dynamics/" },
    { slug: "pd-tournament",        topic: "GAME THEORY",  title: "Iterated Prisoner's Dilemma Tournament", tone: "violet", status: "LIVE",
      blurb: "Run Axelrod's round-robin and watch nice, reciprocal strategies (TitForTat) beat pure defection - cooperation emerging from repetition.", lesson: "learn/reinforcement-learning/iterated-prisoners-dilemma/" },
    { slug: "mutual-information",   topic: "INFORMATION THEORY", title: "Mutual Information vs Correlation", tone: "blue", status: "LIVE",
      blurb: "Correlation only sees straight lines - mutual information detects any dependence, including a parabola and a ring where correlation is zero.", lesson: "learn/foundations/mutual-information/" },
    { slug: "channel-capacity",     topic: "INFORMATION THEORY", title: "Channel Capacity", tone: "blue", status: "LIVE",
      blurb: "How much information survives a noisy channel - Shannon's binary symmetric channel and the capacity C = 1 - H(p) that no code can beat.", lesson: "learn/foundations/channel-capacity/" },
    { slug: "huffman-coding",       topic: "INFORMATION THEORY", title: "Huffman Coding & Entropy", tone: "blue", status: "LIVE",
      blurb: "Build the optimal compression code and watch its average length hug the entropy limit H <= L < H+1 - why entropy is the floor of lossless compression.", lesson: "learn/foundations/huffman-coding/" },
    { slug: "broadcasting",         topic: "TENSORS", title: "Broadcasting", tone: "blue", status: "LIVE",
      blurb: "One rule applied right to left - what stretches, the memory it saves by never materialising, and the silent (4,1)+(1,4) shape bug it lets through.", lesson: "learn/foundations/advanced-numpy-pytorch/" },
    { slug: "cross-entropy",        topic: "INFORMATION THEORY", title: "Cross-Entropy Loss", tone: "blue", status: "LIVE",
      blurb: "The loss every classifier is trained with - and why its gradient keeps working when the model is confidently wrong, where squared error's collapses.", lesson: "learn/foundations/cross-entropy/" },
    { slug: "classification-metrics", topic: "EVALUATION", title: "Classification Metrics", tone: "blue", status: "LIVE",
      blurb: "Read the confusion matrix - accuracy, precision, recall, F1, and the macro / micro / weighted / F-beta averagings that disagree on imbalanced data.", lesson: "learn/interview-capstone/classification-metrics/" },
    { slug: "adversarial-examples", topic: "ROBUSTNESS",   title: "Adversarial Examples (FGSM / PGD)", tone: "blue", status: "LIVE",
      blurb: "Nudge an input along the loss gradient and fool a real classifier inside an epsilon ball - then defend it with adversarial training.", lesson: "learn/trustworthy-ai/adversarial-examples/" },
    { slug: "certified-robustness", topic: "ROBUSTNESS",   title: "Certified Robustness (Randomized Smoothing)", tone: "blue", status: "LIVE",
      blurb: "Wrap a classifier in Gaussian noise to earn a provable safety radius R = sigma * Phi-inverse(pA) - no perturbation inside the circle can change its answer.", lesson: "learn/trustworthy-ai/certified-robustness/" },
    { slug: "morphological-ops",    topic: "COMPUTER VISION", title: "Morphological Operations", tone: "violet", status: "LIVE",
      blurb: "Reshape a binary image with erosion, dilation, opening, closing, and gradient - the cleanup crew of classical vision.", lesson: "learn/advanced-cv/morphological-operations/" },
    { slug: "template-matching",    topic: "COMPUTER VISION", title: "Template Matching (NCC)", tone: "violet", status: "LIVE",
      blurb: "Slide a template over an image and score every position - and see why normalized cross-correlation beats raw differences under a brightness change.", lesson: "learn/advanced-cv/template-matching/" },
    { slug: "histogram-equalization", topic: "COMPUTER VISION", title: "Histogram Equalization", tone: "violet", status: "LIVE",
      blurb: "Push a washed-out image's tones through its own CDF to spread the contrast - plus CLAHE clipping to tame noise.", lesson: "learn/ml-theory/data-augmentation/" },
    { slug: "overfitting",        topic: "ML THEORY",     title: "Overfitting Lab",       tone: "violet", status: "LIVE",
      blurb: "Fit a polynomial to noisy data and watch the bias-variance tradeoff and overfitting play out.", lesson: "learn/fine-tuning/full-fine-tuning/" },
    { slug: "cross-validation",   topic: "ML THEORY",     title: "Cross-Validation",      tone: "violet", status: "LIVE",
      blurb: "k-fold CV for model selection: a held-out fold rotates through the data while train error falls forever and CV error traces a U whose minimum is the right complexity.", lesson: "learn/ml-theory/cross-validation/" },
    { slug: "double-descent",     topic: "ML THEORY",     title: "Double Descent",        tone: "violet", status: "LIVE",
      blurb: "Test error dips, spikes at the interpolation threshold, then dips again as capacity grows. Sweep capacity to watch the fit go wild at P/N=1 — then see what noise and ridge do to the peak.", lesson: "learn/ml-theory/bias-variance/" },
    { slug: "bias-variance-decomp", topic: "ML THEORY",   title: "Bias-Variance Decomposition", tone: "violet", status: "LIVE",
      blurb: "Fit many models to resampled noisy data and watch error split into bias², variance, and irreducible noise. Sweep complexity to trace the U-curve; add data to see variance collapse." },
    { slug: "roc",                topic: "ML THEORY",     title: "ROC, PR & Thresholds",  tone: "blue",   status: "LIVE",
      blurb: "Slide a decision threshold across two score distributions and watch precision, recall, ROC, and PR trade off.", lesson: "learn/supervised-learning/roc/" },
    { slug: "decision-tree",      topic: "CLASSICAL ML",  title: "Decision Tree",         tone: "violet", status: "LIVE",
      blurb: "Watch a CART tree carve the plane into axis-aligned regions — and overfit as it deepens.", lesson: "learn/supervised-learning/decision-tree/" },
    { slug: "bagging-boosting",   topic: "CLASSICAL ML",  title: "Bagging vs Boosting",   tone: "violet", status: "LIVE",
      blurb: "Bagging averages bootstrap-trained deep trees to cut variance; boosting stacks shallow trees on the residual to cut bias. Tune depth, count, and noise to see each shine and fail.", lesson: "learn/supervised-learning/ensembles/" },
    { slug: "gaussian-process",   topic: "CLASSICAL ML",  title: "Gaussian Processes",    tone: "violet", status: "LIVE",
      blurb: "A distribution over functions with closed-form uncertainty. Click to add points and watch the posterior mean bend and the ±2σ band pinch shut at data, flare open where you have none." },
    { slug: "knn",                topic: "CLASSICAL ML",  title: "k-Nearest Neighbors",   tone: "blue",   status: "LIVE",
      blurb: "Vote among the k closest points; tune k to trade a jagged boundary for a smooth one.", lesson: "learn/supervised-learning/knn/" },
    { slug: "naive-bayes",        topic: "CLASSICAL ML",  title: "Gaussian Naive Bayes",  tone: "violet", status: "LIVE",
      blurb: "Classify by Bayes' rule assuming features are independent within each class. Tilt the data so features correlate to see what the naive diagonal-covariance assumption costs versus full QDA.", lesson: "learn/supervised-learning/naive-bayes/" },
    { slug: "svm",                topic: "CLASSICAL ML",  title: "SVM - Margins & Kernels", tone: "blue", status: "LIVE",
      blurb: "Find the widest-margin boundary, see the support vectors that define it, then bend it with the kernel trick.", lesson: "learn/supervised-learning/svm/" },
    { slug: "pca",                topic: "UNSUPERVISED",  title: "Principal Component Analysis", tone: "violet", status: "LIVE",
      blurb: "Find the axes of greatest variance via a real covariance eigen-decomposition, then project onto them.", lesson: "learn/unsupervised-learning/pca/" },
    { slug: "tsne",               topic: "UNSUPERVISED",  title: "t-SNE",                 tone: "violet", status: "LIVE",
      blurb: "Watch real KL-divergence gradient descent pull high-dimensional clusters apart in 2D. Tune perplexity and learning rate to see t-SNE work — and the ways it famously misleads.", lesson: "learn/unsupervised-learning/tsne-umap/" },
    { slug: "isomap",             topic: "UNSUPERVISED",  title: "Isomap",                tone: "violet", status: "LIVE",
      blurb: "Nonlinear manifold learning: unroll a curved shape by geodesic (graph) distance, recovering an order that straight-line PCA folds and scrambles. Tune k to see the short-circuit failure." },
    { slug: "gmm",                topic: "UNSUPERVISED",  title: "Gaussian Mixtures & EM", tone: "violet", status: "LIVE",
      blurb: "Soft clustering by Expectation-Maximization — fit overlapping Gaussians and watch the log-likelihood climb.", lesson: "learn/unsupervised-learning/gmm-em/" },
    { slug: "spectral-clustering", topic: "UNSUPERVISED", title: "Spectral Clustering",   tone: "violet", status: "LIVE",
      blurb: "Cluster by graph connectivity, not distance. The Laplacian's eigenvectors separate interlocking rings and moons that k-means cuts straight through.", lesson: "learn/unsupervised-learning/kmeans/" },
    { slug: "label-propagation",  topic: "SEMI-SUPERVISED", title: "Label Propagation",   tone: "violet", status: "LIVE",
      blurb: "Semi-supervised learning: one or two labels per class spread through a similarity graph to color hundreds of unlabeled points along the data's shape.", lesson: "learn/ml-applications/semi-supervised/" },
    { slug: "clt",                topic: "PROBABILITY",   title: "Central Limit Theorem", tone: "violet", status: "LIVE",
      blurb: "Average samples from any distribution and watch the means pile up into a Gaussian.", lesson: "learn/foundations/clt/" },
    { slug: "attention",          topic: "TRANSFORMERS",  title: "Attention Heatmap",     tone: "violet", status: "LIVE",
      blurb: "Type a sentence and see scaled dot-product attention decide which tokens look at which.", lesson: "learn/transformers/self-attention/" },
    { slug: "positional-encoding",topic: "TRANSFORMERS",  title: "Positional Encoding",   tone: "blue",   status: "LIVE",
      blurb: "Visualize how sinusoidal and rotary encodings inject order into a transformer.", lesson: "learn/transformers/positional-encoding/" },
    { slug: "multi-head-attention", topic: "TRANSFORMERS", title: "Multi-Head Attention", tone: "violet", status: "LIVE",
      blurb: "Several real attention patterns in parallel — flip between heads and watch each one specialize on the same sentence.", lesson: "learn/transformers/multi-head-attention/" },
    { slug: "tokenizer",          topic: "NLP",           title: "Tokenizer Lab",         tone: "violet", status: "LIVE",
      blurb: "Watch BPE carve your text into subword tokens — trained live in the browser.", lesson: "learn/transformers/tokenization/" },
    { slug: "markov",             topic: "NLP",           title: "Markov Text Generator", tone: "blue",   status: "LIVE",
      blurb: "The simplest language model — count which token follows which, then sample. The ancestor of every LLM.", lesson: "learn/rnn-nlp/classical-lm/" },
    { slug: "decoding",           topic: "NLP",           title: "Decoding Strategies",   tone: "violet", status: "LIVE",
      blurb: "Temperature, top-k, and top-p — how the same model becomes safe or wild depending on how you sample.", lesson: "learn/transformers/decoding/" },
    { slug: "gridworld-rl",       topic: "REINFORCEMENT LEARNING",            title: "Q-Learning Gridworld",  tone: "blue",   status: "LIVE",
      blurb: "Watch a Q-learning agent learn a policy in a gridworld, one episode at a time.", lesson: "learn/reinforcement-learning/imitation-learning/" },
    { slug: "bandit",             topic: "REINFORCEMENT LEARNING",            title: "Multi-Armed Bandit",    tone: "violet", status: "LIVE",
      blurb: "Explore vs exploit: pit ε-greedy, UCB, and Thompson sampling against each other.", lesson: "learn/reinforcement-learning/bandits/" },
    { slug: "value-iteration",    topic: "REINFORCEMENT LEARNING",            title: "MDP Value Iteration",   tone: "blue",   status: "LIVE",
      blurb: "Solve a gridworld exactly — Bellman backups propagate value out from the goal, inducing the optimal policy.", lesson: "learn/reinforcement-learning/mdp-bellman/" },
    { slug: "perceptron",         topic: "NEURAL NETS",   title: "The Perceptron",        tone: "violet", status: "LIVE",
      blurb: "The original learning algorithm: one corrective nudge per misclassified point swings a boundary into place. Separable data converges by theorem; raise the overlap and it never settles.", lesson: "learn/neural-nets/perceptron-mlp/" },
    { slug: "neural-playground",  topic: "NEURAL NETS",   title: "Neural Playground",     tone: "blue",   status: "LIVE",
      blurb: "Train a tiny neural net live on 2D data and watch the decision boundary form.", lesson: "learn/neural-nets/mlp/" },
    { slug: "activations",        topic: "NEURAL NETS",   title: "Activation Functions",  tone: "blue",   status: "LIVE",
      blurb: "Plot sigmoid, tanh, ReLU, GELU and their gradients — and see where gradients vanish.", lesson: "learn/neural-nets/activations/" },
    { slug: "batch-norm",         topic: "NEURAL NETS",   title: "Batch Normalization",   tone: "violet", status: "LIVE",
      blurb: "Watch a mini-batch's activations drift, explode, or saturate across a deep stack — then turn BatchNorm on and see every layer snap back to a healthy unit-variance spread.", lesson: "learn/neural-nets/batch-norm/" },
    { slug: "weight-init",        topic: "NEURAL NETS",   title: "Weight Initialization", tone: "violet", status: "LIVE",
      blurb: "The activation std stays near 1 or diverges exponentially with depth depending entirely on the init scale. Compare Naive vs Xavier vs He, and switch the activation to see which is right.", lesson: "learn/neural-nets/weight-init/" },
    { slug: "contrastive-learning", topic: "NEURAL NETS", title: "Contrastive Learning",   tone: "violet", status: "LIVE",
      blurb: "Optimize the SimCLR / NT-Xent loss live: two views of each item pull together (alignment) while every other item is pushed away (uniformity) — all without labels.", lesson: "learn/multimodal/contrastive-learning/" },
    { slug: "convolution",        topic: "COMPUTER VISION", title: "Convolution Lab",     tone: "violet", status: "LIVE",
      blurb: "Apply and design kernels on an image to see what each filter detects.", lesson: "learn/cnn/convolution/" },
    { slug: "edge-detection",     topic: "COMPUTER VISION", title: "Canny Edge Detection", tone: "violet", status: "LIVE",
      blurb: "Walk the five-stage Canny pipeline — blur, Sobel gradient, non-max suppression, double threshold, hysteresis — and watch edges emerge from raw pixels.", lesson: "learn/advanced-cv/ocr/" },
    { slug: "hough-transform",    topic: "COMPUTER VISION", title: "Hough Transform",      tone: "violet", status: "LIVE",
      blurb: "Find straight lines by voting: every edge point votes for the lines through it, and real lines emerge as bright peaks in the (rho, theta) accumulator.", lesson: "learn/advanced-cv/hough-transform/" },
    { slug: "sift",               topic: "COMPUTER VISION", title: "SIFT", tone: "violet", status: "LIVE",
      blurb: "Match the same physical point across scale and rotation - scale space, DoG extrema, orientation, the 128-D descriptor and Lowe's ratio test, every match scored against a known transform.", lesson: "learn/advanced-cv/" },
    { slug: "grad-cam",           topic: "COMPUTER VISION", title: "Grad-CAM", tone: "violet", status: "LIVE",
      blurb: "Train a small CNN right here, then ask it where it looked - and run the randomised-weights sanity check that most published saliency methods failed.", lesson: "learn/advanced-cv/grad-cam/" },
    { slug: "integral-image",     topic: "COMPUTER VISION", title: "Integral Images & Haar Features", tone: "violet", status: "LIVE",
      blurb: "Precompute once and every rectangle sum costs four reads, whatever its size - the summed-area table and the Haar features behind real-time face detection.", lesson: "learn/advanced-cv/" },
    { slug: "receptive-field",    topic: "COMPUTER VISION", title: "Receptive Field", tone: "blue", status: "LIVE",
      blurb: "How far back one unit can see - depth adds, stride compounds, dilation is free - and why the region it actually uses is smaller than the number you would quote.", lesson: "learn/cnn/convolution/" },
    { slug: "image-pyramids",     topic: "COMPUTER VISION", title: "Image Pyramids", tone: "violet", status: "LIVE",
      blurb: "Blur then halve, over and over - Gaussian and Laplacian pyramids, why the blur is not optional, and why the whole stack costs only 4/3 of the original.", lesson: "learn/advanced-cv/" },
    { slug: "bilateral-filter",   topic: "COMPUTER VISION", title: "Bilateral Filter", tone: "violet", status: "LIVE",
      blurb: "Smooth the noise and keep the edges by weighting neighbours on how SIMILAR they are, not just how close - with the Gaussian beside it so you can read the trade.", lesson: "learn/advanced-cv/" },
    { slug: "ransac",             topic: "COMPUTER VISION", title: "RANSAC", tone: "violet", status: "LIVE",
      blurb: "Fit a model to data that is mostly wrong - sample two points, count how many agree, keep the largest consensus, and watch least squares get dragged away by outliers RANSAC never sees.", lesson: "learn/advanced-cv/" },
    { slug: "harris-corners",     topic: "COMPUTER VISION", title: "Harris Corner Detector", tone: "violet", status: "LIVE",
      blurb: "Find corners from the eigenvalues of the local gradient structure tensor — where intensity changes in two directions at once. The keypoints behind tracking and SLAM.", lesson: "learn/advanced-cv/harris-corners/" },
    { slug: "optical-flow",       topic: "COMPUTER VISION", title: "Optical Flow (Lucas-Kanade)", tone: "violet", status: "LIVE",
      blurb: "Estimate per-point motion between frames from brightness constancy — solve the 2x2 least-squares window system and watch the aperture problem and small-motion limit live.", lesson: "learn/advanced-cv/optical-flow/" },
    { slug: "hog",                topic: "COMPUTER VISION", title: "Histogram of Oriented Gradients", tone: "violet", status: "LIVE",
      blurb: "Summarize an image by where its edges point — per-cell orientation histograms, block-normalized into the descriptor behind classic HOG+SVM object detection.", lesson: "learn/cnn/convolution/" },
    { slug: "image-augmentation", topic: "COMPUTER VISION", title: "Data Augmentation", tone: "violet", status: "LIVE",
      blurb: "Manufacture endless training views from one labeled image with label-preserving random flips, rotations, crops, color jitter, and cutout — deep learning's cheapest regularizer.", lesson: "learn/cnn/data-augmentation/" },
    { slug: "watershed",          topic: "COMPUTER VISION", title: "Watershed Segmentation", tone: "violet", status: "LIVE",
      blurb: "Separate touching objects by flooding the distance transform from markers and damming where basins meet — and watch the marker count flip between over- and under-segmentation.", lesson: "learn/cnn/segmentation/" },
    { slug: "nms",                topic: "COMPUTER VISION", title: "IoU & Non-Max Suppression", tone: "blue", status: "LIVE",
      blurb: "Turn a cloud of overlapping detection boxes into one clean box per object with IoU + greedy NMS.", lesson: "learn/advanced-cv/yolo/" },
    { slug: "diffusion",          topic: "GENERATIVE",    title: "Diffusion Sampler",     tone: "blue",   status: "LIVE",
      blurb: "Step through a denoising chain turning pure noise into samples from a 2D distribution.", lesson: "learn/generative/diffusion/" },
    { slug: "vae",                topic: "GENERATIVE",    title: "Variational Autoencoder", tone: "violet", status: "LIVE",
      blurb: "Train a tiny VAE live — reparameterization, a KL-shaped latent space, and generation from pure noise.", lesson: "learn/generative/vae/" },
    { slug: "fourier",            topic: "SIGNAL",        title: "Fourier Series",        tone: "violet", status: "LIVE",
      blurb: "Rotating epicycles — one per sine wave — summing into square, sawtooth, and triangle waves.", lesson: "learn/foundations/fourier/" },
    { slug: "ica",                topic: "SIGNAL",        title: "ICA (Cocktail Party)",  tone: "violet", status: "LIVE",
      blurb: "Blind source separation: two signals blended into two microphones, unmixed by FastICA hunting the least-Gaussian directions. Switch to two Gaussian sources and watch it fail by design.", lesson: "learn/unsupervised-learning/ica/" },
    { slug: "forecasting",        topic: "TIME SERIES",   title: "Time-Series Forecasting", tone: "blue", status: "LIVE",
      blurb: "Level, trend, and seasonality: exponential smoothing fit on history and scored on a held-out future.", lesson: "learn/ml-applications/forecasting/" },
    { slug: "embeddings",         topic: "EMBEDDINGS",    title: "Embedding Atlas",       tone: "violet", status: "LIVE",
      blurb: "Explore word embeddings in 2D — nearest neighbors and analogy arrows.", lesson: "learn/transformers/embeddings/" },
    { slug: "word2vec",           topic: "EMBEDDINGS",    title: "word2vec (Skip-gram)",  tone: "violet", status: "LIVE",
      blurb: "Train real 2-D word vectors with skip-gram SGD and watch topics self-organize into clusters from co-occurrence alone. Raise the cross-topic mix to see the geometry blur.", lesson: "learn/rnn-nlp/word-vectors/" },
    { slug: "vector-search",      topic: "RAG / RETRIEVAL", title: "Vector Search",       tone: "violet", status: "LIVE",
      blurb: "Click to query an embedding space and watch k-NN retrieval — the engine under semantic search and RAG.", lesson: "learn/multimodal/vector-search/" },
    { slug: "lr-schedule",        topic: "TRAINING",      title: "Learning-Rate Schedules", tone: "blue", status: "LIVE",
      blurb: "Warmup and decay, and the real noisy-SGD loss curve that converges or diverges depending on the schedule.", lesson: "learn/training-systems/lr-schedule/" },
    { slug: "gradient-clipping",  topic: "TRAINING",      title: "Gradient Clipping",      tone: "violet", status: "LIVE",
      blurb: "A loss cliff makes the gradient explode; one unclipped step launches the parameters off the map. Norm clipping caps the gradient so descent stays bounded — race a clipped and unclipped walker.", lesson: "learn/training-systems/training-stability/" },
    { slug: "lora",               topic: "FINE-TUNING",   title: "LoRA - Low-Rank Adaptation", tone: "violet", status: "LIVE",
      blurb: "Approximate a full weight update with two thin matrices via real truncated SVD — most of the change, a fraction of the params.", lesson: "learn/fine-tuning/lora/" },
    { slug: "scaling-laws",       topic: "SCALING",       title: "Neural Scaling Laws",   tone: "blue",   status: "LIVE",
      blurb: "The power-law loss frontier and the compute-optimal balance of model size and data (Chinchilla).", lesson: "learn/llm-systems/scaling-laws/" },
    { slug: "bayes",              topic: "FOUNDATIONS",   title: "Bayes Updater",         tone: "violet", status: "LIVE",
      blurb: "A Beta prior meets Bernoulli flips: drag your prior, watch the posterior tighten on the truth, learn conjugate updating by feel.", lesson: "learn/foundations/bayes/" },
    { slug: "kalman-filter",      topic: "FOUNDATIONS",   title: "Kalman Filter",         tone: "violet", status: "LIVE",
      blurb: "A real 2-state Kalman filter tracks a maneuvering target from noisy measurements — tune process and sensor noise to move the gain and watch it denoise in real time.", lesson: "learn/ml-applications/kalman-filter/" },
    { slug: "hmm-viterbi",        topic: "FOUNDATIONS",   title: "HMM & Viterbi",         tone: "violet", status: "LIVE",
      blurb: "Watch real Viterbi dynamic programming decode the most-likely hidden regime path from a noisy observation stream — tune persistence and emission noise to make it easy or near-impossible.", lesson: "learn/rnn-nlp/hmm-viterbi/" },
    { slug: "mcmc",               topic: "FOUNDATIONS",   title: "MCMC (Metropolis)",     tone: "violet", status: "LIVE",
      blurb: "Sample a distribution you can only evaluate up to a constant via a random walk that visits it in proportion to its density. Tune the proposal step to feel the mixing-vs-acceptance tradeoff.", lesson: "learn/causal-inference/mcmc/" },
    { slug: "importance-sampling", topic: "FOUNDATIONS",  title: "Importance Sampling",   tone: "violet", status: "LIVE",
      blurb: "Estimate a rare-event probability naive Monte Carlo never reaches by sampling a steered proposal and reweighting by p/q. Misplace the proposal and watch the effective sample size collapse.", lesson: "learn/foundations/importance-sampling/" },
    { slug: "reservoir-sampling", topic: "FOUNDATIONS",   title: "Reservoir Sampling",    tone: "violet", status: "LIVE",
      blurb: "Keep a uniform random sample of k items from an unbounded stream in one pass, O(k) memory. A Monte-Carlo histogram proves every position survives with equal probability k/N.", lesson: "learn/foundations/reservoir-sampling/" },
    { slug: "count-min-sketch",   topic: "FOUNDATIONS",   title: "Count-Min Sketch",      tone: "violet", status: "LIVE",
      blurb: "Estimate item frequencies in a massive stream with a tiny d x w table of hashed counters. Query takes the min, so collisions only ever overestimate — heavy hitters are nailed in sublinear memory.", lesson: "learn/mlops/count-min-sketch/" },
    { slug: "bloom-filter",       topic: "FOUNDATIONS",   title: "Bloom Filter",          tone: "violet", status: "LIVE",
      blurb: "Probabilistic set membership in a tiny bit array: never a false negative, only tunable false positives. Watch the FP rate climb as the array fills and find the optimal hash count.", lesson: "learn/llm-systems/llm-data-pipelines/" },
    { slug: "optimizers",         topic: "OPTIMIZATION",  title: "Optimizer Shootout",    tone: "blue",   status: "LIVE",
      blurb: "SGD, Momentum, RMSProp, and Adam racing on the same non-convex loss surface — see how each one's mechanics shape its path." },
    { slug: "gan",                topic: "GENERATIVE",    title: "GAN 2-D",               tone: "violet", status: "LIVE",
      blurb: "A real generator and discriminator duel in your browser — fakes drift toward the target as the two networks fight to a draw.", lesson: "learn/generative/gan/" },
    { slug: "backprop",           topic: "FOUNDATIONS",   title: "Backprop Graph",        tone: "blue",   status: "LIVE",
      blurb: "Step through forward then backward on a tiny computation graph — every value, every gradient, by the chain rule.", lesson: "learn/neural-nets/backprop/" },
    { slug: "mcts",               topic: "REINFORCEMENT LEARNING",            title: "MCTS Tree Search",      tone: "violet", status: "LIVE",
      blurb: "Monte-Carlo Tree Search iteration by iteration — select, expand, rollout, backup — the search that powered AlphaGo.", lesson: "learn/agentic-ai/react-planning/" },
    { slug: "simulated-annealing", topic: "OPTIMIZATION", title: "Simulated Annealing",  tone: "violet", status: "LIVE",
      blurb: "Cool a tangled traveling-salesman tour into a clean one — Metropolis acceptance, geometric cooling, real 2-opt moves.", lesson: "learn/interview-capstone/simulated-annealing/" },
    { slug: "regression",         topic: "CLASSICAL ML",  title: "Linear & Logistic Regression", tone: "blue", status: "LIVE",
      blurb: "Click to scatter points and watch the closed-form line of best fit, or train a sigmoid boundary with real gradient descent on BCE." },
    { slug: "rnn-gates",          topic: "NLP",     title: "LSTM Gates",            tone: "violet", status: "LIVE",
      blurb: "Feed a sequence into a tiny LSTM and watch the forget, input, and output gates open and close — a live look at gated memory.", lesson: "learn/rnn-nlp/lstm-gates/" },
    { slug: "beam-search",        topic: "NLP", title: "Beam Search Tree",     tone: "blue",   status: "LIVE",
      blurb: "Greedy vs beam vs sampling on a toy language model — see the search frontier branch, prune, and find the high-probability sentence.", lesson: "learn/advanced-nlp/beam-search/" },
    { slug: "kv-cache",           topic: "TRANSFORMERS",  title: "KV Cache",              tone: "blue",   status: "LIVE",
      blurb: "Toggle the KV cache during autoregressive generation and watch per-step compute either stay flat or grow with prefix length.", lesson: "learn/transformers/kv-cache/" },
    { slug: "attention-rollout",  topic: "TRANSFORMERS",  title: "Attention Rollout",     tone: "violet", status: "LIVE",
      blurb: "One attention layer shows one hop; compose them to trace a token's attribution back to the input. Watch rollout spread credit beyond the last layer." },
    { slug: "gnn",                topic: "GRAPHS / NETWORKS",    title: "GNN Message Passing",   tone: "violet", status: "LIVE",
      blurb: "Watch node features smooth across a small graph as a real GCN runs message passing — and over-smooth when you stack too many layers.", lesson: "learn/ml-applications/gnn/" },
    { slug: "rope",               topic: "TRANSFORMERS",  title: "RoPE Explorer",         tone: "violet", status: "LIVE",
      blurb: "Rotary position embeddings, live — see why the attention score depends only on relative position, the trick behind every long-context LLM.", lesson: "learn/transformers/rope/" },
    { slug: "dbscan",             topic: "UNSUPERVISED",  title: "DBSCAN",                tone: "blue",   status: "LIVE",
      blurb: "Density-based clustering — no k to pick, just two knobs that define what counts as dense. Watch moons, rings, and blobs cluster cleanly while noise stays gray.", lesson: "learn/unsupervised-learning/dbscan/" },
    { slug: "hierarchical-clustering", topic: "UNSUPERVISED", title: "Hierarchical Clustering", tone: "violet", status: "LIVE",
      blurb: "Merge the closest clusters into a tree, then slide a cut across the dendrogram to read off any number of clusters from one structure. Switch linkage for compact, chained, or Ward clusters.", lesson: "learn/unsupervised-learning/hierarchical-clustering/" },
    { slug: "kernel-density",     topic: "UNSUPERVISED",  title: "Kernel Density Estimation", tone: "violet", status: "LIVE",
      blurb: "Drop a kernel on every point and sum them into a smooth, assumption-free density. Drag the bandwidth to watch the bias/variance tradeoff: spiky at small h, oversmoothed at large h.", lesson: "learn/unsupervised-learning/kernel-density/" },
    { slug: "policy-gradient",    topic: "REINFORCEMENT LEARNING", title: "Policy Gradient — REINFORCE", tone: "violet", status: "LIVE",
      blurb: "A Gaussian policy finds a hidden target by sampling, scoring, and ascending log-prob times reward. The simplest RL — parent of PPO, GRPO, and RLHF.", lesson: "learn/reinforcement-learning/policy-gradient/" },
    { slug: "actor-critic",       topic: "REINFORCEMENT LEARNING", title: "Actor-Critic", tone: "violet", status: "LIVE",
      blurb: "A critic learns each state's value while an actor learns the policy — one shared TD error trains both. The learned baseline behind A2C, PPO, and RLHF.", lesson: "learn/reinforcement-learning/actor-critic/" },
    { slug: "dqn",                topic: "REINFORCEMENT LEARNING", title: "Deep Q-Network (DQN)", tone: "violet", status: "LIVE",
      blurb: "A neural net learns Q(s, a) on a continuous state. Toggle experience replay and the target network to see why deep RL needs both to stay stable.", lesson: "learn/reinforcement-learning/dqn/" },
    { slug: "reward-model",       topic: "REINFORCEMENT LEARNING", title: "Reward Model (RLHF)", tone: "violet", status: "LIVE",
      blurb: "Learn a scalar reward from pairwise human preferences with Bradley-Terry — the signal PPO maximizes in RLHF. Watch the learned field reconstruct the hidden one.", lesson: "learn/fine-tuning/reward-model/" },
    { slug: "dpo",                topic: "REINFORCEMENT LEARNING", title: "DPO vs RLHF", tone: "violet", status: "LIVE",
      blurb: "Align a policy from the same human preferences two ways — RLHF's reward model + RL loop vs DPO's direct update — and watch them converge to the same policy.", lesson: "learn/fine-tuning/dpo-grpo/" },
    { slug: "sarsa-vs-qlearning", topic: "REINFORCEMENT LEARNING", title: "SARSA vs Q-Learning", tone: "violet", status: "LIVE",
      blurb: "Cliff Walking: one term in the TD update separates on-policy SARSA (safe path) from off-policy Q-learning (optimal cliff-edge path) — and the online reward gap it causes.", lesson: "learn/reinforcement-learning/q-learning/" },
    { slug: "td-lambda",          topic: "REINFORCEMENT LEARNING", title: "TD(λ) & Eligibility Traces", tone: "violet", status: "LIVE",
      blurb: "One knob from one-step TD to Monte Carlo. Eligibility traces carry a reward's credit backward along the path you took — and an intermediate λ usually learns fastest.", lesson: "learn/reinforcement-learning/q-learning/" },
    { slug: "ppo",                topic: "REINFORCEMENT LEARNING", title: "PPO Clipped Objective", tone: "violet", status: "LIVE",
      blurb: "The clip that made policy gradients stable: reward moving the policy only within a trust region, so you can reuse a batch for many epochs without a destructive update.", lesson: "learn/reinforcement-learning/ppo/" },
    { slug: "dyna-q",             topic: "REINFORCEMENT LEARNING", title: "Dyna-Q (Model-Based Planning)", tone: "violet", status: "LIVE",
      blurb: "Learn a model from experience, then plan inside it. n imagined updates per real step let Dyna-Q solve the maze in a fraction of the experience model-free Q-learning needs.", lesson: "learn/reinforcement-learning/dyna-q/" },
    { slug: "double-q-learning",  topic: "REINFORCEMENT LEARNING", title: "Double Q-Learning", tone: "violet", status: "LIVE",
      blurb: "Selecting and evaluating with the same noisy max overestimates, so Q-learning prefers a losing action. Two decoupled estimators cancel the maximization bias.", lesson: "learn/reinforcement-learning/double-q-learning/" },
    { slug: "gae",                topic: "REINFORCEMENT LEARNING", title: "Generalized Advantage Estimation", tone: "violet", status: "LIVE",
      blurb: "The one knob λ that trades bias against variance in the advantage estimate behind every modern policy gradient — and a critic error that shifts the sweet spot.", lesson: "learn/reinforcement-learning/gae/" },
    { slug: "prioritized-replay", topic: "REINFORCEMENT LEARNING", title: "Prioritized Experience Replay", tone: "violet", status: "LIVE",
      blurb: "Replay surprising transitions first. Sampling by TD error sweeps value back from a sparse reward in a fraction of the updates uniform replay needs.", lesson: "learn/reinforcement-learning/dqn/" },
    { slug: "distributional-rl",  topic: "REINFORCEMENT LEARNING", title: "Distributional RL (C51)", tone: "violet", status: "LIVE",
      blurb: "Learn the whole distribution of returns, not just its mean. The distributional Bellman backup carries a bimodal payoff back through the chain — the scalar value hides it.", lesson: "learn/reinforcement-learning/distributional-rl/" },
    { slug: "successor-representation", topic: "REINFORCEMENT LEARNING", title: "Successor Representation", tone: "violet", status: "LIVE",
      blurb: "Separate where you'll go from what you want. Learn the successor map once, then move the reward and value recomputes instantly as V = M·R — no relearning.", lesson: "learn/reinforcement-learning/successor-representation/" },
    { slug: "max-entropy-rl",     topic: "REINFORCEMENT LEARNING", title: "Maximum-Entropy RL", tone: "violet", status: "LIVE",
      blurb: "Maximize reward plus entropy. The temperature α slides from a single greedy path to a stochastic policy that keeps its options open — the idea behind Soft Actor-Critic.", lesson: "learn/reinforcement-learning/max-entropy-rl/" },
    { slug: "rag-chunking",       topic: "RAG / RETRIEVAL", title: "RAG Chunking", tone: "violet", status: "LIVE",
      blurb: "Chunk size, overlap, and strategy decide whether the answer survives retrieval. Real TF-IDF cosine over the chunks — watch the retrieval verdict flip.", lesson: "learn/rag-agents/rag-chunking/" },
    { slug: "self-consistency",   topic: "AGENTS / LLM OPS", title: "Self-Consistency", tone: "violet", status: "LIVE",
      blurb: "Sample many chains of thought and majority-vote the answer. See why it lifts accuracy — and why correlated errors quietly defeat it.", lesson: "learn/advanced-nlp/cot/" },
    { slug: "constrained-decoding", topic: "AGENTS / LLM OPS", title: "Constrained Decoding", tone: "violet", status: "LIVE",
      blurb: "Mask the grammar-invalid tokens at every step and structured output becomes guaranteed, not hoped-for. Raw vs constrained JSON generation, side by side.", lesson: "learn/agentic-ai/constrained-decoding/" },
    { slug: "guardrails",         topic: "AGENTS / LLM OPS", title: "Guardrails", tone: "violet", status: "LIVE",
      blurb: "The input/output safety pipeline around an LLM — PII redaction, injection and topic guards, output filtering. Toggle a guard off and watch a threat get through.", lesson: "learn/rag-agents/guardrails/" },
    { slug: "prompt-injection",   topic: "AGENTS / LLM OPS", title: "Prompt Injection", tone: "violet", status: "LIVE",
      blurb: "Untrusted content posing as instructions. Pick an attack — direct, indirect, jailbreak, exfiltration — layer the structural defenses, and watch how much survives.", lesson: "learn/trustworthy-ai/red-teaming/" },
    { slug: "semantic-caching",   topic: "AGENTS / LLM OPS", title: "Semantic Caching", tone: "violet", status: "LIVE",
      blurb: "Cache LLM answers by embedding similarity, not exact text. Slide the threshold between big cost savings and serving a confidently wrong cached answer.", lesson: "learn/mlops/semantic-caching/" },
    { slug: "kv-cache-eviction",  topic: "AGENTS / LLM OPS", title: "KV-Cache Eviction", tone: "violet", status: "LIVE",
      blurb: "Bound the KV cache by dropping past tokens. Sliding-window throws away the attention sinks and quality crashes; sink+window and H2O hold it at the same memory.", lesson: "learn/llm-systems/kv-cache-eviction/" },
    { slug: "mixture-of-depths",  topic: "AGENTS / LLM OPS", title: "Mixture-of-Depths", tone: "violet", status: "LIVE",
      blurb: "Per-token dynamic compute: a router picks which tokens each block processes under a fixed capacity. Smart routing keeps quality at a fraction of the FLOPs.", lesson: "learn/llm-systems/moe/" },
    { slug: "context-extension",  topic: "AGENTS / LLM OPS", title: "Context Extension", tone: "violet", status: "LIVE",
      blurb: "Stretch a RoPE model past its training length. Naive extrapolation falls off a cliff; PI, NTK-aware, and YaRN rescale the positions to hold quality.", lesson: "learn/transformers/rope/" },
    { slug: "lost-in-the-middle", topic: "AGENTS / LLM OPS", title: "Lost in the Middle", tone: "violet", status: "LIVE",
      blurb: "Models use the start and end of a long context far better than the middle. Slide the answer's position along the U-curve — and rerank it to the front to fix it." },
    { slug: "hyde",               topic: "AGENTS / LLM OPS", title: "HyDE — Hypothetical Embeddings", tone: "violet", status: "LIVE",
      blurb: "Questions embed away from their answers. Draft a hypothetical answer, embed that instead, and retrieval lands on the right documents.", lesson: "learn/rag-agents/hyde/" },
    { slug: "reflection",         topic: "AGENTS / LLM OPS", title: "Self-Correction (Reflection)", tone: "violet", status: "LIVE",
      blurb: "Draft, critique, revise, repeat. Watch quality climb to the bar — then weaken the critic and see reflection stall, ship garbage, or burn the budget.", lesson: "learn/rag-agents/reflection/" },
    { slug: "react-agent",        topic: "AGENTS / LLM OPS", title: "ReAct — Reason + Act", tone: "violet", status: "LIVE",
      blurb: "The tool-using agent loop: Thought → Action → Observation, repeat. Watch a worked trace — then drop the reliability and see errors compound.", lesson: "learn/rag-agents/react-agent/" },
    { slug: "multi-query",        topic: "AGENTS / LLM OPS", title: "Multi-Query & RAG-Fusion", tone: "violet", status: "LIVE",
      blurb: "One phrasing misses docs another catches. Retrieve with several query variants and fuse the ranked lists by reciprocal rank — recall beats any single query.", lesson: "learn/rag-agents/rag-fusion/" },
    { slug: "rag-reranker",       topic: "AGENTS / LLM OPS", title: "RAG Reranker", tone: "violet", status: "LIVE",
      blurb: "Cheap lexical retrieval buries semantically-relevant docs; a cross-encoder reranker re-scores the shortlist and floats them to the top. Watch nDCG jump.", lesson: "learn/rag-agents/advanced-rag/" },
    { slug: "agent-router",       topic: "AGENTS / LLM OPS", title: "Agent Tool Router", tone: "violet", status: "LIVE",
      blurb: "Which tool handles this query? Score it against each tool, route to the top above a confidence threshold, and fall back to the model when nothing fits.", lesson: "learn/agentic-ai/tool-routing/" },
    { slug: "calibration",        topic: "TRUSTWORTHY ML", title: "Model Calibration", tone: "blue", status: "LIVE",
      blurb: "A '90% confident' model should be right 90% of the time. See overconfidence on a reliability diagram, measure ECE, and fix it with one temperature knob.", lesson: "learn/ml-theory/calibration/" },
    { slug: "shap",               topic: "TRUSTWORTHY ML", title: "Feature Attribution (SHAP)", tone: "blue", status: "LIVE",
      blurb: "Why did the model decide that? Exact Shapley values credit each feature's contribution — including the interaction — as a waterfall from base to prediction.", lesson: "learn/ml-applications/shap/" },
    { slug: "conformal",          topic: "TRUSTWORTHY ML", title: "Conformal Prediction", tone: "blue", status: "LIVE",
      blurb: "Output a label set guaranteed to contain the truth (1−α) of the time — for any model. Coverage holds even as the model worsens; only set size suffers.", lesson: "learn/trustworthy-ai/conformal-prediction/" },
    { slug: "conformal-regression", topic: "TRUSTWORTHY ML", title: "Conformal Regression", tone: "blue", status: "LIVE",
      blurb: "Turn a point regressor into a prediction interval with a coverage guarantee. Coverage holds even when the mean is underfit; an adaptive score lets the band breathe with the noise.", lesson: "learn/trustworthy-ai/conformal-prediction/" },
    { slug: "active-learning",    topic: "TRUSTWORTHY ML", title: "Active Learning", tone: "blue", status: "LIVE",
      blurb: "Labels are expensive — let the model pick what to label. Uncertainty sampling races random labeling and hits high accuracy with far fewer labels.", lesson: "learn/ml-theory/active-learning/" },
    { slug: "coreset",            topic: "DATA-CENTRIC ML", title: "Coresets", tone: "violet", status: "LIVE",
      blurb: "Keep a tiny weighted subset of the data that reproduces the full k-means clustering. Importance sampling tracks the answer with a fraction of the points where uniform falls apart.", lesson: "learn/ml-applications/semi-supervised/" },
    { slug: "dataset-distillation", topic: "DATA-CENTRIC ML", title: "Dataset Distillation", tone: "violet", status: "LIVE",
      blurb: "Learn a handful of synthetic training points whose model reproduces the full dataset's boundary. Watch them migrate into the most informative positions as the distillation loss falls.", lesson: "learn/fine-tuning/instruction-tuning/" },
    { slug: "fairness",           topic: "TRUSTWORTHY ML", title: "Fairness & Group Metrics", tone: "blue", status: "LIVE",
      blurb: "Equal qualification, biased scores. See how one threshold creates unequal outcomes — and why you can't satisfy every fairness metric at once.", lesson: "learn/trustworthy-ai/fairness/" },
    { slug: "label-noise",        topic: "TRUSTWORTHY ML", title: "Label Noise", tone: "blue", status: "LIVE",
      blurb: "Flip some training labels and watch the boundary warp around them. Train longer and the model memorizes the noise — true accuracy falls as train accuracy climbs.", lesson: "learn/ml-theory/data-augmentation/" },
    { slug: "mc-dropout",         topic: "TRUSTWORTHY ML", title: "MC Dropout", tone: "blue", status: "LIVE",
      blurb: "Keep dropout on at inference and sample many times — the spread is the model's uncertainty, and it grows where the data runs out.", lesson: "learn/neural-nets/regularization/" },
    { slug: "saliency",           topic: "TRUSTWORTHY ML", title: "Saliency Maps", tone: "blue", status: "LIVE",
      blurb: "Gradient of the output w.r.t. each input pixel — a per-example map of what the model is looking at. Paint the grid and watch the explanation move.", lesson: "learn/advanced-cv/grad-cam/" },
    { slug: "drift-detection",    topic: "MLOPS", title: "Data Drift Detection", tone: "blue", status: "LIVE",
      blurb: "Deployed models rot as the world shifts. Watch the live distribution peel away from the reference and a PSI monitor trip the retrain alarm.", lesson: "learn/mlops/drift-detection/" },
    { slug: "n-queens",           topic: "SEARCH / CSP", title: "N-Queens (Backtracking)", tone: "blue", status: "LIVE",
      blurb: "Place N non-attacking queens by depth-first backtracking. Toggle forward checking and watch constraint propagation prune the search tree.", lesson: "learn/interview-capstone/backtracking/" },
    { slug: "graph-coloring",     topic: "SEARCH / CSP", title: "Graph Coloring (AC-3)", tone: "blue", status: "LIVE",
      blurb: "Color the map so neighbors differ. Backtracking with arc-consistency propagation — watch domains shrink, and compare backtracks with AC-3 on vs off.", lesson: "learn/interview-capstone/arc-consistency/" },
    { slug: "sudoku",             topic: "SEARCH / CSP", title: "Sudoku Solver", tone: "blue", status: "LIVE",
      blurb: "Backtracking + constraint propagation on a 9×9 grid. Toggle propagation off and watch the guess and backtrack counts explode for the same puzzle." },
    { slug: "quantization",       topic: "EFFICIENCY", title: "Quantization", tone: "violet", status: "LIVE",
      blurb: "Round fp32 weights to b-bit integers — smaller and faster, but coarser. Watch weights snap to the grid, and how outliers wreck it until you clip them.", lesson: "learn/llm-systems/quantization/" },
    { slug: "pruning",            topic: "EFFICIENCY", title: "Pruning & Sparsity", tone: "violet", status: "LIVE",
      blurb: "Zero the smallest weights and accuracy barely budges — until it falls off a cliff. The over-parameterization that makes networks compressible.", lesson: "learn/pytorch-internals/torch-fx/" },
    { slug: "distillation",       topic: "EFFICIENCY", title: "Knowledge Distillation", tone: "violet", status: "LIVE",
      blurb: "Train a small student to match a teacher's soft labels, not just its answers. Turn up temperature and soft-weight to transfer the teacher's dark knowledge.", lesson: "learn/llm-systems/distillation/" },
    { slug: "moe",                topic: "EFFICIENCY", title: "Mixture of Experts (MoE)", tone: "violet", status: "LIVE",
      blurb: "Route each token to a few of many experts — scale parameters, not per-token compute. Watch specialization emerge and fight the load-imbalance failure.", lesson: "learn/llm-systems/moe/" },
    { slug: "mixed-precision",    topic: "EFFICIENCY", title: "Mixed Precision", tone: "violet", status: "LIVE",
      blurb: "fp16's narrow range makes small gradients vanish and big ones blow up. Slide loss scaling to rescue them — or switch to bf16 and trade precision for range.", lesson: "learn/training-systems/mixed-precision/" },
    { slug: "speculative-decoding", topic: "EFFICIENCY", title: "Speculative Decoding", tone: "violet", status: "LIVE",
      blurb: "A small draft model guesses ahead; the big model verifies in one pass. Several tokens per expensive step — a lossless speedup set by draft agreement and lookahead.", lesson: "learn/llm-systems/speculative-decoding/" },
    { slug: "paged-attention",    topic: "EFFICIENCY", title: "PagedAttention", tone: "violet", status: "LIVE",
      blurb: "Contiguous KV-cache reservations waste memory on every half-finished sequence; paging packs fixed blocks on demand and fits far more streams in the same GPU.", lesson: "learn/frontier-frameworks/vllm-inference/" },
    { slug: "batching",           topic: "MLOPS", title: "Dynamic Batching", tone: "blue", status: "LIVE",
      blurb: "Live inference-server simulation: batch requests to amortize GPU overhead and watch throughput climb while tail latency grows — and the queue blow up the instant arrivals outrun capacity." },
    { slug: "model-cascade",      topic: "MLOPS", title: "Model Cascade (Early-Exit)", tone: "blue", status: "LIVE",
      blurb: "A cheap model answers the easy inputs and escalates only the uncertain ones to an expensive model — slide the confidence threshold along the cost-vs-accuracy curve.", lesson: "learn/interview-capstone/system-design-framework/" },
    { slug: "autoscaling",        topic: "MLOPS", title: "Autoscaling", tone: "blue", status: "LIVE",
      blurb: "Size the replica pool to chase a moving load — and watch cold-start lag breach the SLO on spikes while spare headroom trades cost for safety. A live control-loop simulation.", lesson: "learn/mlops/autoscaling/" },
    { slug: "canary-rollout",     topic: "MLOPS", title: "Canary Rollout", tone: "blue", status: "LIVE",
      blurb: "Ship a new model to a sliver of live traffic, guard it with an automated z-test, and widen or roll back — capping how many users a bad deploy can ever hit.", lesson: "learn/mlops/canary-rollout/" },
    { slug: "simpsons-paradox",   topic: "CAUSAL INFERENCE", title: "Simpson's Paradox", tone: "blue", status: "LIVE",
      blurb: "Every subgroup trends up, the pooled data trends down. See how a confounder reverses the conclusion — and why you have to condition on it.", lesson: "learn/causal-inference/confounding/" },
    { slug: "do-intervention",    topic: "CAUSAL INFERENCE", title: "do() & Backdoor Adjustment", tone: "blue", status: "LIVE",
      blurb: "Observing X is not setting X. A confounder biases the naive estimate; cut its arrow with do(X), or adjust for it, to recover the true causal effect.", lesson: "learn/causal-inference/causal-inference/" },
    { slug: "instrumental-variables", topic: "CAUSAL INFERENCE", title: "Instrumental Variables", tone: "blue", status: "LIVE",
      blurb: "Can't measure the confounder? Find an instrument that moves the treatment but not the outcome, and 2SLS reads the true effect off it — until you break relevance or exclusion.", lesson: "learn/causal-inference/instrumental-variables/" },
    { slug: "knapsack",           topic: "DYNAMIC PROGRAMMING", title: "Knapsack (DP)", tone: "blue", status: "LIVE",
      blurb: "Pack the most value into a weight budget. Watch the DP table fill from its sub-answers, then backtrack to recover which items to take.", lesson: "learn/interview-capstone/cs-algorithms/" },
    { slug: "branch-and-bound",   topic: "SEARCH / CSP", title: "Branch & Bound", tone: "blue", status: "LIVE",
      blurb: "Solve 0/1 knapsack exactly without opening every branch. An optimistic LP bound prunes whole subtrees that can't beat the best solution so far — toggle bounding off to watch it collapse into brute force.", lesson: "learn/interview-capstone/branch-and-bound/" },
    { slug: "bfs-dfs-astar",      topic: "SEARCH / CSP", title: "BFS vs DFS vs A*", tone: "blue", status: "LIVE",
      blurb: "Three searches, one maze. Watch uninformed rings and dives versus A*'s heuristic beeline — and compare nodes expanded and path optimality.", lesson: "learn/interview-capstone/cs-algorithms/" },
    { slug: "edit-distance",      topic: "DYNAMIC PROGRAMMING", title: "Edit Distance", tone: "blue", status: "LIVE",
      blurb: "The fewest insert/delete/substitute edits between two strings. Watch the DP table fill from its neighbors, then backtrack the character alignment." },
    { slug: "spectrogram",        topic: "AUDIO / SIGNAL", title: "Spectrogram (STFT)", tone: "violet", status: "LIVE",
      blurb: "See frequency change over time. The STFT windows a signal and FFTs each chunk — and the window length forces a tradeoff between time and frequency resolution.", lesson: "learn/multimodal/spectrogram/" },
    { slug: "mfcc",               topic: "AUDIO / SIGNAL", title: "Mel Filterbank & MFCC", tone: "violet", status: "LIVE",
      blurb: "Turn a sound into a dozen numbers. Spectrum → perceptual mel bands → log → DCT — the feature that named phonemes for decades of speech recognition.", lesson: "learn/multimodal/mfcc/" },
    { slug: "pitch-detection",    topic: "AUDIO / SIGNAL", title: "Pitch Detection", tone: "violet", status: "LIVE",
      blurb: "Find the note in a sound. A periodic signal autocorrelates to a peak at its period — f0 = sample rate / peak lag — and noise is what makes it hard.", lesson: "learn/multimodal/pitch-detection/" },
    { slug: "dtw",                topic: "AUDIO / SIGNAL", title: "Dynamic Time Warping", tone: "violet", status: "LIVE",
      blurb: "Align two series at different speeds. DTW finds the cheapest nonlinear warp between them — where rigid Euclidean distance fails on the smallest time shift.", lesson: "learn/multimodal/dtw/" },
    { slug: "aliasing",           topic: "AUDIO / SIGNAL", title: "Aliasing & Nyquist", tone: "violet", status: "LIVE",
      blurb: "Sample a sine too slowly and a phantom lower frequency appears. The Nyquist-Shannon theorem says why — and why every digitizer filters before it samples.", lesson: "learn/foundations/aliasing/" },
    { slug: "pagerank",           topic: "GRAPHS / NETWORKS", title: "PageRank", tone: "blue", status: "LIVE",
      blurb: "Importance flows along links. Power iteration converges to the random surfer's stationary distribution — and the damping factor keeps it well-defined.", lesson: "learn/ml-applications/pagerank/" },
    { slug: "dijkstra",           topic: "GRAPHS / NETWORKS", title: "Dijkstra's Shortest Path", tone: "blue", status: "LIVE",
      blurb: "Grow certainty outward from the source: always settle the closest frontier node and relax its neighbors. Non-negative weights make the greedy choice optimal.", lesson: "learn/interview-capstone/cs-algorithms/" },
    { slug: "mst",                topic: "GRAPHS / NETWORKS", title: "Minimum Spanning Tree", tone: "blue", status: "LIVE",
      blurb: "Connect everything for the least total weight. Prim's greedily adds the cheapest edge crossing out of the growing tree — the cut property says that's always safe.", lesson: "learn/interview-capstone/mst/" },
    { slug: "louvain",            topic: "GRAPHS / NETWORKS", title: "Community Detection", tone: "violet", status: "LIVE",
      blurb: "Find the groups in a network. Greedily move nodes to maximize modularity and the colors merge into communities — until too many cross-edges blur them away.", lesson: "learn/ml-applications/gnn/" },
    { slug: "max-flow",           topic: "GRAPHS / NETWORKS", title: "Max Flow / Min Cut", tone: "blue", status: "LIVE",
      blurb: "Push as much as the network allows from source to sink. Augmenting paths find the maximum flow — and reveal the bottleneck cut that exactly equals it.", lesson: "learn/interview-capstone/max-flow/" },
  ],
  // Display order + the "why it matters / foundations" line per category.
  categories: [
    { name: "Foundations", why: "The optimization, probability, evaluation, and search that sit under every model. Get these in your hands and the rest of ML stops looking like magic — it's gradient descent, generalization, the Gaussian, thresholds, and informed search, all the way down.", slugs: ["gradient-descent", "newton-vs-gradient", "coordinate-descent", "ista", "l-bfgs", "backprop", "overfitting", "double-descent", "bias-variance-decomp", "roc", "clt", "bayes", "mcmc", "importance-sampling", "reservoir-sampling", "count-min-sketch", "bloom-filter", "cross-validation", "kalman-filter", "hmm-viterbi", "simpsons-paradox", "do-intervention", "instrumental-variables", "pathfinding", "simulated-annealing"] },
    { name: "Tensors & Numerics", why: "How arrays and numbers actually behave underneath the model - the shape rules every vectorised line depends on, what a matrix does to space, and where floating point stops telling the truth. Module 01 material: unglamorous, and the source of a large share of real bugs.", slugs: ["broadcasting"] },
    { name: "Information Theory", why: "The mathematics of information itself: how much a signal carries, how much survives noise, and how few bits can store it. Entropy is the common currency - it sets the limit on compression, bounds reliable communication, and is exactly the cross-entropy loss a model is trained to minimize.", slugs: ["mutual-information", "channel-capacity", "huffman-coding", "cross-entropy"] },
    { name: "Evaluation & Robustness", why: "How you know whether a model is actually good - and whether it holds up. Reading the confusion matrix beyond accuracy, picking the metric that matches the cost of each error, and stress-testing predictions against adversarial perturbations and distribution shift. The difference between a leaderboard number and a model you'd deploy.", slugs: ["classification-metrics", "adversarial-examples", "certified-robustness"] },
    { name: "Probabilistic & Bayesian", why: "Reasoning about what you don't know. Instead of one best guess, carry a whole distribution over the answer, update it as evidence arrives, and let calibrated uncertainty drive the next decision. The toolkit behind A/B tests, Bayesian optimization, and trustworthy predictions.", slugs: ["bayesian-linear-regression", "conjugate-updating", "variational-inference", "thompson-vs-ucb", "bayesian-optimization"] },
    { name: "Classical Machine Learning", why: "Interpretable algorithms that still win on tabular data — and that build the geometric intuition (distance, splits, clusters, margins, projections, mixtures) deep learning quietly assumes you already have.", slugs: ["regression", "kmeans", "decision-tree", "bagging-boosting", "knn", "svm", "naive-bayes", "gaussian-process", "pca", "tsne", "isomap", "gmm", "dbscan", "hierarchical-clustering", "spectral-clustering", "label-propagation", "kernel-density"] },
    { name: "Neural Networks", why: "Where deep learning begins: how a network bends space to separate classes, why the choice of nonlinearity decides whether it trains, how convolution turns raw pixels into features, how optimizers actually move through a loss landscape, and how detectors turn those features into boxes.", slugs: ["perceptron", "neural-playground", "activations", "batch-norm", "weight-init", "contrastive-learning", "optimizers", "convolution", "edge-detection", "hough-transform", "harris-corners", "ransac", "bilateral-filter", "image-pyramids", "receptive-field", "integral-image", "grad-cam", "sift", "optical-flow", "hog", "image-augmentation", "morphological-ops", "template-matching", "histogram-equalization", "watershed", "nms", "rnn-gates", "gnn"] },
    { name: "Transformers & NLP", why: "The path from counting which word follows which to the scaled dot-product attention behind every modern LLM — tokenization, embeddings, position, attention itself, how you sample the output, and how retrieval grounds it.", slugs: ["tokenizer", "markov", "decoding", "beam-search", "embeddings", "word2vec", "vector-search", "attention", "multi-head-attention", "attention-rollout", "positional-encoding", "rope", "kv-cache"] },
    { name: "Training & Scaling", why: "How large models actually get trained, adapted, and scaled — the practical engineering behind the headline results: the learning-rate schedules that keep training stable, the low-rank tricks that make fine-tuning cheap, and the scaling laws that decide how to spend compute.", slugs: ["lr-schedule", "gradient-clipping", "lora", "scaling-laws"] },
    { name: "Reinforcement Learning", why: "Learning from delayed reward instead of labels, the explore-vs-exploit tradeoff, the Bellman backups that plan optimal behavior, and the tree search that scales planning to large games — the foundations of agents that act, not just predict.", slugs: ["gridworld-rl", "value-iteration", "bandit", "mcts", "policy-gradient", "actor-critic", "dqn", "reward-model", "dpo", "sarsa-vs-qlearning", "td-lambda", "ppo", "dyna-q", "double-q-learning", "gae", "prioritized-replay", "distributional-rl", "successor-representation", "max-entropy-rl"] },
    { name: "Game Theory & Multi-Agent", why: "When the environment is other strategic agents, not fixed data. How equilibria arise from simple learning rules, how populations of strategies evolve, and how cooperation can emerge from repetition - the foundations of multi-agent systems, mechanism design, and competitive training like GANs and self-play.", slugs: ["regret-matching", "replicator-dynamics", "pd-tournament"] },
    { name: "Generative & Signal", why: "Creating new data rather than labeling it, plus the frequency-domain and sequence views that underpin audio, images, forecasting, and the diffusion models reshaping generative AI.", slugs: ["diffusion", "vae", "gan", "fourier", "ica", "forecasting"] },
    { name: "Agents & LLM Systems", why: "What it takes to turn a raw model into a reliable system: grounding answers in retrieved context, the reliability patterns — sampling-and-voting, verification — that make stochastic models dependable, and the decoding constraints that guarantee structured output. The engineering layer on top of the weights.", slugs: ["rag-chunking", "hyde", "multi-query", "rag-reranker", "lost-in-the-middle", "react-agent", "agent-router", "self-consistency", "reflection", "constrained-decoding", "guardrails", "prompt-injection", "semantic-caching", "kv-cache-eviction", "mixture-of-depths", "context-extension"] },
    { name: "Trustworthy & Explainable ML", why: "Whether you can actually trust what a model outputs: are its confidence scores honest, and can you explain why it decided what it did? The layer that turns a black-box predictor into something you'd deploy where the stakes are real.", slugs: ["calibration", "shap", "saliency", "conformal", "conformal-regression", "mc-dropout", "active-learning", "coreset", "dataset-distillation", "label-noise", "drift-detection", "fairness"] },
    { name: "Interpretability", why: "Prying open the black box. Neural nets pack more concepts than neurons (superposition), so understanding them means recovering the real features, testing what each layer encodes, and intervening to see what the network actually uses. The mechanistic-interpretability toolkit that turns opaque activations into something you can read and audit.", slugs: ["superposition", "sparse-autoencoder", "probing-classifier", "activation-patching"] },
    { name: "Search & Constraint Solving", why: "The classic computer-science core under so much of AI: systematically searching enormous discrete spaces, and using constraints to prune them. Complete methods that guarantee a solution if one exists — the counterpoint to the gradient-based learning everywhere else here.", slugs: ["bfs-dfs-astar", "n-queens", "graph-coloring", "sudoku", "knapsack", "branch-and-bound", "edit-distance"] },
    { name: "Efficiency & Systems", why: "Trained models are huge; this is how you make them cheap enough to actually ship — shrinking the bits, the weights, and the compute without giving back the accuracy. The engineering that turns a research checkpoint into something that runs on your hardware.", slugs: ["quantization", "pruning", "distillation", "moe", "mixed-precision", "speculative-decoding", "paged-attention"] },
    { name: "MLOps & Serving", why: "What happens after training: keeping a model fast, cheap, and reliable under real traffic. The queueing and batching that trade latency for throughput, the routing that spends compute only where it's needed, and the rollout discipline that ships a new model without taking the service down.", slugs: ["batching", "model-cascade", "autoscaling", "canary-rollout"] },
    { name: "Audio & Signal", why: "How a continuous waveform becomes something a model can learn from: the time-frequency views that turn sound into an image, the features that compress it, and the sampling and alignment subtleties that bite if you ignore them. The front end of every speech and audio system.", slugs: ["spectrogram", "mfcc", "pitch-detection", "dtw", "aliasing"] },
    { name: "Graphs & Networks", why: "The algorithms for data shaped like a network — webs, maps, social graphs, dependencies. Ranking nodes by who points at them, finding shortest routes and cheapest spanning structures, carving out communities, and pushing maximum flow through a capacitated network. The classical backbone under graph ML.", slugs: ["pagerank", "dijkstra", "mst", "louvain", "max-flow"] },
  ],
  // The single concept each demo rests on — shown as a "foundation" tag.
  foundations: {
    "pathfinding": "informed search · f = g + h",
    "kmeans": "Lloyd's algorithm",
    "gradient-descent": "following the gradient",
    "newton-vs-gradient": "curvature: the Hessian",
    "coordinate-descent": "one variable at a time",
    "ista": "soft-threshold prox - L1 sparsity",
    "l-bfgs": "curvature from a gradient memory",
    "bayesian-linear-regression": "posterior over functions",
    "variational-inference": "maximize the ELBO",
    "thompson-vs-ucb": "explore via uncertainty",
    "conjugate-updating": "prior x likelihood -> posterior",
    "bayesian-optimization": "GP surrogate + acquisition",
    "sparse-autoencoder": "features from superposition",
    "probing-classifier": "what each layer encodes",
    "activation-patching": "causal localization by intervention",
    "superposition": "more features than dimensions",
    "regret-matching": "no-regret learning -> Nash",
    "replicator-dynamics": "evolutionary game dynamics",
    "pd-tournament": "cooperation from repetition",
    "mutual-information": "dependence beyond correlation",
    "channel-capacity": "the limit on reliable comms",
    "huffman-coding": "entropy = compression limit",
    "classification-metrics": "beyond accuracy: P/R/F1",
    "adversarial-examples": "tiny nudge, wrong answer",
    "certified-robustness": "a provable safety radius",
    "morphological-ops": "erode / dilate / open / close",
    "template-matching": "find a patch by correlation",
    "histogram-equalization": "spread tones via the CDF",
    "overfitting": "the bias-variance tradeoff",
    "cross-validation": "held-out folds pick the model",
    "double-descent": "error peaks then falls past interpolation",
    "bias-variance-decomp": "split error: bias² + variance + noise",
    "clt": "the √n law",
    "decision-tree": "recursive Gini splits",
    "bagging-boosting": "average to cut variance, stack to cut bias",
    "gaussian-process": "distribution over functions + uncertainty",
    "tsne": "preserve neighbors from high-D to 2D",
    "isomap": "unroll by geodesic distance",
    "spectral-clustering": "cluster the graph Laplacian's eigenvectors",
    "label-propagation": "a few labels spread through the graph",
    "knn": "distance-weighted voting",
    "naive-bayes": "Bayes rule + feature independence",
    "svm": "max-margin + the kernel trick",
    "pca": "covariance eigenvectors",
    "gmm": "EM soft clustering",
    "roc": "threshold, ROC & PR",
    "value-iteration": "the Bellman optimality backup",
    "lr-schedule": "warmup & decay",
    "gradient-clipping": "cap the gradient norm at a cliff",
    "lora": "the low-rank update ΔW = BA",
    "scaling-laws": "power laws & compute-optimal",
    "nms": "IoU & greedy suppression",
    "vector-search": "k-NN retrieval (cosine vs L2)",
    "forecasting": "level, trend & seasonality",
    "multi-head-attention": "parallel attention heads",
    "vae": "reparameterization + KL",
    "decoding": "temperature, top-k, top-p sampling",
    "attention": "scaled dot-product attention",
    "positional-encoding": "sinusoidal & rotary position",
    "tokenizer": "byte-pair encoding",
    "markov": "the n-gram next-token model",
    "embeddings": "vector semantics",
    "word2vec": "skip-gram learns vectors from context",
    "gridworld-rl": "the Bellman update",
    "bandit": "explore vs exploit",
    "perceptron": "mistake-driven linear learning",
    "neural-playground": "backpropagation",
    "activations": "nonlinearity & gradients",
    "batch-norm": "re-standardize activations per layer",
    "weight-init": "scale weights to preserve variance",
    "contrastive-learning": "pull positives, push negatives",
    "convolution": "the convolution kernel",
    "edge-detection": "Canny: gradient, thin, threshold, link",
    "hough-transform": "edge points vote; lines = peaks",
    "harris-corners": "structure tensor: both eigenvalues large",
    "ransac": "consensus over least squares: ignore what disagrees",
    "bilateral-filter": "range weight: close in space AND in value",
    "image-pyramids": "blur before you drop, or the detail lies",
    "receptive-field": "theoretical reach vs the part that matters",
    "integral-image": "four reads, any rectangle, any size",
    "grad-cam": "where it looked - and whether that is about the model",
    "sift": "which step buys scale, and which buys rotation",
    "optical-flow": "brightness constancy + LK least squares",
    "hog": "per-cell orientation histograms",
    "image-augmentation": "label-preserving random transforms",
    "watershed": "flood the distance map from markers",
    "batching": "amortize overhead; trade latency for throughput",
    "model-cascade": "cheap model first; escalate the unsure",
    "autoscaling": "replicas chase load; mind the cold start",
    "canary-rollout": "test on a sliver; guard then widen",
    "diffusion": "denoising (score / DDIM)",
    "fourier": "a sum of sines",
    "ica": "unmix by maximizing non-Gaussianity",
    "bayes": "conjugate prior × likelihood → posterior",
    "mcmc": "sample by random walk; proportional to density",
    "importance-sampling": "reweight a proposal by p/q",
    "reservoir-sampling": "uniform sample of a stream in one pass",
    "count-min-sketch": "hashed counters; query the min",
    "bloom-filter": "k hashes; no false negatives",
    "kalman-filter": "predict then update; optimal denoising",
    "hmm-viterbi": "DP for the best hidden path",
    "optimizers": "SGD · Momentum · RMSProp · Adam",
    "gan": "generator vs discriminator (BCE)",
    "backprop": "the chain rule on a computation graph",
    "mcts": "UCB tree search + rollouts",
    "simulated-annealing": "Metropolis acceptance + cooling",
    "regression": "least squares & cross-entropy",
    "rnn-gates": "gated recurrent memory",
    "beam-search": "log-probability tree search",
    "kv-cache": "reuse the prefix's K & V",
    "gnn": "neighborhood message passing",
    "rope": "rotate-by-position, score by relative",
    "dbscan": "density reachability + noise",
    "hierarchical-clustering": "merge into a dendrogram, cut for k",
    "kernel-density": "sum of kernels; bandwidth = bias/variance",
    "policy-gradient": "log-prob × reward",
    "actor-critic": "TD error trains actor + critic",
    "dqn": "replay + target net stabilize Q",
    "reward-model": "Bradley-Terry from preferences",
    "dpo": "implicit reward = β·log(π/π_ref)",
    "sarsa-vs-qlearning": "on-policy vs off-policy TD control",
    "td-lambda": "eligibility traces, TD(0) to Monte Carlo",
    "ppo": "clipped surrogate trust region",
    "dyna-q": "learn a model, plan inside it",
    "double-q-learning": "two estimators cancel max bias",
    "gae": "λ trades bias vs variance in advantages",
    "prioritized-replay": "sample transitions by TD error",
    "distributional-rl": "learn the return distribution, not its mean",
    "successor-representation": "V = M·R, dynamics split from reward",
    "max-entropy-rl": "reward + entropy; soft Bellman, SAC",
    "spectrogram": "STFT time-frequency image",
    "mfcc": "mel filterbank + log + DCT features",
    "pitch-detection": "autocorrelation peak = fundamental",
    "dtw": "elastic alignment of two series",
    "aliasing": "sample below Nyquist, get a phantom freq",
    "pagerank": "importance from the link structure",
    "dijkstra": "settle nearest, relax neighbors",
    "mst": "cheapest edges that connect everything",
    "louvain": "maximize modularity to find communities",
    "max-flow": "augmenting paths; max flow = min cut",
    "rag-chunking": "chunk → retrieve → ground",
    "self-consistency": "sample N → majority vote",
    "constrained-decoding": "mask invalid tokens per step",
    "guardrails": "layered input/output checks",
    "prompt-injection": "untrusted text overriding instructions",
    "semantic-caching": "embedding-similarity response cache",
    "kv-cache-eviction": "drop past tokens to bound the cache",
    "mixture-of-depths": "per-token dynamic compute under capacity",
    "context-extension": "rescale RoPE to run past train length",
    "lost-in-the-middle": "U-shaped context position bias",
    "hyde": "embed a drafted answer, not the query",
    "reflection": "draft → critique → revise loop",
    "react-agent": "thought → action → observation",
    "multi-query": "query variants + reciprocal-rank fusion",
    "rag-reranker": "cross-encoder reorders the shortlist",
    "agent-router": "score tools, route or fall back",
    "attention-rollout": "compose attention across layers",
    "calibration": "reliability diagram + temperature",
    "shap": "Shapley values over feature coalitions",
    "conformal": "calibrated sets with coverage guarantee",
    "conformal-regression": "prediction intervals with coverage guarantee",
    "active-learning": "label the most uncertain points",
    "coreset": "tiny weighted subset preserves the model",
    "dataset-distillation": "learn synthetic points that teach",
    "fairness": "group metrics & the threshold tradeoff",
    "label-noise": "memorizing flipped labels",
    "mc-dropout": "sample dropout masks for uncertainty",
    "saliency": "input-gradient attribution map",
    "drift-detection": "PSI alarm on covariate shift",
    "n-queens": "backtracking + forward checking",
    "graph-coloring": "backtracking + AC-3 propagation",
    "sudoku": "backtracking + naked singles",
    "quantization": "round to a b-bit grid",
    "pruning": "zero small weights, keep accuracy",
    "distillation": "match the teacher's soft labels",
    "moe": "route tokens to top-k experts",
    "mixed-precision": "loss scaling into fp16's range",
    "speculative-decoding": "draft proposes, target verifies",
    "paged-attention": "KV cache in on-demand blocks",
    "simpsons-paradox": "confounding reverses the trend",
    "do-intervention": "observe vs do(); backdoor adjust",
    "instrumental-variables": "2SLS via an instrument; recover β",
    "knapsack": "fill the table, backtrack the choice",
    "branch-and-bound": "prune subtrees with an optimistic bound",
    "bfs-dfs-astar": "uninformed vs informed search",
    "edit-distance": "string alignment DP",
  },
  findDemo(slug) { return this.demos.find(d => d.slug === slug); },
};
