// sub-lessons.js — per-concept sub-lessons that break each ML-from-scratch module
// down into the concepts it teaches. Each module page (module-app.jsx) renders its
// concept sequence as a "Concept by concept" syllabus; each concept gets its own
// taught lesson page at learn/<module>/<concept>/ (concept-lesson-app.jsx).
//
// This is the TAUGHT companion to the reference /concepts/<id>/ hub pages: intuition
// -> the math (KaTeX) -> a small code illustration -> takeaways -> a live demo to play
// with. Data-driven like lectures.js / paths.js. Pages are generated by
// _private/scripts/gen-sublesson-pages.mjs (re-run when you add a module/lesson).
//
// SHAPE
//   SUB_LESSONS[<moduleSlug>] = {
//     title, intro, order: [<conceptId>...],
//     lessons: { <conceptId>: {
//       title, oneLine,
//       sections: [{ h, paras?:[..], tex?, texNote?, code?, caption? }],
//       takeaways: [..], demo?: <visualizeSlug>
//     } }
//   }
// A lesson's concept id resolves to its /concepts/<id>/ hub page automatically.

window.SUB_LESSONS = {
  transformers: {
    title: "Transformers",
    intro: "The architecture behind modern language models, built one idea at a time: turn text into tokens, tokens into vectors, give them a sense of order, let them attend to each other, stack that into a block, and decode the result back into text.",
    order: ["tokenization", "embeddings", "positional-encoding", "attention", "multi-head", "transformer-block", "decoding"],
    lessons: {
      tokenization: {
        title: "Tokenization",
        oneLine: "Turn raw text into the discrete tokens a model actually consumes.",
        sections: [
          { h: "The intuition", paras: [
            "A language model never sees characters or words — it sees a sequence of integer token ids drawn from a fixed vocabulary. Tokenization is the step that converts a string into that sequence, and back.",
            "Word-level vocabularies explode and choke on typos and rare words; character-level keeps the vocabulary tiny but makes sequences painfully long. Subword tokenization (BPE, WordPiece, Unigram) is the compromise everyone uses: common words stay whole, rare ones split into reusable pieces, and nothing is ever out-of-vocabulary.",
          ] },
          { h: "The math", paras: [
            "Byte-Pair Encoding learns its vocabulary greedily. Start from single characters, then repeatedly merge the adjacent pair with the highest frequency across the corpus until you hit the target vocabulary size:",
          ], tex: "(a,b)^\\star = \\arg\\max_{(a,b)}\\; \\mathrm{count}(a,b)", texNote: "Each chosen pair becomes a new token; the merge list, applied in order, is the tokenizer." },
          { h: "In code", code: "from collections import Counter\n\n# greedy BPE merge step over a corpus of symbol-lists\ndef best_pair(corpus):\n    pairs = Counter()\n    for word in corpus:                # word = ['l','o','w','</w>']\n        for a, b in zip(word, word[1:]):\n            pairs[(a, b)] += 1\n    return pairs.most_common(1)[0][0]  # the pair to merge next\n\ndef merge(corpus, pair):\n    a, b = pair\n    return [_join(word, a, b) for word in corpus]", caption: "Run best_pair -> merge in a loop until the vocabulary reaches the size you want." },
        ],
        takeaways: [
          "Models operate on token ids, not text — tokenization defines what a 'unit' even is.",
          "Subword tokenizers trade vocabulary size against sequence length and eliminate out-of-vocabulary words.",
          "BPE is just: merge the most frequent adjacent pair, repeat.",
        ],
        demo: "tokenizer",
      },
      embeddings: {
        title: "Embeddings",
        oneLine: "Map each token id to a dense vector whose geometry carries meaning.",
        sections: [
          { h: "The intuition", paras: [
            "A token id is just an index — id 4017 means nothing on its own. An embedding layer is a learned lookup table that turns each id into a vector of real numbers, and training shapes that table so related tokens land near each other.",
            "Once tokens are vectors, 'meaning' becomes geometry: similarity is a dot product, analogies are directions, and every later layer gets to do linear algebra instead of string matching.",
          ] },
          { h: "The math", paras: [
            "The embedding matrix is E in R^(V x d) for vocabulary size V and model width d. Looking up token i is just selecting a row:",
          ], tex: "e_i = E_{i,:} \\in \\mathbb{R}^{d}", texNote: "E is a parameter — it is learned by gradient descent like any other weight." },
          { h: "In code", code: "import numpy as np\n\nV, d = 50000, 256\nE = np.random.randn(V, d) * 0.02      # learned embedding table\n\nids = np.array([101, 4017, 2009])     # a tokenized sentence\nx = E[ids]                            # (3, d) — one vector per token\n\n# similarity between two tokens is a dot product\ncos = E[4017] @ E[2009] / (np.linalg.norm(E[4017]) * np.linalg.norm(E[2009]))", caption: "The whole layer is a row-select; the magic is in what training writes into E." },
        ],
        takeaways: [
          "Embeddings convert discrete ids into a continuous space where similarity is measurable.",
          "The table is learned, so structure (synonyms, analogies) emerges from the training objective.",
          "Every downstream layer benefits — they all operate on vectors, never on tokens.",
        ],
        demo: "embeddings",
      },
      "positional-encoding": {
        title: "Positional Encoding",
        oneLine: "Inject order into a model that otherwise treats its input as a set.",
        sections: [
          { h: "The intuition", paras: [
            "Attention has no built-in notion of order — shuffle the tokens and the raw computation is unchanged. But language is sequential: 'dog bites man' is not 'man bites dog'. Positional encodings add a position-dependent signal to each token vector so the model can tell where each token sits.",
            "The classic transformer uses fixed sinusoids of geometrically increasing wavelength. Because sines and cosines combine linearly, the model can represent relative offsets — a useful inductive bias that also extends to lengths never seen in training.",
          ] },
          { h: "The math", paras: [
            "For position pos and dimension i, the encoding interleaves sine and cosine across a spectrum of frequencies:",
          ], tex: "PE_{(pos,2i)} = \\sin\\!\\Big(\\tfrac{pos}{10000^{2i/d}}\\Big),\\quad PE_{(pos,2i+1)} = \\cos\\!\\Big(\\tfrac{pos}{10000^{2i/d}}\\Big)", texNote: "Added to the token embedding before the first attention layer." },
          { h: "In code", code: "import numpy as np\n\ndef positional_encoding(seq_len, d):\n    pos = np.arange(seq_len)[:, None]\n    i = np.arange(d)[None, :]\n    angle = pos / np.power(10000, (2 * (i // 2)) / d)\n    pe = np.where(i % 2 == 0, np.sin(angle), np.cos(angle))\n    return pe                          # (seq_len, d), add to embeddings", caption: "Different dimensions oscillate at different rates — a positional fingerprint." },
        ],
        takeaways: [
          "Self-attention is permutation-invariant; position must be added explicitly.",
          "Sinusoidal encodings let the model reason about relative position and generalize past trained lengths.",
          "Modern variants (RoPE, ALiBi) encode position inside attention instead of adding it up front.",
        ],
        demo: "positional-encoding",
      },
      attention: {
        title: "Attention",
        oneLine: "Weight every token by how relevant it is to the one you are computing.",
        sections: [
          { h: "The intuition", paras: [
            "Attention lets each token pull in information from every other token, weighted by relevance. Each token emits a query (what am I looking for?), a key (what do I offer?), and a value (what I'll pass along). A token's output is a relevance-weighted average of everyone's values.",
            "This is the operation that replaced recurrence: instead of passing a state step by step, every token talks to every other token in one parallel step.",
          ] },
          { h: "The math", paras: [
            "Scaled dot-product attention scores each query against every key, softmax-normalizes the scores into weights, and mixes the values. The 1/sqrt(d_k) keeps the dot products from saturating the softmax:",
          ], tex: "\\mathrm{Attention}(Q,K,V) = \\mathrm{softmax}\\!\\Big(\\tfrac{QK^{\\top}}{\\sqrt{d_k}}\\Big)V", texNote: "Q, K, V are linear projections of the input. See the full derivation in the on-site Self-Attention lesson." },
          { h: "In code", code: "import numpy as np\n\ndef attention(Q, K, V):\n    dk = Q.shape[-1]\n    scores = Q @ K.T / np.sqrt(dk)     # (n, n) relevance\n    scores -= scores.max(-1, keepdims=True)\n    w = np.exp(scores)\n    w /= w.sum(-1, keepdims=True)      # softmax over keys\n    return w @ V                       # weighted mix of values", caption: "Three matmuls and a softmax — the core of every transformer." },
        ],
        takeaways: [
          "Attention is a content-based, weighted average of values — no recurrence required.",
          "Queries and keys decide the weights; values carry the information.",
          "The sqrt(d_k) scaling keeps gradients healthy as the dimension grows.",
        ],
        demo: "attention",
      },
      "multi-head": {
        title: "Multi-Head Attention",
        oneLine: "Run several attention patterns in parallel, then combine them.",
        sections: [
          { h: "The intuition", paras: [
            "One attention map forces every token to mix information in a single way. Real language needs several relationships at once — syntactic agreement, coreference, local phrasing. Multi-head attention splits the model width into h smaller subspaces, runs attention independently in each, and concatenates the results.",
            "Each head is cheap (it works in d/h dimensions), and together they let the layer attend to different things in different subspaces simultaneously.",
          ] },
          { h: "The math", paras: [
            "Each head projects Q, K, V into its own subspace, attends there, and the outputs are concatenated and mixed by a final projection W^O:",
          ], tex: "\\mathrm{MultiHead}(X) = \\mathrm{Concat}(\\mathrm{head}_1,\\dots,\\mathrm{head}_h)\\,W^{O}", texNote: "head_i = Attention(XW_i^Q, XW_i^K, XW_i^V); the heads run fully in parallel." },
          { h: "In code", code: "import numpy as np\n\ndef multi_head(X, Wq, Wk, Wv, Wo, h):\n    n, d = X.shape\n    dk = d // h\n    outs = []\n    for i in range(h):                 # each head sees a d/h slice\n        sl = slice(i * dk, (i + 1) * dk)\n        outs.append(attention(X @ Wq[:, sl], X @ Wk[:, sl], X @ Wv[:, sl]))\n    return np.concatenate(outs, axis=-1) @ Wo", caption: "Heads are independent; the final W^O lets them interact." },
        ],
        takeaways: [
          "Multiple heads capture multiple relationships in parallel subspaces.",
          "Splitting the width keeps the total cost the same as single-head attention.",
          "The output projection W^O lets the heads' results recombine.",
        ],
        demo: "multi-head-attention",
      },
      "transformer-block": {
        title: "The Transformer Block",
        oneLine: "Stack attention and an MLP with residuals and normalization into one repeatable unit.",
        sections: [
          { h: "The intuition", paras: [
            "A transformer is just the same block stacked many times. Each block does two things: mix information across tokens (attention), then transform each token on its own (a small MLP). Residual connections let signal and gradients flow straight through, and layer normalization keeps the activations well-scaled at every depth.",
            "This residual-and-norm sandwich is what makes very deep stacks trainable at all.",
          ] },
          { h: "The math", paras: [
            "With pre-norm placement, each sub-layer reads a normalized input and adds its result back to the residual stream:",
          ], tex: "\\begin{aligned} x &\\leftarrow x + \\mathrm{MHA}(\\mathrm{LN}(x)) \\\\ x &\\leftarrow x + \\mathrm{MLP}(\\mathrm{LN}(x)) \\end{aligned}", texNote: "The MLP is two linear layers with a nonlinearity, applied to each token independently." },
          { h: "In code", code: "def transformer_block(x, attn, mlp, ln1, ln2):\n    x = x + attn(ln1(x))               # mix across tokens\n    x = x + mlp(ln2(x))                # transform each token\n    return x\n\n# a stack is just this block, repeated\ndef transformer(x, blocks):\n    for blk in blocks:\n        x = blk(x)\n    return x", caption: "Residual + norm around two sub-layers — repeat N times." },
        ],
        takeaways: [
          "A transformer is one block (attention + MLP) stacked with residuals and normalization.",
          "Residual connections keep gradients flowing through deep stacks.",
          "Attention mixes tokens; the MLP processes each token independently.",
        ],
        demo: "multi-head-attention",
      },
      decoding: {
        title: "Decoding",
        oneLine: "Turn the model's next-token distribution into actual generated text.",
        sections: [
          { h: "The intuition", paras: [
            "A language model outputs a probability distribution over the next token. Decoding is the policy that picks one — and that choice shapes everything about the output. Always taking the argmax (greedy) is fluent but repetitive; sampling adds variety but can wander.",
            "Temperature sharpens or flattens the distribution; top-k and top-p (nucleus) clip the long tail so you sample only from plausible tokens; beam search keeps several candidate continuations at once.",
          ] },
          { h: "The math", paras: [
            "Temperature T rescales the logits before the softmax — low T concentrates probability on the top tokens, high T spreads it out:",
          ], tex: "p_i = \\frac{\\exp(z_i / T)}{\\sum_j \\exp(z_j / T)}", texNote: "T -> 0 recovers greedy argmax; T = 1 is the model's raw distribution." },
          { h: "In code", code: "import numpy as np\n\ndef sample(logits, T=1.0, top_p=0.9):\n    z = logits / T\n    p = np.exp(z - z.max()); p /= p.sum()\n    order = np.argsort(p)[::-1]                 # nucleus: keep smallest\n    keep = order[np.cumsum(p[order]) <= top_p]  # set with mass >= top_p\n    if len(keep) == 0: keep = order[:1]\n    p2 = p[keep] / p[keep].sum()\n    return np.random.choice(keep, p=p2)", caption: "Temperature reshapes the distribution; top-p trims the tail before sampling." },
        ],
        takeaways: [
          "Decoding is a separate policy on top of the model's distribution — it controls the style of the output.",
          "Temperature trades determinism for diversity; top-k / top-p remove implausible tokens.",
          "Greedy is just temperature -> 0; beam search searches several continuations at once.",
        ],
        demo: "decoding",
      },
    },
  },
  foundations: {
    title: "Mathematical and Programming Foundations",
    intro: "The handful of mathematical ideas the rest of the course quietly assumes: how derivatives compose, how a model learns by descending a loss, how to reason about uncertainty, and why averages become bell curves.",
    order: ["chain-rule", "gradient-descent", "bayes", "entropy", "clt"],
    lessons: {
      "chain-rule": {
        title: "The Chain Rule",
        oneLine: "Compose derivatives through a graph - the calculus identity that makes backprop possible.",
        sections: [
          { h: "The intuition", paras: [
            "A neural network is a long composition of functions. To train it you need the derivative of the final loss with respect to every parameter buried inside that composition. The chain rule is the one rule that lets you get there: the sensitivity of an output to a distant input is the product of the local sensitivities along the path between them.",
          ] },
          { h: "The math", paras: ["For a composition L(y(x)), the derivative multiplies the local pieces:"],
            tex: "\\frac{\\partial L}{\\partial x} = \\frac{\\partial L}{\\partial y}\\,\\frac{\\partial y}{\\partial x}", texNote: "Chained across many layers, this product is exactly what backpropagation computes." },
          { h: "In code", code: "# d/dx of L = (y - t)^2 where y = w*x\n# dL/dy = 2(y - t);  dy/dw = x  ->  dL/dw = 2(y - t) * x\ndef grad_w(x, w, t):\n    y = w * x\n    return 2 * (y - t) * x", caption: "Every autograd engine is this rule applied over a graph." },
        ],
        takeaways: ["Gradients of compositions are products of local gradients.", "It is the mathematical engine inside backprop and every autograd library."],
        demo: "backprop",
      },
      "gradient-descent": {
        title: "Gradient Descent",
        oneLine: "Follow the negative gradient downhill to minimize a loss.",
        sections: [
          { h: "The intuition", paras: [
            "Most models are trained by minimizing a loss function you cannot solve in closed form. Gradient descent is the universal fallback: stand on the loss surface, look at the slope, and take a small step in the steepest downhill direction. Repeat until you stop improving.",
          ] },
          { h: "The math", paras: ["Each step moves the parameters against the gradient, scaled by a learning rate eta:"],
            tex: "\\theta_{t+1} = \\theta_t - \\eta\\,\\nabla_\\theta\\,\\mathcal{L}(\\theta_t)", texNote: "Too large an eta overshoots; too small crawls. The learning-rate schedule manages this." },
          { h: "In code", code: "def gradient_descent(grad, theta, eta=0.1, steps=100):\n    for _ in range(steps):\n        theta = theta - eta * grad(theta)\n    return theta", caption: "The same three lines train a line fit or a billion-parameter model." },
        ],
        takeaways: ["Gradient descent turns 'minimize this loss' into a simple iterative rule.", "The learning rate is the single most important knob.", "Adam and friends are gradient descent with adaptive per-parameter steps."],
        demo: "gradient-descent",
      },
      bayes: {
        title: "Bayes' Rule",
        oneLine: "Update what you believe in light of new evidence.",
        sections: [
          { h: "The intuition", paras: [
            "Bayes' rule is how a rational agent revises a belief when data arrives. You start with a prior, see some evidence, and end with a posterior that blends the two - leaning on the prior when data is scarce and on the data when it is plentiful. It underlies Naive Bayes, Kalman filters, and probabilistic modeling generally.",
          ] },
          { h: "The math", paras: ["The posterior is the likelihood times the prior, normalized:"],
            tex: "P(H\\mid E) = \\frac{P(E\\mid H)\\,P(H)}{P(E)}", texNote: "Posterior is proportional to likelihood times prior; the denominator just makes it sum to one." },
          { h: "In code", code: "def posterior(prior, likelihood):\n    # prior, likelihood: dict over hypotheses\n    joint = {h: prior[h] * likelihood[h] for h in prior}\n    z = sum(joint.values())\n    return {h: joint[h] / z for h in joint}", caption: "Multiply prior by likelihood, then normalize." },
        ],
        takeaways: ["Bayes' rule is the calculus of updating beliefs with evidence.", "Priors dominate when data is scarce; data dominates when it is plentiful."],
        demo: "bayes",
      },
      entropy: {
        title: "Entropy and Information",
        oneLine: "Measure how much uncertainty a distribution carries, in bits.",
        sections: [
          { h: "The intuition", paras: [
            "Entropy quantifies surprise. A fair coin is maximally uncertain (1 bit); a loaded one carries less. It is the currency behind decision-tree splits (which question removes the most uncertainty?), cross-entropy loss, and compression.",
          ] },
          { h: "The math", paras: ["Entropy is the expected number of bits to encode an outcome:"],
            tex: "H(p) = -\\sum_i p_i \\log_2 p_i", texNote: "Maximized by the uniform distribution; zero when one outcome is certain." },
          { h: "In code", code: "import numpy as np\n\ndef entropy(p):\n    p = np.asarray(p)\n    p = p[p > 0]\n    return -np.sum(p * np.log2(p))", caption: "A decision tree picks the split that drops this the most." },
        ],
        takeaways: ["Entropy measures uncertainty in bits.", "Information gain (entropy drop) drives decision-tree splits.", "Cross-entropy, the workhorse classification loss, is built from it."],
        demo: "decision-tree",
      },
      clt: {
        title: "The Central Limit Theorem",
        oneLine: "Sums of many independent random draws look Gaussian, whatever the source.",
        sections: [
          { h: "The intuition", paras: [
            "Average enough independent random quantities and the distribution of the average becomes a bell curve - even if each piece is wildly non-Gaussian. This is why noise is so often modeled as Gaussian, why error bars shrink as 1/sqrt(n), and why the normal distribution is everywhere.",
          ] },
          { h: "The math", paras: ["The standardized sample mean converges to a standard normal:"],
            tex: "\\frac{\\bar{X}_n - \\mu}{\\sigma/\\sqrt{n}} \\;\\xrightarrow{d}\\; \\mathcal{N}(0,1)", texNote: "The spread of the mean shrinks like 1/sqrt(n) - quadruple the data to halve the error." },
          { h: "In code", code: "import numpy as np\n\n# means of uniform samples become Gaussian\nmeans = [np.random.rand(50).mean() for _ in range(10000)]\n# histogram of `means` is a tight bell curve around 0.5", caption: "Sum anything independent enough times and a bell curve appears." },
        ],
        takeaways: ["Averages of independent variables tend to a Gaussian.", "Estimation error shrinks like 1/sqrt(n).", "It justifies Gaussian noise assumptions across ML."],
        demo: "clt",
      },
    },
  },

  "supervised-learning": {
    title: "Supervised Learning",
    intro: "The classic classifiers, each built before it is trusted: vote with your neighbors, carve the space with questions, find the widest margin, and score the result honestly.",
    order: ["knn", "decision-tree", "svm", "roc"],
    lessons: {
      knn: {
        title: "k-Nearest Neighbors",
        oneLine: "Classify a point by the majority vote of its closest neighbors.",
        sections: [
          { h: "The intuition", paras: [
            "kNN is the simplest idea that actually works: to label a new point, find the k closest labeled points and let them vote. There is no training - the data is the model. Small k gives a jagged, high-variance boundary; large k smooths it toward the majority class.",
          ] },
          { h: "The math", paras: ["Predict the most common label among the k nearest by some distance d:"],
            tex: "\\hat{y}(x) = \\text{mode}\\,\\{\\, y_i : x_i \\in \\mathcal{N}_k(x) \\,\\}", texNote: "Distance choice and feature scaling matter enormously - standardize first." },
          { h: "In code", code: "import numpy as np\n\ndef knn_predict(X, y, x, k=5):\n    d = np.linalg.norm(X - x, axis=1)\n    nn = np.argsort(d)[:k]\n    return np.bincount(y[nn]).argmax()", caption: "No fit step - prediction does all the work." },
        ],
        takeaways: ["kNN is lazy: it stores the data and votes at query time.", "k trades a jagged boundary (low k) for a smooth one (high k).", "Distances need scaled features to be meaningful."],
        demo: "knn",
      },
      "decision-tree": {
        title: "Decision Trees",
        oneLine: "Carve the feature space with a sequence of axis-aligned questions.",
        sections: [
          { h: "The intuition", paras: [
            "A decision tree asks one yes/no question at a time, splitting the data into ever-purer groups. Each split is chosen to reduce impurity the most. Trees are interpretable and handle mixed feature types, but a deep tree overfits - which is why we average many of them in forests and boosting.",
          ] },
          { h: "The math", paras: ["Each node picks the feature and threshold that most reduce impurity (e.g. Gini):"],
            tex: "G = 1 - \\sum_c p_c^2", texNote: "The split maximizing the weighted impurity drop wins; recurse until pure or capped." },
          { h: "In code", code: "import numpy as np\n\ndef gini(y):\n    _, counts = np.unique(y, return_counts=True)\n    p = counts / counts.sum()\n    return 1 - np.sum(p ** 2)\n# best split = argmin over (feature, threshold) of weighted child gini", caption: "Greedy, recursive, and the building block of forests and boosting." },
        ],
        takeaways: ["Trees split on the question that most purifies the labels.", "They are interpretable but overfit when deep.", "Ensembles (bagging, boosting) turn weak trees into strong models."],
        demo: "decision-tree",
      },
      svm: {
        title: "Support Vector Machines",
        oneLine: "Separate the classes with the widest possible margin.",
        sections: [
          { h: "The intuition", paras: [
            "An SVM does not just find a separating line - it finds the one with the largest buffer between the classes, defined by a few critical points called support vectors. The kernel trick lets the same idea draw curved boundaries by measuring similarity in a richer space without ever building it.",
          ] },
          { h: "The math", paras: ["Maximize the margin, i.e. minimize the weight norm subject to correct, confident classification:"],
            tex: "\\min_{w,b}\\;\\tfrac12\\|w\\|^2 \\quad \\text{s.t.}\\quad y_i(w^{\\top}x_i + b) \\ge 1", texNote: "The soft-margin version adds slack so a few points may violate the margin." },
          { h: "In code", code: "# hinge-loss SVM via subgradient descent\ndef step(w, b, x, y, lr=0.01, C=1.0):\n    if y * (w @ x + b) < 1:\n        w = w - lr * (w - C * y * x); b = b + lr * C * y\n    else:\n        w = w - lr * w\n    return w, b", caption: "Only the margin-violating points (support vectors) drive the update." },
        ],
        takeaways: ["SVMs maximize the margin, set by a few support vectors.", "Kernels give nonlinear boundaries cheaply.", "The C parameter trades margin width against training errors."],
        demo: "svm",
      },
      roc: {
        title: "ROC and Thresholds",
        oneLine: "Score a classifier honestly across every decision threshold.",
        sections: [
          { h: "The intuition", paras: [
            "Accuracy hides the trade-off between catching positives and raising false alarms - and collapses on imbalanced data. The ROC curve sweeps the decision threshold and plots true-positive rate against false-positive rate, and the area under it (AUC) summarizes ranking quality independent of any single threshold.",
          ] },
          { h: "The math", paras: ["The curve plots, over all thresholds t, the two rates:"],
            tex: "\\text{TPR} = \\frac{TP}{TP+FN},\\qquad \\text{FPR} = \\frac{FP}{FP+TN}", texNote: "AUC is the probability a random positive is ranked above a random negative." },
          { h: "In code", code: "import numpy as np\n\ndef roc_points(scores, y):\n    for t in np.sort(scores)[::-1]:\n        pred = scores >= t\n        tpr = (pred & (y == 1)).sum() / max((y == 1).sum(), 1)\n        fpr = (pred & (y == 0)).sum() / max((y == 0).sum(), 1)\n        yield fpr, tpr", caption: "Sweep the threshold, trace the curve, integrate for AUC." },
        ],
        takeaways: ["ROC separates ranking quality from the choice of threshold.", "AUC is threshold-free and robust to class imbalance.", "Pick the operating threshold from the curve, by the cost of each error."],
        demo: "roc",
      },
    },
  },

  "unsupervised-learning": {
    title: "Unsupervised Learning",
    intro: "Finding structure with no labels at all: group points that belong together, and find the directions that carry the information.",
    order: ["kmeans", "gmm-em", "pca"],
    lessons: {
      kmeans: {
        title: "K-Means Clustering",
        oneLine: "Group points around k centers by alternating assignment and update.",
        sections: [
          { h: "The intuition", paras: [
            "K-means partitions data into k groups by repeating two steps: assign each point to its nearest center, then move each center to the mean of its points. It is fast and intuitive but assumes round, similarly sized clusters and needs k chosen up front.",
          ] },
          { h: "The math", paras: ["It minimizes within-cluster squared distance to the centers:"],
            tex: "\\min_{\\{\\mu_k\\}}\\;\\sum_i \\min_k \\|x_i - \\mu_k\\|^2", texNote: "Each iteration cannot increase this objective, so it converges - but to a local optimum." },
          { h: "In code", code: "import numpy as np\n\ndef kmeans_step(X, mu):\n    a = np.argmin(((X[:, None] - mu) ** 2).sum(-1), axis=1)\n    mu = np.array([X[a == k].mean(0) for k in range(len(mu))])\n    return a, mu", caption: "Assign, update, repeat - Lloyd's algorithm." },
        ],
        takeaways: ["K-means alternates nearest-center assignment with mean updates.", "It assumes round clusters and needs k chosen in advance.", "GMMs generalize it to soft, elliptical clusters."],
        demo: "kmeans",
      },
      "gmm-em": {
        title: "Gaussian Mixtures and EM",
        oneLine: "Model data as a blend of Gaussians, fit by soft assignments.",
        sections: [
          { h: "The intuition", paras: [
            "A Gaussian mixture says the data came from several Gaussian blobs with unknown parameters. Expectation-Maximization fits it by alternating: the E-step computes each point's soft membership in every blob; the M-step re-estimates each blob from those weighted points. It is k-means with probabilities and elliptical clusters.",
          ] },
          { h: "The math", paras: ["The E-step responsibility of component k for point i:"],
            tex: "\\gamma_{ik} = \\frac{\\pi_k\\,\\mathcal{N}(x_i\\mid \\mu_k,\\Sigma_k)}{\\sum_j \\pi_j\\,\\mathcal{N}(x_i\\mid \\mu_j,\\Sigma_j)}", texNote: "The M-step updates each mean, covariance, and weight from responsibility-weighted data." },
          { h: "In code", code: "# E-step: soft assignments; M-step: weighted moments\ngamma = (pi * gaussian(X, mu, Sigma))      # (n, k)\ngamma /= gamma.sum(1, keepdims=True)\nNk = gamma.sum(0)\nmu = (gamma.T @ X) / Nk[:, None]           # weighted means", caption: "Soft k-means: every point partly belongs to every cluster." },
        ],
        takeaways: ["GMMs model data as a weighted blend of Gaussians.", "EM alternates soft assignment (E) with re-estimation (M).", "It generalizes k-means to elliptical, overlapping clusters."],
        demo: "gmm",
      },
      pca: {
        title: "Principal Component Analysis",
        oneLine: "Find the orthogonal directions that capture the most variance.",
        sections: [
          { h: "The intuition", paras: [
            "PCA rotates the data to new axes ordered by how much variance they explain, then keeps the top few. It compresses, denoises, and visualizes high-dimensional data by projecting onto the directions that matter most. Those directions are the leading eigenvectors of the covariance matrix.",
          ] },
          { h: "The math", paras: ["The principal directions are the top eigenvectors of the covariance:"],
            tex: "\\Sigma = \\tfrac1n X^{\\top}X = U\\Lambda U^{\\top}", texNote: "Project onto the top-k columns of U; the eigenvalues say how much variance each keeps." },
          { h: "In code", code: "import numpy as np\n\ndef pca(X, k):\n    X = X - X.mean(0)\n    U, S, Vt = np.linalg.svd(X, full_matrices=False)\n    return X @ Vt[:k].T          # top-k projection", caption: "Center, take the SVD, project onto the leading directions." },
        ],
        takeaways: ["PCA keeps the directions of greatest variance.", "It is computed from the covariance eigenvectors (or an SVD).", "Used for compression, denoising, and 2D visualization."],
        demo: "pca",
      },
    },
  },

  "ml-theory": {
    title: "Machine Learning Theory",
    intro: "Why models generalize - or fail to: the bias-variance trade-off, how regularization tames it, how to estimate true performance, and the surprise of double descent.",
    order: ["bias-variance", "regularization", "cross-validation", "double-descent"],
    lessons: {
      "bias-variance": {
        title: "The Bias-Variance Trade-off",
        oneLine: "Generalization error splits into bias, variance, and irreducible noise.",
        sections: [
          { h: "The intuition", paras: [
            "Too simple a model misses the pattern (high bias); too flexible a model chases the noise and changes wildly with the training set (high variance). Test error is the sum of both plus the noise floor, and model selection is the search for their sweet spot.",
          ] },
          { h: "The math", paras: ["Expected squared error decomposes cleanly:"],
            tex: "\\mathbb{E}[(y-\\hat{f})^2] = \\text{Bias}^2 + \\text{Var} + \\sigma^2", texNote: "More capacity lowers bias but raises variance; the irreducible noise sigma^2 cannot be removed." },
          { h: "In code", code: "import numpy as np\n\n# fit many models on resampled data, then:\nbias2 = (preds.mean(0) - truth) ** 2\nvar = preds.var(0)\n# test_err ~ bias2.mean() + var.mean() + noise", caption: "Average predictions give bias; their spread gives variance." },
        ],
        takeaways: ["Error = bias^2 + variance + irreducible noise.", "Capacity trades bias for variance.", "The goal is the minimum-total-error sweet spot, not zero training error."],
        demo: "bias-variance-decomp",
      },
      regularization: {
        title: "Regularization",
        oneLine: "Penalize complexity to trade a little bias for much less variance.",
        sections: [
          { h: "The intuition", paras: [
            "Regularization discourages the model from fitting noise by adding a penalty on the size of its weights. L2 (weight decay) shrinks weights smoothly; L1 drives some to exactly zero, selecting features. Either way you accept slightly more bias for a big drop in variance.",
          ] },
          { h: "The math", paras: ["Add a penalty term to the loss, weighted by lambda:"],
            tex: "\\mathcal{L}_{\\text{reg}} = \\mathcal{L}(\\theta) + \\lambda\\,\\|\\theta\\|_2^2", texNote: "Larger lambda means simpler models; it is tuned on validation data." },
          { h: "In code", code: "# L2 adds a constant pull toward zero to every gradient step\ngrad = data_grad(theta) + 2 * lam * theta\ntheta = theta - eta * grad      # 'weight decay'", caption: "A constant shrink toward the origin each update." },
        ],
        takeaways: ["Regularization penalizes complexity to cut variance.", "L2 shrinks smoothly; L1 induces sparsity.", "lambda is chosen by cross-validation."],
        demo: "overfitting",
      },
      "cross-validation": {
        title: "Cross-Validation",
        oneLine: "Estimate true performance without ever touching the test set.",
        sections: [
          { h: "The intuition", paras: [
            "You cannot judge generalization on the data you trained on, and you must not tune on the test set. k-fold cross-validation rotates: train on k-1 folds, validate on the held-out one, repeat, and average. It gives an honest, low-variance estimate to pick hyperparameters.",
          ] },
          { h: "The math", paras: ["The CV estimate averages the held-out error across folds:"],
            tex: "\\text{CV} = \\frac1k \\sum_{j=1}^{k} \\mathcal{L}\\big(\\text{fold}_j;\\ \\text{model trained without } \\text{fold}_j\\big)", texNote: "More folds means less bias but more compute; k=5 or 10 is standard." },
          { h: "In code", code: "import numpy as np\n\ndef kfold(n, k=5):\n    idx = np.random.permutation(n)\n    return np.array_split(idx, k)   # each chunk is a validation fold", caption: "Rotate the held-out fold; average the scores." },
        ],
        takeaways: ["CV estimates generalization using only training data.", "It is the standard way to choose hyperparameters.", "Keep a final untouched test set for the last, honest number."],
        demo: "cross-validation",
      },
      "double-descent": {
        title: "Double Descent",
        oneLine: "Past the interpolation threshold, more parameters can help again.",
        sections: [
          { h: "The intuition", paras: [
            "Classical theory says test error is U-shaped in model size. Modern overparameterized models show a second descent: error rises to a peak right where the model can exactly fit the training data, then falls again as you add even more capacity. It is why huge networks generalize despite zero training error.",
          ] },
          { h: "The math", paras: ["Error peaks near the interpolation threshold where parameters P match samples N:"],
            tex: "P \\approx N \\;\\Rightarrow\\; \\text{test error peaks, then descends again}", texNote: "Implicit regularization from SGD picks low-norm solutions in the overparameterized regime." },
          { h: "In code", code: "# sweep model width and record test error\nfor width in widths:\n    model = fit(width)\n    err.append(test_error(model))\n# err first dips, spikes near width ~ n_samples, then dips again", caption: "The second dip is the modern, overparameterized regime." },
        ],
        takeaways: ["Test error can be double-descent shaped, not just U-shaped.", "The peak sits at the interpolation threshold (params ~ samples).", "Overparameterization plus SGD's implicit bias explains big-model success."],
        demo: "double-descent",
      },
    },
  },

  "neural-nets": {
    title: "Neural Networks from Scratch",
    intro: "The deep-learning core: stack linear maps and nonlinearities into a network, get gradients with backprop, keep training stable with the right activations, initialization, normalization, and optimizer.",
    order: ["mlp", "backprop", "activations", "optimizers", "batch-norm", "weight-init"],
    lessons: {
      mlp: {
        title: "The Multilayer Perceptron",
        oneLine: "Stack linear layers and nonlinearities into a universal function approximator.",
        sections: [
          { h: "The intuition", paras: [
            "A multilayer perceptron alternates two operations: a linear map (weights and a bias) and a per-neuron nonlinearity. Without the nonlinearity, stacking layers collapses to a single linear map; with it, a wide-enough network can approximate any continuous function.",
          ] },
          { h: "The math", paras: ["Each layer applies a weight matrix, a bias, and an activation:"],
            tex: "h^{(l)} = \\sigma\\!\\big(W^{(l)} h^{(l-1)} + b^{(l)}\\big)", texNote: "Depth composes simple features into complex ones; the nonlinearity is what makes depth matter." },
          { h: "In code", code: "import numpy as np\n\ndef mlp(x, layers):\n    for W, b in layers[:-1]:\n        x = np.maximum(0, W @ x + b)   # ReLU\n    W, b = layers[-1]\n    return W @ x + b                   # linear head", caption: "Linear, nonlinear, repeat - then a final linear head." },
        ],
        takeaways: ["An MLP is alternating linear maps and nonlinearities.", "The nonlinearity is what makes depth more than one big linear layer.", "Wide enough, it can approximate any continuous function."],
        demo: "neural-playground",
      },
      backprop: {
        title: "Backpropagation",
        oneLine: "Get the gradient for every parameter in one backward pass.",
        sections: [
          { h: "The intuition", paras: [
            "Backprop is the chain rule run efficiently over the whole network. A forward pass computes the output and caches intermediate values; a backward pass sends the error signal from the loss back through each layer, accumulating the gradient of the loss with respect to every weight in a single sweep.",
          ] },
          { h: "The math", paras: ["The error signal at a layer propagates through the local Jacobian:"],
            tex: "\\delta^{(l)} = \\big(W^{(l+1)\\top}\\delta^{(l+1)}\\big)\\odot\\sigma'\\!\\big(z^{(l)}\\big)", texNote: "Then the weight gradient is delta times the layer's input - reuse, not recompute." },
          { h: "In code", code: "# backward through one ReLU layer\ndZ = dA * (Z > 0)            # gradient through ReLU\ndW = dZ @ A_prev.T           # weight gradient\ndA_prev = W.T @ dZ           # pass the signal down", caption: "One backward sweep yields every gradient at once." },
        ],
        takeaways: ["Backprop is reverse-mode automatic differentiation.", "One forward + one backward pass gives all gradients.", "It reuses cached activations instead of recomputing."],
        demo: "backprop",
      },
      activations: {
        title: "Activation Functions",
        oneLine: "The per-neuron nonlinearity that gives a network its expressive power.",
        sections: [
          { h: "The intuition", paras: [
            "Activations decide whether and how strongly a neuron fires. ReLU is the default - cheap, and it avoids the vanishing gradients that crippled deep sigmoid networks. Variants (LeakyReLU, GELU, SiLU) tweak the behavior near zero. The choice affects how easily gradients flow through depth.",
          ] },
          { h: "The math", paras: ["ReLU passes positives and zeroes negatives:"],
            tex: "\\mathrm{ReLU}(x) = \\max(0, x)", texNote: "Its gradient is 1 for positive inputs - no shrinking signal as depth grows." },
          { h: "In code", code: "import numpy as np\nrelu  = lambda x: np.maximum(0, x)\ngelu  = lambda x: 0.5 * x * (1 + np.tanh(0.797 * (x + 0.044 * x**3)))\nsilu  = lambda x: x / (1 + np.exp(-x))", caption: "Different shapes near zero, same job: inject nonlinearity." },
        ],
        takeaways: ["Activations make a deep stack more than one linear layer.", "ReLU keeps gradients alive through depth.", "GELU/SiLU are smooth variants common in transformers."],
        demo: "activations",
      },
      optimizers: {
        title: "Optimizers: SGD to Adam",
        oneLine: "Turn raw gradients into stable, fast parameter updates.",
        sections: [
          { h: "The intuition", paras: [
            "Plain SGD takes a fixed step against the gradient. Momentum smooths the path by accumulating a velocity; Adam goes further, keeping per-parameter running averages of the gradient and its square so each weight gets its own adaptive step size. Adam is the default for most deep learning.",
          ] },
          { h: "The math", paras: ["Adam rescales each step by a running estimate of the gradient and its magnitude:"],
            tex: "\\theta \\leftarrow \\theta - \\eta\\,\\frac{\\hat{m}_t}{\\sqrt{\\hat{v}_t}+\\epsilon}", texNote: "m is the momentum (first moment), v the per-parameter scale (second moment)." },
          { h: "In code", code: "m = beta1*m + (1-beta1)*g\nv = beta2*v + (1-beta2)*g*g\nmh, vh = m/(1-beta1**t), v/(1-beta2**t)\ntheta -= lr * mh / (np.sqrt(vh) + 1e-8)", caption: "Momentum plus per-parameter scaling - the Adam update." },
        ],
        takeaways: ["Momentum smooths noisy gradients into a steadier path.", "Adam gives each parameter its own adaptive step size.", "It is the safe default for most deep networks."],
        demo: "optimizers",
      },
      "batch-norm": {
        title: "Batch Normalization",
        oneLine: "Normalize activations across the batch to stabilize training.",
        sections: [
          { h: "The intuition", paras: [
            "As signals pass through layers, their scale can drift and stall learning. Batch norm renormalizes each feature to zero mean and unit variance over the mini-batch, then lets the network rescale with learned parameters. It smooths the loss landscape, allows higher learning rates, and adds a little regularizing noise.",
          ] },
          { h: "The math", paras: ["Standardize over the batch, then shift and scale:"],
            tex: "\\hat{x} = \\frac{x-\\mu_B}{\\sqrt{\\sigma_B^2+\\epsilon}},\\quad y = \\gamma\\hat{x}+\\beta", texNote: "gamma and beta are learned; at inference, running statistics replace the batch ones." },
          { h: "In code", code: "mu = x.mean(0); var = x.var(0)\nxhat = (x - mu) / np.sqrt(var + 1e-5)\ny = gamma * xhat + beta", caption: "Standardize per feature, then let the net rescale." },
        ],
        takeaways: ["Batch norm keeps activation statistics stable across depth.", "It enables higher learning rates and faster convergence.", "Layer norm is the batch-free variant used in transformers."],
        demo: "batch-norm",
      },
      "weight-init": {
        title: "Weight Initialization",
        oneLine: "Start with the right variance so signals neither vanish nor explode.",
        sections: [
          { h: "The intuition", paras: [
            "If initial weights are too small, activations shrink to nothing through depth; too large, and they blow up. Good initialization sets the variance so the signal's scale is preserved layer to layer. Xavier targets this for tanh, He for ReLU.",
          ] },
          { h: "The math", paras: ["He initialization scales by the fan-in for ReLU networks:"],
            tex: "W \\sim \\mathcal{N}\\!\\Big(0,\\ \\tfrac{2}{n_{\\text{in}}}\\Big)", texNote: "The 2 compensates for ReLU zeroing half the activations." },
          { h: "In code", code: "import numpy as np\n# He init for a ReLU layer\nW = np.random.randn(n_out, n_in) * np.sqrt(2.0 / n_in)", caption: "Set the variance to keep signal scale constant through depth." },
        ],
        takeaways: ["Initialization controls whether deep signals vanish or explode.", "Xavier suits tanh; He suits ReLU.", "It matters most before normalization layers are added."],
        demo: "weight-init",
      },
    },
  },

  cnn: {
    title: "Convolutional Neural Networks",
    intro: "Vision-shaped networks: slide learnable filters over the image, share weights for translation equivariance, and regularize with augmentation.",
    order: ["convolution", "cnn", "data-augmentation"],
    lessons: {
      convolution: {
        title: "Convolution",
        oneLine: "Slide a small learnable kernel over the input to detect local patterns.",
        sections: [
          { h: "The intuition", paras: [
            "A convolution slides a small filter across the image, computing a weighted sum at every position. Because the same weights are reused everywhere, the layer detects a pattern (an edge, a texture) wherever it appears, with far fewer parameters than a dense layer. Stacking convolutions builds from edges to objects.",
          ] },
          { h: "The math", paras: ["Each output pixel is a dot product of the kernel with a local patch:"],
            tex: "(I * K)(i,j) = \\sum_{m,n} I(i+m,\\,j+n)\\,K(m,n)", texNote: "Weight sharing gives translation equivariance and parameter efficiency." },
          { h: "In code", code: "import numpy as np\n\ndef conv2d(I, K):\n    kh, kw = K.shape\n    out = np.zeros((I.shape[0]-kh+1, I.shape[1]-kw+1))\n    for i in range(out.shape[0]):\n        for j in range(out.shape[1]):\n            out[i, j] = (I[i:i+kh, j:j+kw] * K).sum()\n    return out", caption: "One kernel, reused at every position." },
        ],
        takeaways: ["Convolution applies a shared filter across all positions.", "Weight sharing gives translation equivariance and few parameters.", "Stacked convolutions grow from edges to objects."],
        demo: "convolution",
      },
      cnn: {
        title: "Convolutional Networks",
        oneLine: "Stack convolutions and pooling into a hierarchy of visual features.",
        sections: [
          { h: "The intuition", paras: [
            "A CNN interleaves convolutions (detect features) with pooling (shrink and gain invariance), building a hierarchy from edges to textures to object parts. The final feature map feeds a classifier or a detector head. This inductive bias - locality and weight sharing - is what makes vision models data-efficient.",
          ] },
          { h: "The math", paras: ["Pooling downsamples a region to one value, e.g. the max:"],
            tex: "y_{i,j} = \\max_{(m,n)\\in R_{i,j}} x_{m,n}", texNote: "Each conv-pool stage widens the receptive field and adds translation invariance." },
          { h: "In code", code: "def max_pool(x, k=2):\n    h, w = x.shape\n    return x[:h//k*k, :w//k*k].reshape(h//k, k, w//k, k).max((1, 3))", caption: "Conv to detect, pool to summarize - repeat, then classify." },
        ],
        takeaways: ["CNNs build a feature hierarchy via conv + pool stages.", "Locality and weight sharing make them data-efficient on images.", "Detection and segmentation reuse the same backbone."],
        demo: "nms",
      },
      "data-augmentation": {
        title: "Data Augmentation",
        oneLine: "Manufacture label-preserving variety to regularize a vision model.",
        sections: [
          { h: "The intuition", paras: [
            "A flipped, rotated, or cropped cat is still a cat. Augmentation applies these label-preserving transforms during training so the model sees far more variety than the raw dataset holds, teaching invariance to nuisance factors and curbing overfitting - the cheapest regularizer in vision.",
          ] },
          { h: "The math", paras: ["Train on transformed inputs whose label is unchanged:"],
            tex: "(x, y) \\;\\longrightarrow\\; (T(x),\\, y),\\quad T \\sim \\mathcal{T}", texNote: "T is sampled fresh each epoch; the family T encodes which variations should not change the label." },
          { h: "In code", code: "import numpy as np\n\ndef augment(img):\n    if np.random.rand() < 0.5: img = img[:, ::-1]      # h-flip\n    img = np.roll(img, np.random.randint(-3, 4), axis=0) # shift\n    return img", caption: "Fresh random transforms each epoch multiply the effective data." },
        ],
        takeaways: ["Augmentation adds label-preserving variety for free.", "It teaches invariance and reduces overfitting.", "Strong augmentation underpins modern self-supervised vision."],
        demo: "image-augmentation",
      },
    },
  },

  "rnn-nlp": {
    title: "Sequence Models and NLP",
    intro: "Modeling order before transformers: Markov chains, learned word vectors, recurrent state, and the gates that made it trainable.",
    order: ["markov", "word2vec", "rnn", "lstm-gates"],
    lessons: {
      markov: {
        title: "Markov Chains",
        oneLine: "Model a sequence where the next step depends only on the current state.",
        sections: [
          { h: "The intuition", paras: [
            "A Markov chain assumes the future depends on the present, not the full past. n-gram language models are exactly this: predict the next token from the last few. It is a weak assumption that is still a surprisingly strong baseline - and the conceptual ancestor of every sequence model.",
          ] },
          { h: "The math", paras: ["The Markov property drops all but the current state:"],
            tex: "P(x_t \\mid x_{<t}) = P(x_t \\mid x_{t-1})", texNote: "Transition probabilities are just normalized counts of observed pairs." },
          { h: "In code", code: "from collections import Counter, defaultdict\n\ndef fit_bigram(tokens):\n    trans = defaultdict(Counter)\n    for a, b in zip(tokens, tokens[1:]):\n        trans[a][b] += 1\n    return trans            # sample next token from trans[current]", caption: "Count pairs, normalize, sample - an n-gram model." },
        ],
        takeaways: ["Markov models condition only on the current state.", "n-gram language models are Markov chains over tokens.", "They are a strong, simple baseline for sequences."],
        demo: "markov",
      },
      word2vec: {
        title: "Word2Vec",
        oneLine: "Learn word vectors by predicting a word from its context.",
        sections: [
          { h: "The intuition", paras: [
            "Words that appear in similar contexts should have similar vectors. Skip-gram trains embeddings by pushing a word's vector toward the words around it and away from random negatives. The result is the famous geometry where king - man + woman lands near queen.",
          ] },
          { h: "The math", paras: ["Skip-gram maximizes the probability of context given the center word:"],
            tex: "P(c\\mid w) = \\frac{\\exp(v_c^{\\top} v_w)}{\\sum_{c'}\\exp(v_{c'}^{\\top} v_w)}", texNote: "Negative sampling approximates the costly denominator with a few random words." },
          { h: "In code", code: "# one skip-gram step with negative sampling\nscore = v_center @ v_context\ngrad = (sigmoid(score) - label) * v_center   # label 1 for true ctx, 0 for neg\nv_context -= lr * grad", caption: "Pull true context together, push negatives apart." },
        ],
        takeaways: ["Distributional meaning: context predicts the embedding.", "Negative sampling makes training cheap.", "It produces vectors with linear analogy structure."],
        demo: "word2vec",
      },
      rnn: {
        title: "Recurrent Networks",
        oneLine: "Carry a hidden state across time to model sequences of any length.",
        sections: [
          { h: "The intuition", paras: [
            "An RNN reads a sequence one step at a time, updating a hidden state that summarizes everything seen so far. The same weights apply at every step, so it handles arbitrary lengths. It was the pre-transformer way to model order - but long-range dependencies are hard because gradients vanish through time.",
          ] },
          { h: "The math", paras: ["The hidden state recurs through a shared cell:"],
            tex: "h_t = \\tanh\\!\\big(W_h h_{t-1} + W_x x_t + b\\big)", texNote: "Trained by backprop through time; repeated multiplication makes gradients vanish or explode." },
          { h: "In code", code: "import numpy as np\n\ndef rnn(xs, h, Wh, Wx, b):\n    for x in xs:\n        h = np.tanh(Wh @ h + Wx @ x + b)\n    return h            # summary of the whole sequence", caption: "One shared cell, unrolled over the sequence." },
        ],
        takeaways: ["RNNs maintain a running summary in a hidden state.", "Shared weights handle variable-length input.", "Vanishing gradients limit their memory - which LSTMs address."],
        demo: "rnn-gates",
      },
      "lstm-gates": {
        title: "LSTM Gates",
        oneLine: "Gates let a recurrent net keep or forget information over long spans.",
        sections: [
          { h: "The intuition", paras: [
            "The LSTM adds a cell state that information can travel along nearly untouched, controlled by gates: a forget gate decides what to drop, an input gate what to add, an output gate what to expose. This gated highway keeps gradients alive far longer than a plain RNN.",
          ] },
          { h: "The math", paras: ["Each gate is a learned sigmoid; the cell is updated additively:"],
            tex: "c_t = f_t \\odot c_{t-1} + i_t \\odot \\tilde{c}_t", texNote: "The additive update is what preserves gradient flow across many steps." },
          { h: "In code", code: "f = sigmoid(Wf @ z)    # forget\ni = sigmoid(Wi @ z)    # input\no = sigmoid(Wo @ z)    # output\nc = f * c + i * np.tanh(Wc @ z)\nh = o * np.tanh(c)", caption: "Gates throttle what the cell keeps, adds, and reveals." },
        ],
        takeaways: ["LSTM gates control keep / add / expose for the cell state.", "The additive cell update fights vanishing gradients.", "GRUs are a lighter, two-gate variant."],
        demo: "rnn-gates",
      },
    },
  },

  "advanced-nlp": {
    title: "Advanced NLP and Generation",
    intro: "Beyond a single forward pass: search for better continuations, encode position efficiently, and cache computation so generation is fast.",
    order: ["beam-search", "rope", "kv-cache"],
    lessons: {
      "beam-search": {
        title: "Beam Search",
        oneLine: "Keep several candidate continuations instead of committing greedily.",
        sections: [
          { h: "The intuition", paras: [
            "Greedy decoding picks the single best next token and can paint itself into a corner. Beam search keeps the B most probable partial sequences at each step, expanding all of them and pruning back to B. It finds higher-probability sequences than greedy at B times the cost.",
          ] },
          { h: "The math", paras: ["Score a sequence by its summed log-probability and keep the top B:"],
            tex: "s(y_{1:t}) = \\sum_{k=1}^{t} \\log P(y_k \\mid y_{<k})", texNote: "Length-normalize the score, or beam search favors short sequences." },
          { h: "In code", code: "def expand(beams, logp):\n    cand = []\n    for seq, s in beams:\n        for tok, lp in logp(seq):\n            cand.append((seq + [tok], s + lp))\n    return sorted(cand, key=lambda x: -x[1])[:B]", caption: "Expand every beam, keep the top B by score." },
        ],
        takeaways: ["Beam search tracks the top-B partial sequences.", "It beats greedy on sequence probability at B times the cost.", "Length normalization stops it preferring short outputs."],
        demo: "beam-search",
      },
      rope: {
        title: "Rotary Position Embeddings",
        oneLine: "Encode position by rotating query and key vectors.",
        sections: [
          { h: "The intuition", paras: [
            "Instead of adding a position signal, RoPE rotates each query and key by an angle proportional to its position. Because a dot product of two rotated vectors depends only on their angle difference, attention naturally sees relative position - and it extrapolates to longer contexts better than learned absolute embeddings.",
          ] },
          { h: "The math", paras: ["Rotate by a position-dependent angle so dot products encode relative offset:"],
            tex: "\\langle R_{\\theta m} q,\\ R_{\\theta n} k\\rangle = g(q, k,\\ m-n)", texNote: "The result depends on m - n, the relative position, not the absolute indices." },
          { h: "In code", code: "import numpy as np\n\ndef rope(x, pos, base=10000):\n    d = x.shape[-1]; i = np.arange(0, d, 2)\n    theta = pos / base ** (i / d)\n    c, s = np.cos(theta), np.sin(theta)\n    return np.stack([x[..., ::2]*c - x[..., 1::2]*s,\n                     x[..., ::2]*s + x[..., 1::2]*c], -1).reshape(x.shape)", caption: "Rotate pairs of dimensions by a position-scaled angle." },
        ],
        takeaways: ["RoPE encodes position by rotating Q and K.", "Attention then sees relative position for free.", "It extends to longer contexts better than absolute encodings."],
        demo: "rope",
      },
      "kv-cache": {
        title: "The KV Cache",
        oneLine: "Cache past keys and values so each new token is cheap to generate.",
        sections: [
          { h: "The intuition", paras: [
            "When generating text token by token, the keys and values for all previous tokens never change. Recomputing them every step is wasteful. The KV cache stores them, so producing the next token only computes one new query against the cached keys and values - turning quadratic regeneration into linear growth.",
          ] },
          { h: "The math", paras: ["Step t attends a single new query against all cached keys and values:"],
            tex: "o_t = \\mathrm{softmax}\\!\\Big(\\tfrac{q_t K_{1:t}^{\\top}}{\\sqrt{d}}\\Big) V_{1:t}", texNote: "Only q_t is new each step; K and V are appended to and reused from the cache." },
          { h: "In code", code: "# generation loop with a growing cache\nK_cache, V_cache = [], []\nfor step in range(max_len):\n    q, k, v = project(next_token)\n    K_cache.append(k); V_cache.append(v)\n    out = attend(q, np.array(K_cache), np.array(V_cache))", caption: "Append the new key/value; reuse all the old ones." },
        ],
        takeaways: ["The KV cache stores past keys and values across steps.", "It makes per-token generation cost grow linearly, not quadratically.", "Its memory cost motivates cache eviction and paging."],
        demo: "kv-cache",
      },
    },
  },

};

// resolve a sub-lesson + its module context; null if missing.
window.DM_SUBLESSON = function (moduleSlug, conceptId) {
  const m = (window.SUB_LESSONS || {})[moduleSlug];
  if (!m) return null;
  const lesson = m.lessons[conceptId];
  if (!lesson) return null;
  const order = m.order || Object.keys(m.lessons);
  const i = order.indexOf(conceptId);
  return {
    module: m, moduleSlug, conceptId, lesson, order, index: i,
    prev: i > 0 ? order[i - 1] : null,
    next: i >= 0 && i < order.length - 1 ? order[i + 1] : null,
  };
};
