// sub-lessons.js — per-concept sub-lessons that break each ML-from-scratch module
// down into the concepts it teaches. Each module page (module-app.jsx) renders its
// concept sequence as a "Concept by concept" syllabus; each concept gets its own
// taught lesson page at learn/<module>/<concept>/ (concept-lesson-app.jsx).
//
// This is the TAUGHT companion to the reference /concepts/<id>/ hub pages: intuition
// -> the math (KaTeX) -> a small code illustration -> takeaways -> a live demo to play
// with. Data-driven like lectures.js / paths.js. Pages are generated by
// _private/scripts/gen-sublesson-pages.mjs (re-run when you add a module/lesson).
//
// SHAPE
//   SUB_LESSONS[<moduleSlug>] = {
//     title, intro, order: [<conceptId>...],
//     lessons: { <conceptId>: {
//       title, oneLine,
//       sections: [{ h, paras?:[..], tex?, texNote?, code?, caption? }],
//       takeaways: [..], demo?: <visualizeSlug>
//     } }
//   }
// A lesson's concept id resolves to its /concepts/<id>/ hub page automatically.

window.SUB_LESSONS = {
  transformers: {
    title: "Transformers",
    intro: "The architecture behind modern language models, built one idea at a time: turn text into tokens, tokens into vectors, give them a sense of order, let them attend to each other, stack that into a block, and decode the result back into text.",
    order: ["tokenization", "embeddings", "positional-encoding", "attention", "multi-head", "transformer-block", "decoding"],
    lessons: {
      tokenization: {
        title: "Tokenization",
        oneLine: "Turn raw text into the discrete tokens a model actually consumes.",
        sections: [
          { h: "The intuition", paras: [
            "A language model never sees characters or words — it sees a sequence of integer token ids drawn from a fixed vocabulary. Tokenization is the step that converts a string into that sequence, and back.",
            "Word-level vocabularies explode and choke on typos and rare words; character-level keeps the vocabulary tiny but makes sequences painfully long. Subword tokenization (BPE, WordPiece, Unigram) is the compromise everyone uses: common words stay whole, rare ones split into reusable pieces, and nothing is ever out-of-vocabulary.",
          ] },
          { h: "The math", paras: [
            "Byte-Pair Encoding learns its vocabulary greedily. Start from single characters, then repeatedly merge the adjacent pair with the highest frequency across the corpus until you hit the target vocabulary size:",
          ], tex: "(a,b)^\\star = \\arg\\max_{(a,b)}\\; \\mathrm{count}(a,b)", texNote: "Each chosen pair becomes a new token; the merge list, applied in order, is the tokenizer." },
          { h: "In code", code: "from collections import Counter\n\n# greedy BPE merge step over a corpus of symbol-lists\ndef best_pair(corpus):\n    pairs = Counter()\n    for word in corpus:                # word = ['l','o','w','</w>']\n        for a, b in zip(word, word[1:]):\n            pairs[(a, b)] += 1\n    return pairs.most_common(1)[0][0]  # the pair to merge next\n\ndef merge(corpus, pair):\n    a, b = pair\n    return [_join(word, a, b) for word in corpus]", caption: "Run best_pair -> merge in a loop until the vocabulary reaches the size you want." },
        ],
        takeaways: [
          "Models operate on token ids, not text — tokenization defines what a 'unit' even is.",
          "Subword tokenizers trade vocabulary size against sequence length and eliminate out-of-vocabulary words.",
          "BPE is just: merge the most frequent adjacent pair, repeat.",
        ],
        demo: "tokenizer",
      },
      embeddings: {
        title: "Embeddings",
        oneLine: "Map each token id to a dense vector whose geometry carries meaning.",
        sections: [
          { h: "The intuition", paras: [
            "A token id is just an index — id 4017 means nothing on its own. An embedding layer is a learned lookup table that turns each id into a vector of real numbers, and training shapes that table so related tokens land near each other.",
            "Once tokens are vectors, 'meaning' becomes geometry: similarity is a dot product, analogies are directions, and every later layer gets to do linear algebra instead of string matching.",
          ] },
          { h: "The math", paras: [
            "The embedding matrix is E in R^(V x d) for vocabulary size V and model width d. Looking up token i is just selecting a row:",
          ], tex: "e_i = E_{i,:} \\in \\mathbb{R}^{d}", texNote: "E is a parameter — it is learned by gradient descent like any other weight." },
          { h: "In code", code: "import numpy as np\n\nV, d = 50000, 256\nE = np.random.randn(V, d) * 0.02      # learned embedding table\n\nids = np.array([101, 4017, 2009])     # a tokenized sentence\nx = E[ids]                            # (3, d) — one vector per token\n\n# similarity between two tokens is a dot product\ncos = E[4017] @ E[2009] / (np.linalg.norm(E[4017]) * np.linalg.norm(E[2009]))", caption: "The whole layer is a row-select; the magic is in what training writes into E." },
        ],
        takeaways: [
          "Embeddings convert discrete ids into a continuous space where similarity is measurable.",
          "The table is learned, so structure (synonyms, analogies) emerges from the training objective.",
          "Every downstream layer benefits — they all operate on vectors, never on tokens.",
        ],
        demo: "embeddings",
      },
      "positional-encoding": {
        title: "Positional Encoding",
        oneLine: "Inject order into a model that otherwise treats its input as a set.",
        sections: [
          { h: "The intuition", paras: [
            "Attention has no built-in notion of order — shuffle the tokens and the raw computation is unchanged. But language is sequential: 'dog bites man' is not 'man bites dog'. Positional encodings add a position-dependent signal to each token vector so the model can tell where each token sits.",
            "The classic transformer uses fixed sinusoids of geometrically increasing wavelength. Because sines and cosines combine linearly, the model can represent relative offsets — a useful inductive bias that also extends to lengths never seen in training.",
          ] },
          { h: "The math", paras: [
            "For position pos and dimension i, the encoding interleaves sine and cosine across a spectrum of frequencies:",
          ], tex: "PE_{(pos,2i)} = \\sin\\!\\Big(\\tfrac{pos}{10000^{2i/d}}\\Big),\\quad PE_{(pos,2i+1)} = \\cos\\!\\Big(\\tfrac{pos}{10000^{2i/d}}\\Big)", texNote: "Added to the token embedding before the first attention layer." },
          { h: "In code", code: "import numpy as np\n\ndef positional_encoding(seq_len, d):\n    pos = np.arange(seq_len)[:, None]\n    i = np.arange(d)[None, :]\n    angle = pos / np.power(10000, (2 * (i // 2)) / d)\n    pe = np.where(i % 2 == 0, np.sin(angle), np.cos(angle))\n    return pe                          # (seq_len, d), add to embeddings", caption: "Different dimensions oscillate at different rates — a positional fingerprint." },
        ],
        takeaways: [
          "Self-attention is permutation-invariant; position must be added explicitly.",
          "Sinusoidal encodings let the model reason about relative position and generalize past trained lengths.",
          "Modern variants (RoPE, ALiBi) encode position inside attention instead of adding it up front.",
        ],
        demo: "positional-encoding",
      },
      attention: {
        title: "Attention",
        oneLine: "Weight every token by how relevant it is to the one you are computing.",
        sections: [
          { h: "The intuition", paras: [
            "Attention lets each token pull in information from every other token, weighted by relevance. Each token emits a query (what am I looking for?), a key (what do I offer?), and a value (what I'll pass along). A token's output is a relevance-weighted average of everyone's values.",
            "This is the operation that replaced recurrence: instead of passing a state step by step, every token talks to every other token in one parallel step.",
          ] },
          { h: "The math", paras: [
            "Scaled dot-product attention scores each query against every key, softmax-normalizes the scores into weights, and mixes the values. The 1/sqrt(d_k) keeps the dot products from saturating the softmax:",
          ], tex: "\\mathrm{Attention}(Q,K,V) = \\mathrm{softmax}\\!\\Big(\\tfrac{QK^{\\top}}{\\sqrt{d_k}}\\Big)V", texNote: "Q, K, V are linear projections of the input. See the full derivation in the on-site Self-Attention lesson." },
          { h: "In code", code: "import numpy as np\n\ndef attention(Q, K, V):\n    dk = Q.shape[-1]\n    scores = Q @ K.T / np.sqrt(dk)     # (n, n) relevance\n    scores -= scores.max(-1, keepdims=True)\n    w = np.exp(scores)\n    w /= w.sum(-1, keepdims=True)      # softmax over keys\n    return w @ V                       # weighted mix of values", caption: "Three matmuls and a softmax — the core of every transformer." },
        ],
        takeaways: [
          "Attention is a content-based, weighted average of values — no recurrence required.",
          "Queries and keys decide the weights; values carry the information.",
          "The sqrt(d_k) scaling keeps gradients healthy as the dimension grows.",
        ],
        demo: "attention",
      },
      "multi-head": {
        title: "Multi-Head Attention",
        oneLine: "Run several attention patterns in parallel, then combine them.",
        sections: [
          { h: "The intuition", paras: [
            "One attention map forces every token to mix information in a single way. Real language needs several relationships at once — syntactic agreement, coreference, local phrasing. Multi-head attention splits the model width into h smaller subspaces, runs attention independently in each, and concatenates the results.",
            "Each head is cheap (it works in d/h dimensions), and together they let the layer attend to different things in different subspaces simultaneously.",
          ] },
          { h: "The math", paras: [
            "Each head projects Q, K, V into its own subspace, attends there, and the outputs are concatenated and mixed by a final projection W^O:",
          ], tex: "\\mathrm{MultiHead}(X) = \\mathrm{Concat}(\\mathrm{head}_1,\\dots,\\mathrm{head}_h)\\,W^{O}", texNote: "head_i = Attention(XW_i^Q, XW_i^K, XW_i^V); the heads run fully in parallel." },
          { h: "In code", code: "import numpy as np\n\ndef multi_head(X, Wq, Wk, Wv, Wo, h):\n    n, d = X.shape\n    dk = d // h\n    outs = []\n    for i in range(h):                 # each head sees a d/h slice\n        sl = slice(i * dk, (i + 1) * dk)\n        outs.append(attention(X @ Wq[:, sl], X @ Wk[:, sl], X @ Wv[:, sl]))\n    return np.concatenate(outs, axis=-1) @ Wo", caption: "Heads are independent; the final W^O lets them interact." },
        ],
        takeaways: [
          "Multiple heads capture multiple relationships in parallel subspaces.",
          "Splitting the width keeps the total cost the same as single-head attention.",
          "The output projection W^O lets the heads' results recombine.",
        ],
        demo: "multi-head-attention",
      },
      "transformer-block": {
        title: "The Transformer Block",
        oneLine: "Stack attention and an MLP with residuals and normalization into one repeatable unit.",
        sections: [
          { h: "The intuition", paras: [
            "A transformer is just the same block stacked many times. Each block does two things: mix information across tokens (attention), then transform each token on its own (a small MLP). Residual connections let signal and gradients flow straight through, and layer normalization keeps the activations well-scaled at every depth.",
            "This residual-and-norm sandwich is what makes very deep stacks trainable at all.",
          ] },
          { h: "The math", paras: [
            "With pre-norm placement, each sub-layer reads a normalized input and adds its result back to the residual stream:",
          ], tex: "\\begin{aligned} x &\\leftarrow x + \\mathrm{MHA}(\\mathrm{LN}(x)) \\\\ x &\\leftarrow x + \\mathrm{MLP}(\\mathrm{LN}(x)) \\end{aligned}", texNote: "The MLP is two linear layers with a nonlinearity, applied to each token independently." },
          { h: "In code", code: "def transformer_block(x, attn, mlp, ln1, ln2):\n    x = x + attn(ln1(x))               # mix across tokens\n    x = x + mlp(ln2(x))                # transform each token\n    return x\n\n# a stack is just this block, repeated\ndef transformer(x, blocks):\n    for blk in blocks:\n        x = blk(x)\n    return x", caption: "Residual + norm around two sub-layers — repeat N times." },
        ],
        takeaways: [
          "A transformer is one block (attention + MLP) stacked with residuals and normalization.",
          "Residual connections keep gradients flowing through deep stacks.",
          "Attention mixes tokens; the MLP processes each token independently.",
        ],
        demo: "multi-head-attention",
      },
      decoding: {
        title: "Decoding",
        oneLine: "Turn the model's next-token distribution into actual generated text.",
        sections: [
          { h: "The intuition", paras: [
            "A language model outputs a probability distribution over the next token. Decoding is the policy that picks one — and that choice shapes everything about the output. Always taking the argmax (greedy) is fluent but repetitive; sampling adds variety but can wander.",
            "Temperature sharpens or flattens the distribution; top-k and top-p (nucleus) clip the long tail so you sample only from plausible tokens; beam search keeps several candidate continuations at once.",
          ] },
          { h: "The math", paras: [
            "Temperature T rescales the logits before the softmax — low T concentrates probability on the top tokens, high T spreads it out:",
          ], tex: "p_i = \\frac{\\exp(z_i / T)}{\\sum_j \\exp(z_j / T)}", texNote: "T -> 0 recovers greedy argmax; T = 1 is the model's raw distribution." },
          { h: "In code", code: "import numpy as np\n\ndef sample(logits, T=1.0, top_p=0.9):\n    z = logits / T\n    p = np.exp(z - z.max()); p /= p.sum()\n    order = np.argsort(p)[::-1]                 # nucleus: keep smallest\n    keep = order[np.cumsum(p[order]) <= top_p]  # set with mass >= top_p\n    if len(keep) == 0: keep = order[:1]\n    p2 = p[keep] / p[keep].sum()\n    return np.random.choice(keep, p=p2)", caption: "Temperature reshapes the distribution; top-p trims the tail before sampling." },
        ],
        takeaways: [
          "Decoding is a separate policy on top of the model's distribution — it controls the style of the output.",
          "Temperature trades determinism for diversity; top-k / top-p remove implausible tokens.",
          "Greedy is just temperature -> 0; beam search searches several continuations at once.",
        ],
        demo: "decoding",
      },
    },
  },
};

// resolve a sub-lesson + its module context; null if missing.
window.DM_SUBLESSON = function (moduleSlug, conceptId) {
  const m = (window.SUB_LESSONS || {})[moduleSlug];
  if (!m) return null;
  const lesson = m.lessons[conceptId];
  if (!lesson) return null;
  const order = m.order || Object.keys(m.lessons);
  const i = order.indexOf(conceptId);
  return {
    module: m, moduleSlug, conceptId, lesson, order, index: i,
    prev: i > 0 ? order[i - 1] : null,
    next: i >= 0 && i < order.length - 1 ? order[i + 1] : null,
  };
};
