import { defineConfig } from 'vite'

// Build-only: swap the CDN React from development to production.min (smaller,
// faster, no warnings) and drop the now-mismatched SRI hashes. Dev keeps the
// development build for useful warnings while iterating.
const reactProdInBuild = {
  name: 'react-prod-in-build',
  apply: 'build',
  transformIndexHtml(html) {
    return html
      .replace('react@18.3.1/umd/react.development.js', 'react@18.3.1/umd/react.production.min.js')
      .replace('react-dom@18.3.1/umd/react-dom.development.js', 'react-dom@18.3.1/umd/react-dom.production.min.js')
      .replace(/ integrity="sha384-hD6[^"]*"/, '')
      .replace(/ integrity="sha384-u6a[^"]*"/, '')
  },
}

// Multi-page static build for GitHub Pages.
//
// The site keeps its original "global script" architecture: React + ReactDOM
// are loaded as UMD globals from a CDN (regular <script> tags in each HTML),
// and the page's .jsx files run as ES module scripts in source order, talking
// to each other through `window` side-effects (e.g. window.NeuralNet = ...).
// Vite/esbuild only needs to (a) transpile JSX using the global React, and
// (b) bundle + minify those module scripts. So we set classic JSX factory.
export default defineConfig({
  appType: 'mpa',
  base: '/',
  plugins: [reactProdInBuild],
  esbuild: {
    jsxFactory: 'React.createElement',
    jsxFragment: 'React.Fragment',
  },
  build: {
    target: 'es2020',
    outDir: 'dist',
    emptyOutDir: true,
    rollupOptions: {
      input: {
        home: 'index.html',
        about: 'about/index.html',
        work: 'work/index.html',
        research: 'research/index.html',
        learn: 'learn/index.html',
        'learn-ml-from-scratch': 'learn/ml-from-scratch/index.html',
        'learn-building-with-genai': 'learn/building-with-genai/index.html',
        'learn-notes': 'learn/notes/index.html',
        'weekly-insights': 'weekly-insights/index.html',
        play: 'play/index.html',
        'play-neuroevolution': 'play/neuroevolution/index.html',
        'play-tic-tac-toe': 'play/tic-tac-toe/index.html',
        'play-rps': 'play/rps/index.html',
        'play-connect-four': 'play/connect-four/index.html',
        'play-twenty48': 'play/twenty48/index.html',
        'play-wordle': 'play/wordle/index.html',
        'play-minesweeper': 'play/minesweeper/index.html',
        'play-chess': 'play/chess/index.html',
        'play-snake-dqn': 'play/snake-dqn/index.html',
        'play-self-driving': 'play/self-driving/index.html',
        'play-poker': 'play/poker/index.html',
        'play-go': 'play/go/index.html',
        visualize: 'visualize/index.html',
        'visualize-pathfinding': 'visualize/pathfinding/index.html',
        'visualize-kmeans': 'visualize/kmeans/index.html',
        'visualize-gradient-descent': 'visualize/gradient-descent/index.html',
        'visualize-overfitting': 'visualize/overfitting/index.html',
        'visualize-roc': 'visualize/roc/index.html',
        'visualize-decision-tree': 'visualize/decision-tree/index.html',
        'visualize-knn': 'visualize/knn/index.html',
        'visualize-svm': 'visualize/svm/index.html',
        'visualize-pca': 'visualize/pca/index.html',
        'visualize-gmm': 'visualize/gmm/index.html',
        'visualize-markov': 'visualize/markov/index.html',
        'visualize-decoding': 'visualize/decoding/index.html',
        'visualize-activations': 'visualize/activations/index.html',
        'visualize-clt': 'visualize/clt/index.html',
        'visualize-fourier': 'visualize/fourier/index.html',
        'visualize-attention': 'visualize/attention/index.html',
        'visualize-multi-head-attention': 'visualize/multi-head-attention/index.html',
        'visualize-positional-encoding': 'visualize/positional-encoding/index.html',
        'visualize-tokenizer': 'visualize/tokenizer/index.html',
        'visualize-gridworld-rl': 'visualize/gridworld-rl/index.html',
        'visualize-bandit': 'visualize/bandit/index.html',
        'visualize-value-iteration': 'visualize/value-iteration/index.html',
        'visualize-neural-playground': 'visualize/neural-playground/index.html',
        'visualize-convolution': 'visualize/convolution/index.html',
        'visualize-nms': 'visualize/nms/index.html',
        'visualize-diffusion': 'visualize/diffusion/index.html',
        'visualize-vae': 'visualize/vae/index.html',
        'visualize-embeddings': 'visualize/embeddings/index.html',
        'visualize-vector-search': 'visualize/vector-search/index.html',
        'visualize-forecasting': 'visualize/forecasting/index.html',
        'visualize-lr-schedule': 'visualize/lr-schedule/index.html',
        'visualize-lora': 'visualize/lora/index.html',
        'visualize-scaling-laws': 'visualize/scaling-laws/index.html',
        'visualize-bayes': 'visualize/bayes/index.html',
        'visualize-optimizers': 'visualize/optimizers/index.html',
        'visualize-gan': 'visualize/gan/index.html',
        'visualize-backprop': 'visualize/backprop/index.html',
        'visualize-mcts': 'visualize/mcts/index.html',
        'visualize-simulated-annealing': 'visualize/simulated-annealing/index.html',
        'visualize-regression': 'visualize/regression/index.html',
        'visualize-rnn-gates': 'visualize/rnn-gates/index.html',
        'visualize-beam-search': 'visualize/beam-search/index.html',
        'visualize-kv-cache': 'visualize/kv-cache/index.html',
        'visualize-gnn': 'visualize/gnn/index.html',
        'visualize-rope': 'visualize/rope/index.html',
        'visualize-dbscan': 'visualize/dbscan/index.html',
        'visualize-policy-gradient': 'visualize/policy-gradient/index.html',
        cases: 'cases/index.html',
        'm-foundations': 'learn/foundations/index.html',
        'm-supervised-learning': 'learn/supervised-learning/index.html',
        'm-unsupervised-learning': 'learn/unsupervised-learning/index.html',
        'm-ml-theory': 'learn/ml-theory/index.html',
        'm-neural-nets': 'learn/neural-nets/index.html',
        'm-cnn': 'learn/cnn/index.html',
        'm-rnn-nlp': 'learn/rnn-nlp/index.html',
        'm-transformers': 'learn/transformers/index.html',
        'm-advanced-cv': 'learn/advanced-cv/index.html',
        'm-advanced-nlp': 'learn/advanced-nlp/index.html',
        'm-generative': 'learn/generative/index.html',
        'm-multimodal': 'learn/multimodal/index.html',
        'm-fine-tuning': 'learn/fine-tuning/index.html',
        'm-reinforcement-learning': 'learn/reinforcement-learning/index.html',
        'm-pytorch-internals': 'learn/pytorch-internals/index.html',
        'm-training-systems': 'learn/training-systems/index.html',
        'm-llm-systems': 'learn/llm-systems/index.html',
        'm-rag-agents': 'learn/rag-agents/index.html',
        'm-ml-applications': 'learn/ml-applications/index.html',
        'm-mlops': 'learn/mlops/index.html',
        'learn-self-attention': 'learn/transformers/self-attention/index.html',
        'kc-core': 'learn/key-concepts/index.html',
        'kc-agentic': 'learn/key-concepts/agentic/index.html',
        'kc-applications': 'learn/key-concepts/applications/index.html',
        'hf-hub': 'learn/huggingface/index.html',
        'hf-fundamentals': 'learn/huggingface/fundamentals/index.html',
        'hf-nlp': 'learn/huggingface/nlp/index.html',
        'hf-computer-vision': 'learn/huggingface/computer-vision/index.html',
        'hf-audio': 'learn/huggingface/audio/index.html',
        'hf-multimodal': 'learn/huggingface/multimodal/index.html',
        'hf-best-practices': 'learn/huggingface/best-practices/index.html',
        'hf-agentic': 'learn/huggingface/agentic/index.html',
// >>> generated:concepts
        'concepts': 'concepts/index.html',
        'concept-gradient-descent': 'concepts/gradient-descent/index.html',
        'concept-backprop': 'concepts/backprop/index.html',
        'concept-rnn': 'concepts/rnn/index.html',
        'concept-chain-rule': 'concepts/chain-rule/index.html',
        'concept-lr-schedule': 'concepts/lr-schedule/index.html',
        'concept-adam': 'concepts/adam/index.html',
        'concept-activations': 'concepts/activations/index.html',
        'concept-softmax': 'concepts/softmax/index.html',
        'concept-cross-entropy': 'concepts/cross-entropy/index.html',
        'concept-bias-variance': 'concepts/bias-variance/index.html',
        'concept-regularization': 'concepts/regularization/index.html',
        'concept-clt': 'concepts/clt/index.html',
        'concept-fourier': 'concepts/fourier/index.html',
        'concept-search-astar': 'concepts/search-astar/index.html',
        'concept-kmeans': 'concepts/kmeans/index.html',
        'concept-knn': 'concepts/knn/index.html',
        'concept-decision-tree': 'concepts/decision-tree/index.html',
        'concept-svm': 'concepts/svm/index.html',
        'concept-pca': 'concepts/pca/index.html',
        'concept-gmm-em': 'concepts/gmm-em/index.html',
        'concept-roc': 'concepts/roc/index.html',
        'concept-mlp': 'concepts/mlp/index.html',
        'concept-convolution': 'concepts/convolution/index.html',
        'concept-cnn': 'concepts/cnn/index.html',
        'concept-iou-nms': 'concepts/iou-nms/index.html',
        'concept-tokenization': 'concepts/tokenization/index.html',
        'concept-markov': 'concepts/markov/index.html',
        'concept-embeddings': 'concepts/embeddings/index.html',
        'concept-attention': 'concepts/attention/index.html',
        'concept-multi-head': 'concepts/multi-head/index.html',
        'concept-positional-encoding': 'concepts/positional-encoding/index.html',
        'concept-transformer-block': 'concepts/transformer-block/index.html',
        'concept-decoding': 'concepts/decoding/index.html',
        'concept-vae': 'concepts/vae/index.html',
        'concept-diffusion': 'concepts/diffusion/index.html',
        'concept-lora': 'concepts/lora/index.html',
        'concept-scaling-laws': 'concepts/scaling-laws/index.html',
        'concept-mdp-bellman': 'concepts/mdp-bellman/index.html',
        'concept-q-learning': 'concepts/q-learning/index.html',
        'concept-bandit': 'concepts/bandit/index.html',
        'concept-minimax': 'concepts/minimax/index.html',
        'concept-mcts': 'concepts/mcts/index.html',
        'concept-cfr': 'concepts/cfr/index.html',
        'concept-neuroevolution': 'concepts/neuroevolution/index.html',
        'concept-vector-search': 'concepts/vector-search/index.html',
        'concept-forecasting': 'concepts/forecasting/index.html',
        'concept-simulated-annealing': 'concepts/simulated-annealing/index.html',
        'concept-entropy': 'concepts/entropy/index.html',
        'concept-bayes': 'concepts/bayes/index.html',
        'concept-optimizers': 'concepts/optimizers/index.html',
        'concept-gan': 'concepts/gan/index.html',
        'concept-linear-regression': 'concepts/linear-regression/index.html',
        'concept-logistic-regression': 'concepts/logistic-regression/index.html',
        'concept-lstm-gates': 'concepts/lstm-gates/index.html',
        'concept-beam-search': 'concepts/beam-search/index.html',
        'concept-kv-cache': 'concepts/kv-cache/index.html',
        'concept-gnn': 'concepts/gnn/index.html',
        'concept-rope': 'concepts/rope/index.html',
        'concept-dbscan': 'concepts/dbscan/index.html',
        'concept-policy-gradient': 'concepts/policy-gradient/index.html',
        // <<< generated:concepts
      },
    },
  },
})
